# B2 级别标准动词（歌德 B2 考纲常见，非 Nicos Weg）
# 格式: 不定式: (过去式, 过去分词, 中文)
B2_VERBS = {
'sich bewerben': ('bewarb sich', 'sich beworben', '申请（职位）'),
'beantragen': ('beantragte', 'beantragt', '申请（正式）'),
'sich beschweren': ('beschwerte sich', 'sich beschwert', '抱怨；投诉'),
'befürchten': ('befürchtete', 'befürchtet', '担心；恐怕'),
'sich eignen': ('eignete sich', 'sich geeignet', '适合；胜任'),
'ermöglichen': ('ermöglichte', 'ermöglicht', '使可能'),
'erfordern': ('erforderte', 'erfordert', '需要；要求'),
'sich kümmern': ('kümmerte sich', 'sich gekümmert', '照顾；处理'),
'leugnen': ('leugnete', 'geleugnet', '否认'),
'verhandeln': ('verhandelte', 'verhandelt', '谈判；协商'),
'vermuten': ('vermutete', 'vermutet', '猜测；怀疑'),
'versagen': ('versagte', 'versagt', '失败；拒绝（工作）'),
'verzichten': ('verzichtete', 'verzichtet', '放弃；舍弃'),
'sich weigern': ('weigerte sich', 'sich geweigert', '拒绝'),
'behaupten': ('behauptete', 'behauptet', '声称；主张'),
'bestätigen': ('bestätigte', 'bestätigt', '证实；确认'),
'bezweifeln': ('bezweifelte', 'bezweifelt', '怀疑'),
'drohen': ('drohte', 'gedroht', '威胁'),
'sich entschließen': ('entschloss sich', 'sich entschlossen', '决定'),
'sich erinnern': ('erinnerte sich', 'sich erinnert', '记得；回忆'),
'gelingen': ('gelang', 'gelungen', '成功（es gelingt mir）'),
'scheitern': ('scheiterte', 'gescheitert', '失败'),
'sich sehnen': ('sehnte sich', 'sich gesehnt', '渴望'),
'überreden': ('überredete', 'überredet', '说服'),
'überzeugen': ('überzeugte', 'überzeugt', '使信服'),
'unterstellen': ('unterstellte', 'unterstellt', '假设；诬指'),
'verlangen': ('verlangte', 'verlangt', '要求'),
'vermeiden': ('vermied', 'vermieden', '避免'),
'versprechen': ('versprach', 'versprochen', '承诺（B2引申：有前途）'),
'vorwerfen': ('warf vor', 'vorgeworfen', '责备；指责'),
'widersprechen': ('widersprach', 'widersprochen', '反驳；矛盾'),
'zweifeln': ('zweifelte', 'gezweifelt', '怀疑'),
'sich anstrengen': ('strengte sich an', 'sich angestrengt', '努力'),
'ausreichen': ('reichte aus', 'ausgereicht', '足够'),
'beeinflussen': ('beeinflusste', 'beeinflusst', '影响'),
'beitragen': ('trug bei', 'beigetragen', '贡献；有助于'),
'benehmen': ('benahm sich', 'sich benommen', '举止；行为'),
'beruhen': ('beruhte', 'beruht', '基于；依赖'),
'betonen': ('betonte', 'betont', '强调'),
'einwenden': ('wandte ein', 'eingewandt', '提出异议'),
'enttäuschen': ('enttäuschte', 'enttäuscht', '使失望'),
'feststellen': ('stellte fest', 'festgestellt', '确定；发现'),
'gelten': ('galt', 'gegolten', '有效；被认为'),
'genehmigen': ('genehmigte', 'genehmigt', '批准'),
'geraten': ('geriet', 'geraten', '陷入；碰巧'),
'hervorheben': ('hob hervor', 'hervorgehoben', '强调；突出'),
'leisten': ('leistete', 'geleistet', '完成；提供'),
'meiden': ('mied', 'gemieden', '避开'),
'neigen': ('neigte', 'geneigt', '倾向于'),
'reizen': ('reizte', 'gereizt', '刺激；吸引'),
'schätzen': ('schätzte', 'geschätzt', '估计；珍视'),
'streben': ('strebte', 'gestrebt', '追求；力求'),
'täuschen': ('täuschte', 'getäuscht', '欺骗；弄错'),
'umfassen': ('umfasste', 'umfasst', '包括；包含'),
'unterschätzen': ('unterschätzte', 'unterschätzt', '低估'),
'verarbeiten': ('verarbeitete', 'verarbeitet', '加工；处理'),
'verheimlichen': ('verheimlichte', 'verheimlicht', '隐瞒'),
'verursachen': ('verursachte', 'verursacht', '引起；造成'),
'voraussehen': ('sah voraus', 'vorausgesehen', '预见'),
'wahrnehmen': ('nahm wahr', 'wahrgenommen', '察觉；行使'),
'zunehmen': ('nahm zu', 'zugenommen', '增加；长胖'),
'zögern': ('zögerte', 'gezögert', '犹豫'),
}
