# B2 课程语法与词汇（按站内实际模块顺序，11 张卡片：3 语法 + 8 主题词汇）
# 数据源：站内课程目录+课件要点（已登录核验）；讲解与例句均为原创，不含视频内容
# 生成：python3 scripts/build_b2_grammar.py -> b2-kurs/grammar_b2.json
import json, os

GRAMMAR_POINTS = [
{'num': 'M17-01', 'id': 'zu_passiv', 'cat': 'yufa', 'title': '带 zu 不定式的被动含义', 'titleDe': 'Infinitiv mit zu (passivisch)',
 'explain': '带 zu 不定式可以表达被动含义：主语是动作的承受者，引导动词相当于情态动词 können/müssen/sollen，整个结构可改写为被动句。五类结构：① sein + zu（≈ können/müssen/sollen）：Die Anträge sind im Rathaus abzuholen.（申请表须在市政厅领取）；② bleiben + zu（≈ müssen）；③ gehen + zu（≈ können）；④ stehen + zu（≈ müssen，主语一般是 es，只与 befürchten/erwarten 搭配）：es steht zu erwarten；⑤ es gibt + zu（≈ müssen）。易错：sein + zu 具体对应 können/müssen/sollen 中的哪一个要靠语境判断；es steht zu erwarten 后可用带 zu 不定式代替 dass 从句；Vorfall（突发坏事）≠ Zufall（意外/巧合），不可互换。\n\n🇬🇧 英语对照：英语 is to be done / remains to be seen 也是类似结构（the work is to be finished = 这工作必须被完成）。',
 'table': [['结构', '相当于', '例子'],
           ['sein + zu', 'können/müssen/sollen', 'Die Anträge sind abzuholen.'],
           ['bleiben + zu', 'müssen', 'Es bleibt zu hoffen.'],
           ['gehen + zu', 'können', 'Das geht nicht zu ändern.'],
           ['stehen + zu', 'müssen', 'es steht zu erwarten'],
           ['es gibt + zu', 'müssen', 'Es gibt viel zu tun.']],
 'examples': [
     ('Die Anträge sind im Rathaus abzuholen.', '申请表要在市政厅领取。'),
     ('Es bleibt zu hoffen, dass alles gut geht.', '只能希望一切顺利。'),
     ('Das geht nicht zu ändern.', '这没法改变。'),
     ('Es steht zu erwarten, dass er kommt.', '预计他会来。'),
 ]},
{'num': 'M19-08', 'id': 'konjunktiv1', 'cat': 'yufa', 'title': '第一虚拟式', 'titleDe': 'Konjunktiv I',
 'explain': '第一虚拟式用于引述第三方的话，体现说话者中立、不表态的态度，只出现在新闻/广播/电视/报纸等正式书面语中。构成：在动词原形词干上加虚拟式词尾（sein、haben、fehlen、zerstören、情态动词等都有完整变位）。当一虚与直陈式现在时变位相同时，改用二虚代替（如 sie würden fehlen）。第二人称几乎不用、第一人称很少用，主语多为第三人称。一虚和二虚的过去时都是 haben/sein 虚拟式 + 过去分词。口语中避免用一虚，改用直陈式或二虚。易错：als sei（一虚）vs als wäre（二虚）——als sei 强调从对方话中可听出的客观事实而非主观理解；记忆口诀：一虚在原形词干上变化，二虚在过去式上变化，词尾一样。\n\n🇬🇧 英语对照：英语间接引语用时态后移（he said he was ill）；德语用第一虚拟式标明"这是转述"，更精确。',
 'table': [['用法', '例子'],
           ['转述（中立）', 'Er sagt, er sei krank.'],
           ['与直陈式相同时改用二虚', 'sie würden fehlen'],
           ['口语中避免', '口语用直陈式或二虚']],
 'examples': [
     ('Er sagt, er sei krank.', '他说他病了。'),
     ('Die Regierung erklärt, sie habe alles im Griff.', '政府称一切尽在掌握。'),
     ('Sie behauptet, sie wisse nichts davon.', '她声称对此一无所知。'),
     ('Es heißt, er komme morgen.', '据说明天他来。'),
 ]},
{'num': 'M20-01', 'id': 'dopp_akk', 'cat': 'yufa', 'title': '支配两个四格宾语的动词', 'titleDe': 'Verben mit zwei Akkusativobjekten',
 'explain': '德语里绝大多数双宾语动词是"三格人 + 四格物"，但有四个动词支配两个四格宾语：① kosten 和 lehren：两个宾语都用四格（Das kostet mich viel Zeit.）；口语中表"人"的四格有时被说成三格（Das kann ihm den Hals kosten），书面语应避免。② abfragen 和 abhören：表"人"的宾语可用三格也可用四格；若"人"是句中唯一宾语，必须用四格。③ fragen 和 bitten：表人的宾语用四格；bitten 很少接双宾语，更常见"人的四格 + um + 介词宾语"（Ich möchte dich darum bitten）或"人的四格 + 带 zu 不定式"。④ angehen：表人的四格 + nichts/etwas 等不定数量/程度的四格（Das geht dich nichts an. 不关你的事）。德国北部方言把表"人"的四格换成三格，但标准德语不接受。\n\n🇬🇧 英语对照：英语 give him the book 是双宾语；德语标准是"三格人+四格物"，这四个动词是"四格+四格"的例外，要单记。',
 'table': [['动词', '结构', '例子'],
           ['kosten/lehren', '四格 + 四格', 'Das kostet mich viel Zeit.'],
           ['abfragen/abhören', '人三/四格 + 物四格', 'Er fragt ihn die Vokabeln ab.'],
           ['fragen/bitten', '人四格', 'Ich frage dich etwas.'],
           ['angehen', '人四格 + nichts/etwas', 'Das geht dich nichts an.']],
 'examples': [
     ('Das kostet mich viel Zeit.', '这花了我很多时间。'),
     ('Er lehrt mich Deutsch.', '他教我德语。'),
     ('Ich möchte dich darum bitten.', '我想请你帮这个忙。'),
     ('Das geht dich nichts an.', '不关你的事。'),
 ]},
{'num': 'M17-08', 'id': 'personen', 'cat': 'vokabel', 'title': 'Personen und Lebensläufe（人物与简历）', 'titleDe': 'Personen und Lebensläufe',
 'explain': '主题词汇：人物与简历。① 个人信息：婚姻状况（ledig 未婚 / verheiratet 已婚 / geschieden 离异）、国籍；② 学校与培训：das Abitur（高中毕业考/高考）、sitzen bleiben（留级）；③ 职业选择与大学：论文、学位；④ 简历与工作经历：求职信、项目管理；⑤ 人际关系：恋爱、婚姻、离婚、单身趋势。Q&A：leiten/führen/anführen 都有"领导"之义，anführen 强调冲锋在前的带领；erarbeiten（团队协作中制定计划）vs ausarbeiten（详细拟定）。\n\n🇬🇧 英语对照：英语 CV / résumé；德语 der Lebenslauf，注意 Tabellarischer Lebenslauf（表格简历）是求职标配。',
 'table': [['词', '中文'],
           ['das Abitur', '高中毕业考/高考'],
           ['sitzen bleiben', '留级'],
           ['ledig', '单身（未婚）'],
           ['die Bewerbung', '申请/求职信'],
           ['anführen', '率领（冲锋在前）'],
           ['erarbeiten', '（协作）制定']],
 'examples': [
     ('Er hat das Abitur mit 1,0 bestanden.', '他以满分通过了高考。'),
     ('Sie ist ledig und wohnt allein.', '她单身独居。'),
     ('Er führt ein Team von zehn Leuten.', '他领导一个十人团队。'),
     ('Wir müssen einen Plan erarbeiten.', '我们得制定一个计划。'),
 ]},
{'num': 'M17-13', 'id': 'daheim', 'cat': 'vokabel', 'title': 'Daheim und unterwegs（家与旅途）', 'titleDe': 'Daheim und unterwegs',
 'explain': '主题词汇：家与旅途。① 乡村居住：房租（die Miete，复数 Mieten）、房东；② 德国城市：城市满意度、景点；③ 旅行：预订、酒店合同、der Preisaufschlag（涨价/加价）；④ 酒店住宿类型与设施：die Frühstückspension（供早餐的民宿）、der Wellnessbereich（康乐区）。Q&A：Wert auf Akk. legen（重视…）；beklagen 可作及物动词；einbehalten（扣留）注意主语；sich an Stränden sonnen（在沙滩上晒太阳）。\n\n🇬🇧 英语对照：英语 B&B；德语 Frühstückspension 就是"供早餐的民宿"，概念一致。',
 'table': [['词', '中文'],
           ['die Miete, -n', '房租'],
           ['der Preisaufschlag', '涨价/加价'],
           ['die Frühstückspension', '供早餐的民宿'],
           ['der Wellnessbereich', '康乐区'],
           ['Wert auf Akk. legen', '重视…']],
 'examples': [
     ('Die Miete ist dieses Jahr gestiegen.', '今年房租涨了。'),
     ('Wir legen großen Wert auf Pünktlichkeit.', '我们很重视守时。'),
     ('Das Hotel hat einen schönen Wellnessbereich.', '这家酒店康乐区不错。'),
     ('Sie sonnt sich gern am Strand.', '她喜欢在沙滩上晒太阳。'),
 ]},
{'num': 'M18-08', 'id': 'kulturen', 'cat': 'vokabel', 'title': 'Zwischen den Kulturen（文化之间）', 'titleDe': 'Zwischen den Kulturen',
 'explain': '主题词汇：文化之间。① 欧洲与德国人：统计数据表达（im Mittelfeld liegen 居中游、der Statistik zufolge 据统计）；② 海外冒险：求职、思乡、适应新环境；③ 文化差异：商务礼仪、谈判；④ 索布人：少数民族、语言文化保护。Q&A：unterhalb 与 unter 意思相同，但 unterhalb 是非常书面的说法。\n\n🇬🇧 英语对照：英语 according to statistics；德语 der Statistik zufolge（zufolge 后置支配三格）是书面语标志。',
 'table': [['词', '中文'],
           ['der Statistik zufolge', '据统计'],
           ['im Mittelfeld liegen', '处于中游'],
           ['das Heimweh', '思乡'],
           ['die Minderheit', '少数民族'],
           ['unterhalb（书面）', '在…之下']],
 'examples': [
     ('Der Statistik zufolge reisen die Deutschen gern.', '据统计德国人爱旅行。'),
     ('Deutschland liegt im Mittelfeld.', '德国居中游。'),
     ('Er hat großes Heimweh.', '他很想家。'),
     ('Die Sorben sind eine Minderheit.', '索布人是少数民族。'),
 ]},
{'num': 'M18-15', 'id': 'arbeit', 'cat': 'vokabel', 'title': 'Arbeit und Studium（工作与学习）', 'titleDe': 'Arbeit und Studium',
 'explain': '主题词汇：工作与学习。① 打电话：转接（weiterleiten）、留言；② 工作日常：会议、截止日期（die Frist）；③ 邮件：下班后邮件；④ 会议组织：der Zeitfresser（时间杀手，指低效会议）；⑤ 大学：das BAföG（助学金）、选专业；⑥ 商务信函；⑦ 称呼与问候：正式信函中 Sie/Ihnen 大写。\n\n🇬🇧 英语对照：英语 deadline；德语 die Frist，还常出现在法律/行政语境（Frist setzen 设定期限）。',
 'table': [['词', '中文'],
           ['der Zeitfresser', '时间杀手（低效会议）'],
           ['das BAföG', '助学金'],
           ['die Frist', '截止日期'],
           ['weiterleiten', '转接（电话）'],
           ['Sehr geehrte/r …', '尊敬的…']],
 'examples': [
     ('Kannst du mich weiterleiten?', '能帮我转接吗？'),
     ('Die Frist läuft morgen ab.', '截止日期是明天。'),
     ('Diese Besprechung war ein echter Zeitfresser.', '这会真是时间杀手。'),
     ('Er bekommt BAföG.', '他拿助学金。'),
 ]},
{'num': 'M19-07', 'id': 'zeit', 'cat': 'vokabel', 'title': 'Zeit und Tätigkeit（时间与活动）', 'titleDe': 'Zeit und Tätigkeit',
 'explain': '主题词汇：时间与活动。① 时间安排：通勤（der Stau 堵车）、等待、浪费时间（Zeit verschwenden）；② 阅读趋势：数字化媒体、休闲活动；③ 体育：赛事、世界纪录、规则；④ 特殊爱好：养蜂（das Bienenvolk 蜂群）、极限运动。\n\n🇬🇧 英语对照：英语 traffic jam；德语 der Stau，还可指"堆积"（Arbeitsstau 工作积压），一词多义。',
 'table': [['词', '中文'],
           ['der Stau', '堵车'],
           ['Zeit verschwenden', '浪费时间'],
           ['der Weltrekord', '世界纪录'],
           ['das Bienenvolk', '蜂群'],
           ['die Freizeitgestaltung', '休闲安排']],
 'examples': [
     ('Ich stehe jeden Morgen im Stau.', '我每天早上都堵车。'),
     ('Verschwende keine Zeit!', '别浪费时间！'),
     ('Er hat einen neuen Weltrekord aufgestellt.', '他创了新的世界纪录。'),
     ('Sein Hobby ist die Imkerei.', '他的爱好是养蜂。'),
 ]},
{'num': 'M19-41', 'id': 'spannung', 'cat': 'vokabel', 'title': 'Spannung und Entspannung（紧张与放松）', 'titleDe': 'Spannung und Entspannung',
 'explain': '主题词汇：紧张与放松。① 新闻媒体：客观性、时效性；② 电视犯罪剧：der Tatort（犯罪现场，德国长寿刑侦剧）、aufklären（破案/查明）、收视率；③ 政治：die DDR（东德）、抗议、die Politikverdrossenheit（政治冷漠）；④ 犯罪统计与腐败：破案率、贿赂。\n\n🇬🇧 英语对照：英语 Tatort 无对应词——它是德国特有的周日晚间刑侦剧品牌，1970 年开播至今，文化常识。',
 'table': [['词', '中文'],
           ['der Tatort', '犯罪现场（刑侦剧）'],
           ['aufklären', '查明/破案'],
           ['die Politikverdrossenheit', '政治冷漠'],
           ['die Bestechung', '贿赂'],
           ['die Einschaltquote', '收视率']],
 'examples': [
     ('Tatort läuft seit 1970.', '《犯罪现场》从1970年播到现在。'),
     ('Die Polizei hat den Fall aufgeklärt.', '警方破了案。'),
     ('Die Politikverdrossenheit wächst.', '政治冷漠在蔓延。'),
     ('Korruption und Bestechung sind ein Problem.', '腐败和贿赂是个问题。'),
 ]},
{'num': 'M20-62', 'id': 'technik', 'cat': 'vokabel', 'title': 'Technik und Trends（技术与趋势）', 'titleDe': 'Technik und Trends',
 'explain': '主题词汇：技术与趋势。① 日常电器：eingebaute Fehler（内置故障）、die Obsoleszenz（计划报废）；② 电脑安全：病毒、黑客、备份、防火墙；③ 新旧学习方法：büffeln（死记硬背）、在线课程；④ 发明与专利：申请专利、商标。\n\n🇬🇧 英语对照：英语 planned obsolescence；德语 geplante Obsoleszenz，媒体高频词。',
 'table': [['词', '中文'],
           ['die Obsoleszenz', '计划报废'],
           ['büffeln', '死记硬背'],
           ['die Datensicherung', '数据备份'],
           ['das Patent', '专利'],
           ['die Firewall', '防火墙']],
 'examples': [
     ('Mein Handy hat nur zwei Jahre gehalten – geplante Obsoleszenz.', '我手机只用了两年——计划报废。'),
     ('Er büffelt für die Prüfung.', '他在死记硬背备考。'),
     ('Mach regelmäßig eine Datensicherung!', '定期备份数据！'),
     ('Sie hat ein Patent angemeldet.', '她申请了专利。'),
 ]},
{'num': 'M20-70', 'id': 'gesundheit', 'cat': 'vokabel', 'title': 'Gesundheit und Umwelt（健康与环境）', 'titleDe': 'Gesundheit und Umwelt',
 'explain': '主题词汇：健康与环境。① 健康生活：文明病（die Zivilisationskrankheit）、风险因素、健康饮食；② 健康问题：看病、家庭疗法、医保（die Krankenkasse）；③ 饮食与环境：气候变化、过度捕捞；④ 环境问题与治理：die Innenstadtmaut（市中心通行费）、绿色能源；⑤ 健康睡眠：午睡、睡眠障碍。Q&A：die Erhebung（征收）+ Innenstadtmaut：die Pkw-Dichte durch die Erhebung einer Innenstadtmaut verringern（通过征收市中心通行费降低汽车密度）。\n\n🇬🇧 英语对照：英语 health insurance；德语 Krankenkasse 字面"疾病金库"，德国医保体系核心词。',
 'table': [['词', '中文'],
           ['die Krankenkasse', '医保/健康保险公司'],
           ['die Zivilisationskrankheit', '文明病'],
           ['die Innenstadtmaut', '市中心通行费'],
           ['die Erhebung', '征收'],
           ['die Überfischung', '过度捕捞']],
 'examples': [
     ('Er ist bei einer gesetzlichen Krankenkasse versichert.', '他在法定医保参保。'),
     ('Stress ist eine typische Zivilisationskrankheit.', '压力是典型的文明病。'),
     ('Die Stadt plant eine Innenstadtmaut.', '该市计划收市中心通行费。'),
     ('Überfischung gefährdet die Meere.', '过度捕捞威胁海洋。'),
 ]},
]

def main():
    for p in GRAMMAR_POINTS:
        assert len(p['examples']) == 4, p['id']
    out = os.path.join(os.path.dirname(__file__), '..', 'b2-kurs', 'grammar_b2.json')
    with open(out, 'w', encoding='utf-8') as f:
        json.dump(GRAMMAR_POINTS, f, ensure_ascii=False, indent=1)
    print(f"wrote {len(GRAMMAR_POINTS)} cards -> {out}")

if __name__ == '__main__':
    main()
