# B1 课程语法与词汇（按站内实际模块顺序，18 张卡片）
# 数据源：站内课程目录+课件要点（已登录核验）；讲解与例句均为原创，不含视频内容
# 生成：python3 scripts/build_b1_grammar.py -> kurs/b1/grammar_b1.json
import json, os

GRAMMAR_POINTS = [
{'num': 'M13-01', 'id': 'all_alle', 'cat': 'pron', 'title': 'all / alle / alles', 'titleDe': 'all-, alle, alles',
 'explain': '作定语时 all- 按 dies- 变格、后接形容词弱变化；在定冠词/其他限定词前可不加词尾。加词尾与不加词尾含义无区别（老师强调不要徒劳区分），但 solch- 前必须用加词尾的 all-。与人称代词连用主格分开写（wir alle），代词本身要变格（bei uns allen）。只有 alles 能和物质名词/动词搭配。易错：Sind das alle?（可数，这些是全部吗）vs Ist das alles?（不可数，就这些吗）不能混用。\n\n🇬🇧 英语对照：英语 all / everything；德语 alle（可数复数）vs alles（不可数/事情）的区分是重点。',
 'table': [['用法', '例子'],
           ['作定语', 'alle meine Freunde'],
           ['与代词连用', 'wir alle / bei uns allen'],
           ['alles', 'Alles ist gut.']],
 'examples': [
     ('Alle meine Freunde kommen.', '我所有的朋友都来。'),
     ('Wir alle sind müde.', '我们都很累。'),
     ('Ist das alles?', '就这些吗？'),
     ('Bei uns allen war es kalt.', '我们那儿都很冷。'),
 ]},
{'num': 'M13-02', 'id': 'beide', 'cat': 'pron', 'title': 'beide / beides', 'titleDe': 'beide, beides',
 'explain': '作代词时 beide 指两个人或两个事物，不可数事物用 beides。作限定词时像复数定冠词变格（die beiden）；省去名词时代词变格相同。与人称代词连用主格分开写（wir beide）、非主格按形容词词尾（uns beiden），第二人称例外（euch beide）。"两个都"不能说 nicht beide，应用 sowohl…als auch / entweder…oder / weder…noch。\n\n🇬🇧 英语对照：英语 both；德语 beide 作限定词还要变格（die beiden），是英语没有的。',
 'table': [['用法', '例子'],
           ['作代词', 'Beide sind gekommen.'],
           ['作限定词', 'die beiden Kinder'],
           ['与代词连用', 'wir beide / uns beiden'],
           ['两个都', 'sowohl…als auch']],
 'examples': [
     ('Beide sind gekommen.', '两个都来了。'),
     ('Die beiden Kinder spielen.', '那两个孩子在玩。'),
     ('Wir beide gehen ins Kino.', '我们俩去看电影。'),
     ('Sowohl er als auch sie kommen.', '他和她都来。'),
 ]},
{'num': 'M13-03', 'id': 'jemand', 'cat': 'pron', 'title': 'jemand / niemand', 'titleDe': 'jemand, niemand',
 'explain': '变格：三格 jemandem、四格 jemanden（口语可用原形），二格 -es 只用于书面语，否则用 von + 第三格。后续代词用阳性单数（es ist seine Pflicht）。口语中 einer/wer 代替 jemand、keiner 代替 niemand。后跟形容词时三、四格不变格，形容词名词化加词尾（jemand Kluges）。与 anders 连用时 jemand/niemand 不变格、anders 小写且永不变格。\n\n🇬🇧 英语对照：英语 someone/anyone；德语 jemand 要变格，且后续形容词名词化是特色。',
 'table': [['格', 'jemand', 'niemand'],
           ['一格', 'jemand', 'niemand'],
           ['三格', 'jemandem', 'niemandem'],
           ['四格', 'jemanden', 'niemanden']],
 'examples': [
     ('Hat jemand angerufen?', '有人打电话吗？'),
     ('Ich habe niemanden gesehen.', '我谁也没见着。'),
     ('Jemand Kluges hat das gesagt.', '某个聪明人说的。'),
     ('Niemand ist perfekt.', '没有人是完美的。'),
 ]},
{'num': 'M13-04', 'id': 'irgend', 'cat': 'pron', 'title': 'irgend- 前缀', 'titleDe': 'irgend-',
 'explain': '共 11 个词：irgendetwas/was、irgendwann、irgendwie、irgendeine-、irgendwelche-、irgendjemand、irgendwer、irgendwo/wohin/woher、irgend so ein-。irgendeine- 作限定词按不定冠词变格（无复数），作代词按定冠词词尾变格。irgendwelche- 用于不可数/抽象/复数名词，按 welche- 变格。口语中 irgendetwas 常简化为 irgendwas。\n\n🇬🇧 英语对照：英语 some-/any-；德语 irgend- = "某个不确定的"，比 some- 更强调不确定。',
 'table': [['词', '含义', '例子'],
           ['irgendjemand', '某人', 'Irgendjemand ruft an.'],
           ['irgendwann', '某个时候', 'Komm irgendwann vorbei!'],
           ['irgendwo', '某处', 'Er ist irgendwo.'],
           ['irgendwelche-', '一些（复数）', 'irgendwelche Fragen']],
 'examples': [
     ('Irgendjemand hat angerufen.', '有人打过电话。'),
     ('Komm irgendwann vorbei!', '改天过来！'),
     ('Hast du irgendwelche Fragen?', '有什么问题吗？'),
     ('Irgendwas stimmt nicht.', '有点不对劲。'),
 ]},
{'num': 'M13-05', 'id': 'ander', 'cat': 'pron', 'title': 'ander / anders / verschieden', 'titleDe': 'ander-, anders, verschieden',
 'explain': 'anders = 与"上文提到的"作横向对比；作定语时去 s 再加形容词词尾（andere Biere = 和第一家酒吧不同的啤酒）。verschieden/unterschiedlich = 同一范围内部的多样性（"好几种不同的啤酒"），二者基本是同义词。带 s 的 anders 只能作表语。anders 还有"其他的"之义。易错：老师明确指出 Deutschland ist anders 不能换成 unterschiedlich（会变成"不同时期的德国"的纵向对比），且 unterschiedlich 画面感更"混乱"。\n\n🇬🇧 英语对照：英语 different/other；德语 anders（横向对比）vs verschieden（内部多样）的区分是精髓。',
 'table': [['词', '含义', '例子'],
           ['anders（表语）', '不一样（横向对比）', 'Deutschland ist anders.'],
           ['andere-（定语）', '不同的', 'andere Biere'],
           ['verschieden', '多种多样的', 'verschiedene Probleme']],
 'examples': [
     ('Ich möchte ein anderes Bier.', '我想换种啤酒。'),
     ('Wir haben verschiedene Probleme.', '我们有各种不同的问题。'),
     ('Das ist etwas anderes.', '那是另一回事。'),
     ('Sie ist anders als ihre Schwester.', '她和她姐姐不一样。'),
 ]},
{'num': 'M14-01', 'id': 'dativ_e', 'cat': 'ge', 'title': '三格词尾 -e（旧式）', 'titleDe': 'Dativ-e',
 'explain': '20 世纪中叶前的旧德语中，阳性/中性名词第三格单数加 -e（Hause, Tage, Jahre, Laufe, Falle, Maße, Grade, Sinne）。现代德语中 -e 为可选项，仅保留在固定表达中：zu Hause（在家）、nach Hause（回家）、im Falle（万一）、im Laufe（在…过程中）、im Grunde（基本上）、in diesem Sinne（在此意义上）。注意 im Grunde 表示"基本"而非"到底"。im Falle von Katastrophen 用 von + 第三格代替第二格。\n\n🇬🇧 英语对照：类似英语古语 thou/thee 的残留；现代德语只在固定搭配里见到，认出来就行。',
 'table': [['固定表达', '含义'],
           ['zu Hause', '在家'],
           ['nach Hause', '回家'],
           ['im Falle', '万一'],
           ['im Laufe', '在…过程中'],
           ['im Grunde', '基本上']],
 'examples': [
     ('Ich bin zu Hause.', '我在家。'),
     ('Im Falle eines Falles ruf an.', '万一有事打电话。'),
     ('Im Laufe der Zeit ändert sich alles.', '随着时间一切都会变。'),
     ('Er geht nach Hause.', '他回家了。'),
 ]},
{'num': 'M14-02', 'id': 'genitiv_praep', 'cat': 'ge', 'title': '支配第二格的介词', 'titleDe': 'Präpositionen mit Genitiv',
 'explain': '四个最常用：statt/anstatt（可作连词，支配与比较对象相同的格）、trotz、während（"期间/始终"，也可作连词表同时或对比）、wegen（固定结构 von…wegen）。八个空间介词：außerhalb、innerhalb、oberhalb、unterhalb、beidseits、diesseits、jenseits、unweit。其他：anlässlich、anhand、infolge、inklusive、mittels、zwecks。易错：wegen Fahrens 中名词化动词即使无冠词第二格也要加 -s；anfangs dieses Jahres 是第二格（Jahres），不是第三格强变化。\n\n🇬🇧 英语对照：英语 during/instead of/despite；德语这些介词支配二格，是书面语的标志。',
 'table': [['介词', '含义', '例子'],
           ['statt/anstatt', '代替', 'statt des Autos'],
           ['trotz', '尽管', 'trotz des Regens'],
           ['während', '在…期间', 'während des Essens'],
           ['wegen', '因为', 'wegen des Staus'],
           ['innerhalb', '在…之内', 'innerhalb der Stadt']],
 'examples': [
     ('Trotz des Regens gehen wir raus.', '尽管下雨我们还是出去。'),
     ('Während des Essens spricht man nicht.', '吃饭时不说话。'),
     ('Wegen des Staus komme ich zu spät.', '因为堵车我迟到了。'),
     ('Statt des Autos nehme ich das Fahrrad.', '我不坐汽车，骑车去。'),
 ]},
{'num': 'M14-03', 'id': 'modal_perfekt', 'cat': 'dongci', 'title': '情态动词的现在完成时', 'titleDe': 'Perfekt der Modalverben',
 'explain': '特殊结构：haben + 动词原形 + 情态动词原形（Er hat nicht kommen dürfen.），不能用过去分词——这是德语著名的"双原形"（Ersatzinfinitiv）。情态动词自身的过去分词形式（gedurft、gekonnt 等）仅在情态动词单独作谓语时使用（Das hat er nicht gedurft.）。易错：带宾语动词时误用过去分词。\n\n🇬🇧 英语对照：英语 had to come；德语用"双原形"代替过去分词，是德语特有的怪规则。',
 'table': [['结构', '例子'],
           ['haben + 原形 + 情态原形', 'Er hat nicht kommen dürfen.'],
           ['情态单独作谓语', 'Das hat er nicht gedurft.']],
 'examples': [
     ('Er hat nicht kommen dürfen.', '他不被允许来。'),
     ('Sie hat das nicht gewollt.', '她不想要那个。'),
     ('Ich habe ihn nicht verstehen können.', '我没能理解他。'),
     ('Das hat er nicht gedurft.', '他不被允许做那个。'),
 ]},
{'num': 'M14-04', 'id': 'lassen', 'cat': 'dongci', 'title': 'lassen 的用法总结', 'titleDe': 'lassen',
 'explain': 'lassen 有 6 种用法：①基本义"什么都不做/算了"（machen 的反义词）；②"允许"（Der Lehrer lässt die Kinder nicht spielen.）；③"命令"（Der Lehrer lässt die Kinder in der Klasse bleiben.）；④"建议/邀请"（Lass uns…）；⑤使役"让别人做"（Ich habe mir die Haare schneiden lassen.）；⑥lassen + sich + 副词/动词原形 = 被动意义，主语一般是物（Die Tür lässt sich nicht öffnen.）。完成时中 lassen 用原形代替过去分词（类似情态动词）。\n\n🇬🇧 英语对照：英语 let/have/make/get；德语一个 lassen 覆盖了 let、allow、order、have sth done、can be done 多个意思。',
 'table': [['用法', '例子'],
           ['允许', 'Der Lehrer lässt die Kinder spielen.'],
           ['命令', 'Er lässt die Kinder bleiben.'],
           ['建议', 'Lass uns gehen!'],
           ['使役', 'sich die Haare schneiden lassen'],
           ['被动意义', 'Die Tür lässt sich nicht öffnen.']],
 'examples': [
     ('Lass uns gehen!', '我们走吧！'),
     ('Der Lehrer lässt die Kinder spielen.', '老师让孩子们玩。'),
     ('Die Tür lässt sich nicht öffnen.', '这门打不开。'),
     ('Ich habe mir die Haare schneiden lassen.', '我去理了发。'),
 ]},
{'num': 'M14-05', 'id': 'partizip_adj', 'cat': 'xingrong', 'title': '分词作形容词', 'titleDe': 'Partizip als Adjektiv',
 'explain': '分词作形容词加正常形容词词尾，也可作副词，还可被名词化（Angestellte 雇员、Bekannte 熟人）。第一分词表主动/进行（boiling water 开水）。第二分词：不及物动词表完成/主动（angekommen = 已经到达），及物动词表被动（verloren 丢失的、gewarnt 被警告的）。第一分词 + zu 表被动的必要性（nicht zu übersehender Fehler = 不能忽视的错误）。易错：Den Schildern folgend（状语，跟着路标走）vs Den folgenden Schildern（定语，接下来的路标）含义不同。\n\n🇬🇧 英语对照：英语 a crying baby / a broken window；德语规则相同，但分词要按形容词变格。',
 'table': [['分词', '含义', '例子'],
           ['第一分词', '主动/进行', 'die weinende Frau'],
           ['第二分词（不及物）', '完成/主动', 'der angekommene Zug'],
           ['第二分词（及物）', '被动', 'der verlorene Schlüssel'],
           ['第一分词+zu', '被动必要', 'nicht zu übersehender Fehler']],
 'examples': [
     ('Die weinende Frau braucht Hilfe.', '哭泣的女人需要帮助。'),
     ('Der verlorene Schlüssel ist wieder da.', '丢失的钥匙又找到了。'),
     ('Die Angestellten streiken.', '雇员们在罢工。'),
     ('Das ist ein nicht zu übersehender Fehler.', '这是个不能忽视的错误。'),
 ]},
{'num': 'M14-06', 'id': 'infinitiv_verben', 'cat': 'dongci', 'title': '搭配动词原形的动词', 'titleDe': 'Verben mit Infinitiv',
 'explain': '感官动词 sehen/hören/fühlen/spüren + 第四格 + 动词原形（acI 结构），完成时仍用原形代替过去分词（Ich habe ihn kommen sehen.）。gehen/kommen/fahren/schicken + 动词原形。bleiben/finden/haben + 方位动词（sitzen bleiben 留级等固定搭配）。heißen（命令）/helfen/lehren/lernen + 动词原形或带 zu 不定式；heißen（意味着）/nennen 只能 + 动词原形。tun + 动词原形在口语中表强调，书面语避免。固定搭配 sich schlafen legen。\n\n🇬🇧 英语对照：英语 see sb do / help sb (to) do；德语感官动词后也是"四格+原形"，完成时同样用双原形。',
 'table': [['动词', '结构', '例子'],
           ['sehen/hören', '四格+原形', 'Ich habe ihn kommen sehen.'],
           ['bleiben', '方位动词', 'sitzen bleiben'],
           ['helfen/lernen', '原形或zu不定式', 'Er hilft mir tragen.'],
           ['heißen（意味着）', '只能原形', 'Das heißt arbeiten.']],
 'examples': [
     ('Ich habe ihn kommen sehen.', '我看见他来了。'),
     ('Sie bleibt sitzen.', '她留级了。'),
     ('Er hilft mir tragen.', '他帮我搬。'),
     ('Lass ihn gehen!', '让他走！'),
 ]},
{'num': 'M15-01', 'id': 'plusquamperfekt', 'cat': 'tempus', 'title': '过去完成时', 'titleDe': 'Plusquamperfekt',
 'explain': '构成：haben/sein 的过去时 + 过去分词（hatte gemacht）。用法："过去的过去"——先发生的动作用过去完成时，常与 bevor/nachdem 配合。老师特别强调的易错点：不要因为"事情发生在过去"就把 haben/sein 改成过去时——现在完成时和一般过去时含义基本等价，*"2001 hatte ich mein Studium abgeschlossen" 是错误的（2001 年毕业直接用完成时/过去时即可）。\n\n🇬🇧 英语对照：英语 had done；德语 had done = hatte gemacht，结构一一对应，但别滥用。',
 'table': [['时态', '构成', '例子'],
           ['过去完成时', 'hatte/war + 过去分词', 'hatte gemacht'],
           ['现在完成时', 'habe + 过去分词', 'habe gemacht'],
           ['过去时', '动词过去式', 'machte']],
 'examples': [
     ('Nachdem er gegessen hatte, ging er.', '他吃完饭后走了。'),
     ('Sie war schon gegangen, als ich kam.', '我到时她已经走了。'),
     ('Als wir ankamen, war der Film schon zu Ende.', '我们到时电影已经结束了。'),
     ('Er hatte viel gelernt und bestand die Prüfung.', '他学了很多，通过了考试。'),
 ]},
{'num': 'M15-02', 'id': 'gleich_derselbe', 'cat': 'pron', 'title': 'gleich vs derselbe', 'titleDe': 'gleich, derselbe',
 'explain': 'gleich = 两个一样的对象（相似，同款）；derselbe = 同一个对象（同一）。derselbe 变格时 der 和 selbe 都要变格；介词后冠词与介词缩合（am/beim/zur selben）。易错：连德国人都常混淆——想表达"同一间办公室"应说 Wir arbeiten im selben Büro 而非 im gleichen Büro。\n\n🇬🇧 英语对照：英语 the same（模糊）vs 德语 gleich（相似）/derselbe（同一）的精确区分，是德语更细的地方。',
 'table': [['词', '含义', '例子'],
           ['gleich', '相似的（两个对象）', 'das gleiche Auto'],
           ['derselbe', '同一个（同一对象）', 'im selben Büro'],
           ['介词缩合', 'zur selben Zeit', '在同一时间']],
 'examples': [
     ('Wir haben das gleiche Auto.', '我们有同款车。'),
     ('Wir arbeiten im selben Büro.', '我们在同一间办公室。'),
     ('Zur selben Zeit war er da.', '同一时间他在那儿。'),
     ('Das ist nicht dasselbe!', '那不是同一回事！'),
 ]},
{'num': 'M15-03', 'id': 'hin_her', 'cat': 'qita', 'title': '表示方向的副词 hin-/her-', 'titleDe': 'hin-, her-',
 'explain': 'her- = 朝向说话人（herauf 上来、herunter 下来、herein 进来、herüber 过来），hin- = 远离说话人（hinauf 上去、hinunter 下去、hinein 进去、hinüber 过去）。口语缩写：rauf、runter、rein、rüber。hinterher 是固定搭配（Otto geht dir hinterher 他跟在你后面）。易错：gehen 是不及物动词，不能支配第四格直接宾语，所以 hinterher 后用第三格（dir 而非 dich）。\n\n🇬🇧 英语对照：英语 come in（朝我）/ go in（离我）；德语把方向编进了前缀 her-/hin-，更系统。',
 'table': [['前缀', '方向', '例子'],
           ['her-', '朝向说话人', 'herein 进来'],
           ['hin-', '远离说话人', 'hinaus 出去'],
           ['口语缩写', '—', 'rein/rüber/runter']],
 'examples': [
     ('Komm herein!', '进来！'),
     ('Geh hinaus!', '出去！'),
     ('Er läuft dir hinterher.', '他跟在你后面跑。'),
     ('Kommst du mit runter?', '你跟我一起下去吗？'),
 ]},
{'num': 'M16-17', 'id': 'abkuerzungen', 'cat': 'vokabel', 'title': '德语常用缩写总结', 'titleDe': 'Abkürzungen',
 'explain': '19 个常用缩写：Abo（订阅）、Akku（电池）、Azubi（学徒）、bzw（beziehungsweise 即/或者）、ca（circa 大约）、d. h.（das heißt 即）、EG（Erdgeschoss 底楼）/OG（楼上）/UG（地下）、Kfz（机动车）、Lkw（卡车）、Pkw（小汽车）、usw（und so weiter 等等）、vgl（vergleiche 比较）、WC、WG（Wohngemeinschaft 合租）、SMS、z. B.（zum Beispiel 例如）。CH = Confoederatio Helvetica（瑞士联邦，拉丁语）。易错：usw 与 und 列举连用不重复（Äpfel, Birnen usw.）。\n\n🇬🇧 英语对照：英语 e.g./i.e./etc.；德语 z. B./d. h./usw 一一对应。',
 'table': [['缩写', '全称', '中文'],
           ['z. B.', 'zum Beispiel', '例如'],
           ['d. h.', 'das heißt', '即'],
           ['usw.', 'und so weiter', '等等'],
           ['bzw.', 'beziehungsweise', '即/或者'],
           ['ca.', 'circa', '大约'],
           ['WG', 'Wohngemeinschaft', '合租'],
           ['EG/OG/UG', 'Erdgeschoss…', '底楼/楼上/地下'],
           ['vgl.', 'vergleiche', '比较']],
 'examples': [
     ('Zum Beispiel: Äpfel, Birnen usw.', '例如：苹果、梨等等。'),
     ('Das heißt, du kommst nicht?', '也就是说你不来了？'),
     ('Er wohnt in einer WG.', '他住在合租房里。'),
     ('Vgl. Seite 10.', '参见第 10 页。'),
 ]},{'num': 'M16-18', 'id': 'b1_verben', 'cat': 'vokabel', 'title': 'B1 动词词汇补充', 'titleDe': 'Verben (B1)',
 'explain': 'B1 级别实用动词约 80 个。特点：①可分动词多（abmachen、ausmachen、zumachen、anmachen…），注意框型结构把前缀放句末；②部分动词有固定搭配（sich nähern + 第三格；Respekt entgegenbringen）；③瑞士用法 parkieren（= parken 停车）；④网络时代新词都是规则弱变化（googeln、bloggen、chatten、mailen、twittern、jobben）；⑤易混：anmachen / ausmachen 是开/关电器，aufmachen / zumachen 是开/关门窗；blitzen（打闪）比 glänzen（发光）更刺眼突然。\n\n🇬🇧 英语对照：英语也有大量短语动词（take off / put on）；德语可分动词的前缀同样放句末，逻辑一致。',
 'table': [['德语', '中文'], ['ablehnen', '拒绝'], ['abmachen', '商定、约定'], ['abonnieren', '订阅'], ['anlassen', '让……开着（如收音机）'], ['annähen', '缝上'], ['sich anschnallen', '系安全带'], ['aufheben', '捡起、妥善保管'], ['auflösen', '溶解'], ['ausmachen', '让……关掉；不介意'], ['ausmessen', '测量'], ['(Fieber) messen', '量（体温）'], ['berechnen', '计算、收取（费用）'], ['bestrafen', '处罚'], ['blitzen', '打闪、闪光'], ['donnern', '打雷、轰隆隆地响'], ['atmen', '呼吸'], ['einatmen', '吸气'], ['ausatmen', '呼气'], ['festnehmen', '逮捕'], ['entgegenbringen', '给予、表示'], ['enttäuschen', '使失望'], ['erschrecken', '（受到）震惊/吓'], ['faulenzen', '闲逛、偷懒'], ['fortsetzen', '继续'], ['beschließen', '决定'], ['freihalten', '保持畅通、请客买单'], ['füttern', '喂食'], ['grillieren', '烧烤'], ['hageln', '下冰雹'], ['anrichten', '造成（损害）'], ['hinfallen', '跌倒'], ['weh tun', '疼痛'], ['sich integrieren', '融入'], ['helfen', '有助于'], ['kaputtmachen', '弄坏'], ['kleben', '粘贴'], ['klicken', '点击'], ['anklicken', '点击'], ['markieren', '标记'], ['korrigieren', '纠正'], ['klopfen', '敲'], ['missverstehen', '误解'], ['nachschlagen', '查阅'], ['nachsehen', '查看'], ['nachsenden', '转寄'], ['sich nähern (+Dat)', '接近'], ['parkieren', '停车（瑞士用法）'], ['pflanzen', '种植'], ['sich rasieren', '刮胡子'], ['reinigen', '清洁'], ['Schwarzfahren', '逃票'], ['transportieren', '运输'], ['überholen', '超车'], ['überreden', '说服'], ['umarmen', '拥抱'], ['sich ummelden', '搬家后重新登记'], ['unterlassen', '停止、禁止'], ['unterstreichen', '画线强调'], ['versäumen', '错过'], ['impfen', '接种疫苗'], ['anbieten', '提供'], ['verurteilen', '判刑、处以（罚款）'], ['vorkommen', '发生'], ['winken', '挥手'], ['zelten', '露营'], ['(mit)nehmen', '带上'], ['zumachen', '关上'], ['ausmachen', '关（电器）'], ['anmachen', '打开（电器/开关）'], ['basteln', '手工制作'], ['(voll)tanken', '加（满）油'], ['bloggen', '写博客'], ['googeln', '用谷歌搜索'], ['jobben', '打工'], ['mailen', '发邮件'], ['twittern', '发推文'], ['chatten', '网上聊天'], ['ausrichten', '转达'], ['kopieren', '复印']],
 'examples': [('Kannst du bitte das Fenster aufmachen?', '你能把窗户打开吗？'), ('Ich habe das Wort im Wörterbuch nachgeschlagen.', '我在词典里查了这个词。'), ('Er hat sich schnell integriert.', '他很快融入了。'), ('Wir müssen vor der Fahrt noch tanken.', '出发前我们还得加油。')]},
{'num': 'M16-19', 'id': 'b1_nomen', 'cat': 'vokabel', 'title': 'B1 名词词汇补充', 'titleDe': 'Nomen (B1)',
 'explain': 'B1 级别高频名词 265 个，冠词和复数要连词一起背。特点：①大量收录瑞士/奥地利说法（Billett、Perron、Trottoir、Poulet、Rüebli、Marille、Paradeiser、Semmel、Jause、Erdapfel、Faschiertes、Knödel、Hendl、Gehsteig、Stiegenhaus、Abwart、Coiffeur、Bankomat、Führerausweis、Zivilstand、Fasnacht 等），歌德 B1 听力常考，注意识别；②易混：der Schreck（一瞬间的惊吓）vs der Schrecken（持续的恐慌）；die Ansage（泛指宣布）vs die Durchsage（特指广播播报）。\n\n🇬🇧 英语对照：英语名词没有性数配合；德语每个名词必须连 der/die/das 一起背，复数形式单独记。',
 'table': [['名词', '中文'], ['der Abfalleimer, -', '垃圾桶'], ['der Abflug, ¨e', '起飞'], ['der Absender, -', '发件人'], ['der Abwart, -e（瑞）', '看门人'], ['der Weg, -e', '路'], ['das Tal, ¨er', '山谷'], ['die Alkoholsucht', '酒瘾'], ['die Ansage, -n', '公告、广播通知'], ['der Antwortbogen, ¨', '答题纸/答题卡'], ['die Aprikose, -n', '杏子'], ['die Apfelsine, -n', '橙子'], ['die Erdbeere, -n', '草莓'], ['das Arbeitsverhältnis, -se', '雇佣关系'], ['der Aufenthaltsraum, ¨e', '休息室'], ['die Ausfahrt, -en', '（高速）出口'], ['die Aushilfe, -n', '帮工'], ['der Ausländer, - / die Ausländerin, -nen', '外国人'], ['die Aussprache, -n', '发音'], ['der Babysitter, -', '保姆'], ['die Backform, -en', '烤盘'], ['die Badewanne, -n', '浴缸'], ['der Bankomat, -en（奥）', '自动取款机'], ['das Bankkonto, -konten', '银行账户'], ['die Bedienungsanleitung, -en', '操作说明'], ['die Betreuerin, -nen', '照看人（女）'], ['der Betriebsrat, ¨e', '职工委员会'], ['das Billett, -e（瑞）', '票'], ['die Brieftasche, -n', '钱包'], ['das Kleingeld', '零钱'], ['die Briefträgerin, -nen', '女邮递员'], ['der Briefumschlag, ¨e', '信封'], ['die Briefmarke, -n', '邮票'], ['das Brötli, -（瑞）', '面包卷'], ['die Buchhandlung, -en', '书店'], ['die Bürste, -n', '刷子/梳子'], ['der Busfahrer, -', '公交司机'], ['der Beruf, -e', '职业'], ['die Castingshow, -s', '选秀节目'], ['die Veranstaltung, -en', '活动'], ['die Fernsehsendung, -en', '电视节目'], ['der Sänger, -', '歌手'], ['der Tänzer, -', '舞者'], ['das Model, -s', '模特'], ['der Akrobat, -en', '杂技演员'], ['der Chat, -s', '网络聊天'], ['der Coiffeur, -e（瑞）', '理发师'], ['das Kuvert, -s（瑞）', '信封'], ['der Dialekt, -e', '方言'], ['die Disko, -s / die Diskothek, -en', '迪斯科舞厅'], ['das Doppelbett, -en', '双人床'], ['das Einzelbett, -en', '单人床'], ['das Waschmittel, -', '清洁剂'], ['die Drogerie, -n', '药妆店'], ['die ec-Karte, -n', '银行卡'], ['die Einbahnstraße, -n', '单向街'], ['der Einbrecher, -', '入室盗窃犯'], ['der Einfall, ¨e', '想法、灵感'], ['die Einzahlung, -en', '存款、押金'], ['die Einzelheit, -en', '细节'], ['das Elektrogeschäft, -e', '电子产品商店'], ['das Handy, -s', '手机'], ['der Elektroherd, -e', '电炉'], ['die Küche, -n', '厨房'], ['die Nahrung, -en', '食物'], ['der Elektroingenieur, -e', '电气工程师'], ['das Endspiel, -e', '决赛'], ['die Enttäuschung, -en', '失望'], ['die Entfernung, -en', '距离'], ['der Entschluss, ¨e', '决定'], ['der Erdapfel, ¨（奥）', '土豆'], ['die Erkältung, -en', '感冒'], ['die Nase, -n', '鼻子'], ['die Ermäßigung, -en', '折扣'], ['die Erziehung, -en', '教育、抚养'], ['die Computerfachfrau, -en', '计算机专家（女）'], ['der Fahrplan, ¨e', '时刻表'], ['der Familienstand, ¨e', '婚姻状况'], ['die Fantasie, -n', '想象力'], ['das Faschierte（奥）', '肉末'], ['der Fasching', '狂欢节（巴伐利亚/奥/萨克森）'], ['die Fasnacht, -en（瑞）', '狂欢节'], ['das Kostüm, -e', '服装'], ['der Fauteuil, -s', '扶手椅'], ['die Firma, -en', '公司'], ['das Feuerzeug, -e', '打火机'], ['der Fleck, -e', '污渍'], ['die Bluse, -n', '女衬衫'], ['der Fleischhauer, -（奥）', '屠夫'], ['die Wurst, ¨e', '香肠'], ['die Folie, -n', '幻灯片'], ['die Fortbildung, -en', '进修'], ['das Forum, Foren', '论坛'], ['der Franken, -', '法郎'], ['der Rappen, -', '生丁'], ['der Führerausweis, -e（瑞）', '驾驶执照'], ['das Gasthaus, ¨er', '餐馆'], ['das Bier, -e', '啤酒'], ['die Geburtstagsfeier, -n', '生日聚会'], ['das Geschirr', '餐具'], ['die Geburtstagsparty, -s', '生日派对'], ['der Gehsteig, -e（奥）', '人行道'], ['die Geldbörse, -n', '钱包'], ['der Gerichtssaal, -säle', '法庭'], ['der Prozess, -e', '诉讼'], ['die Geschwindigkeitsbeschränkung, -en', '限速'], ['der Getränkeautomat, -en', '饮料自动售货机'], ['das Getreide', '谷物'], ['die Gratulation, -en', '祝贺'], ['das Grundstück, -e', '地块'], ['das Hackfleisch', '肉末'], ['das Hühnchen, -', '鸡肉'], ['das Hallenbad, ¨er', '室内游泳池'], ['die Hauptrolle, -n', '主角'], ['das Stück, -e', '剧'], ['die Hausordnung, -en', '房屋守则'], ['der Mieter, -', '租户'], ['das Hendl, -（奥）', '鸡肉'], ['das Hilfsmittel, -', '辅助工具'], ['das Mobiltelefon, -e', '手机'], ['das Wörterbuch, ¨er', '字典'], ['der Teppich, -e', '地毯'], ['der Holzfußboden, ¨', '木地板'], ['der Imbiss, -e', '小吃'], ['die Infektion, -en', '感染'], ['die Tablette, -n', '药片'], ['das Inserat, -e', '报纸广告'], ['die Jause, -n（奥）', '点心'], ['das Kabel, -', '电缆'], ['der Fernsehkanal, ¨e', '电视频道'], ['die Tasse, -n', '杯子'], ['das Kännchen, -', '咖啡小壶'], ['die Musikkassette, -n', '音乐磁带'], ['das Ketchup', '番茄酱'], ['das Brot, -e', '面包'], ['der Kiosk, -e', '售货亭'], ['die Ecke, -n', '拐角'], ['die Kindertagesstätte, -n', '托儿所'], ['die Kita, -s', '托儿所（简称）'], ['die Klimaanlage, -n', '空调'], ['der Knödel, -（奥）', '丸子'], ['der Knopfdruck, ¨e', '按键'], ['der Kompromiss, -e', '妥协'], ['die Konfitüre, -n', '果酱'], ['das Glas, ¨er', '玻璃罐'], ['das Visum, Visa', '签证'], ['das Konsulat, -e', '领事馆'], ['die Botschaft, -en', '大使馆'], ['das Kopfkissen, -', '枕头'], ['der Korridor, -e', '走廊'], ['der Krankenpfleger, -', '护士（男）'], ['das Krankenhaus, ¨er', '医院'], ['die Kursleiterin, -nen', '课程负责人'], ['der Computerraum, ¨e', '计算机房'], ['die Kurve, -n', '弯道'], ['das Couvert, -s', '信封'], ['die Landung, -en', '着陆'], ['das Lineal, -e', '尺子'], ['die Länge, -n', '长度'], ['die Langeweile', '无聊'], ['das Laufwerk, -e', '驱动器'], ['die Ansprache, -n', '演讲'], ['der Lautsprecher, -', '扬声器'], ['die Lehrstelle, -n', '学徒职位'], ['der Leserbrief, -e', '读者来信'], ['die Lohnerhöhung, -en', '加薪'], ['der Magen, ¨', '胃'], ['die Magenschmerzen pl', '胃痛'], ['die Marille, -n（奥）', '杏子'], ['die Mehrwertsteuer, -n', '增值税'], ['das Prozent, -e', '百分比'], ['der Metzger, -', '屠夫'], ['der Mitgliedsausweis, -e', '会员卡'], ['der Mitspieler, -', '队友'], ['das Modul, -e', '模块'], ['die Möhre, -n', '胡萝卜'], ['die Probe, -n', '样本'], ['der Mond, -e', '月球'], ['das Mountainbike, -s', '山地车'], ['die Müllabfuhr', '垃圾清运'], ['die Münze, -n', '硬币'], ['die Nachspeise, -n', '甜点'], ['der Nagel, ¨', '钉子'], ['die Wand, ¨e', '墙'], ['der Fingernagel, ¨', '指甲'], ['der Nasentropfen, -', '鼻滴剂'], ['die Notaufnahme, -n', '急诊室'], ['der Notausgang, ¨e', '紧急出口'], ['die Treppe, -n', '楼梯'], ['der Ober, -', '服务员'], ['die Dichte, -n', '密度'], ['das Öl, -e', '油'], ['der Ordner, -', '文件夹'], ['der Paradeiser, -（奥）', '西红柿'], ['die Pensionistin, -nen', '退休女性'], ['der Perron, -s（瑞）', '站台'], ['die Personalien pl', '个人信息'], ['der Personenstand, ¨e（瑞）', '婚姻状况'], ['der Pinguin, -e', '企鹅'], ['die Pflaume, -n', '李子'], ['der Pflaumenkuchen, -', '李子蛋糕'], ['die Pflegerin, -nen', '护士（女）'], ['das Picknick, -s', '野餐'], ['der Berg, -e', '山'], ['die Pille, -n', '药片'], ['die Pöstlerin, -nen（瑞）', '邮递员（女）'], ['die Postsendung, -en', '邮递包裹'], ['das Poulet, -s（瑞）', '鸡肉'], ['die Präsentation, -en', '演讲'], ['der Inhalt, -e', '内容'], ['die Struktur, -en', '结构'], ['das Puzzle, -s', '拼图'], ['der Rabatt, -e', '折扣'], ['der Rasen', '草坪'], ['das Referat, -e', '专题报告'], ['der Tropfen, -', '滴'], ['die Reklame, -n', '广告'], ['der Briefkasten, ¨', '信箱'], ['der Rennfahrer, -', '赛车手'], ['die Reservierung, -en', '预订'], ['der Richter, -', '法官'], ['das Urteil, -e', '判决'], ['die Rückmeldung, -en', '反馈'], ['das Rüebli, -（瑞）', '胡萝卜'], ['der Ruhetag, -e', '休息日'], ['die S-Bahn, -en', '城市快铁'], ['die Straßenbahn, -en', '有轨电车'], ['die Schulferien pl', '学校假期'], ['die Saison, -s', '旺季'], ['die Friseurin, -nen', '美发师（女）'], ['der Salon, -s', '沙龙'], ['der Schatten, -', '阴凉'], ['das Grad, -e', '度'], ['die Zahnschmerzen pl', '牙痛'], ['das Schmerzmittel, -', '止痛药'], ['das Schokoladeneis', '巧克力冰淇淋'], ['der Nachtisch, -e', '甜点'], ['der Schreck, -e', '一瞬间的惊吓'], ['der Schrecken, -', '持续的恐慌'], ['das Schwammerl, -n（奥/巴伐利亚）', '蘑菇'], ['die Schwiegereltern pl', '公婆/岳父母'], ['die Schwiegertochter, ¨', '儿媳'], ['der Schwiegerbruder, ¨', '姐夫/妹夫'], ['der Schwiegervater, ¨', '岳父/公公'], ['die Semmel, -n（奥）', '面包卷'], ['das Silvester, -', '除夕'], ['das Pfingsten, -', '圣灵降临节'], ['der Snack, -s', '零食'], ['die Pause, -n', '休息'], ['die Software, -s', '软件'], ['die Planung, -en', '计划'], ['das Sommerfest, -e', '夏日派对'], ['der Sonnabend, -e', '星期六'], ['der Speisewagen, -', '餐车'], ['der Stecker, -', '插头'], ['die Steckdose, -n', '插座'], ['der Poststempel, -', '邮戳'], ['das Datum, Daten', '日期'], ['das Paket, -e', '包裹'], ['die Steuerkarte, -n', '税卡'], ['die Strafe, -n', '罚款'], ['die Stewardess, -en', '空姐'], ['der Steward, -s', '空少'], ['das Mittagessen', '午餐'], ['der Stiefel, -', '靴子'], ['das Stiegenhaus, ¨er（奥）', '楼梯间'], ['der Strafzettel, -', '罚单'], ['der Straßenrand, ¨er', '路边'], ['die Schachtel, -n', '盒'], ['das Streichholz, ¨er', '火柴'], ['das Medikament, -e', '药物'], ['das Suchtmittel, -', '上瘾物'], ['die Tabelle, -n', '表格'], ['die Information, -en', '信息'], ['das Taschengeld', '零用钱'], ['der Monat, -e', '月'], ['das Terminal, -s', '航站楼'], ['der Textaufbau', '文本结构'], ['die Anrede, -n', '称呼'], ['die Einleitung, -en', '引言'], ['die Reihenfolge, -n', '顺序'], ['der Inhaltspunkt, -e', '内容点'], ['der Schluss, ¨e', '结尾'], ['der Tierpark, -s', '动物园'], ['das Kind, -er', '孩子'], ['die Gegnerin, -nen', '反对者（女）'], ['der Tierversuch, -e', '动物实验'], ['die Träne, -n', '眼泪'], ['das Trottoir, -s（瑞）', '人行道'], ['die Überschrift, -en', '标题'], ['der Artikel, -', '文章'], ['die Überzeugung, -en', '信念'], ['der Sturm, ¨e', '暴风雨'], ['das Schiff, -e', '船'], ['das Ufer, -', '岸'], ['die Ukraine', '乌克兰'], ['der Ukrainer, -', '乌克兰人（男）'], ['das Ukrainisch', '乌克兰语'], ['die Umleitung, -en', '绕行'], ['der Unfall, ¨e', '事故'], ['die Uniform, -en', '校服'], ['die Schule, -n', '学校'], ['die Unterschrift, -en', '签名'], ['die Urkunde, -n', '证书'], ['das Spiel, -e', '比赛'], ['der Einbruch, ¨e', '入室盗窃'], ['das Gemälde, -', '画作'], ['das Internetportal, -e', '互联网门户'], ['der User, -', '用户'], ['der Entwickler, -', '开发者'], ['die Anregung, -en', '建议'], ['die Idee, -n', '想法'], ['die Programmfunktion, -en', '程序功能'], ['das Velo, -s（瑞）', '自行车'], ['das Verkehrszeichen, -', '交通标志'], ['die Verletzung, -en', '受伤'], ['die Verliererin, -nen', '失败者（女）'], ['die Vermietung, -en', '出租'], ['die Wohnung, -en', '公寓'], ['die Versammlung, -en', '大会'], ['der Minister, -', '部长'], ['die Rede, -n', '演讲'], ['der Vollmond, -e', '满月'], ['die Vorwahl, -en', '区号'], ['der Vorwurf, ¨e', '指责'], ['die Warteschlange, -n', '排队长龙'], ['die Waschmaschine, -n', '洗衣机'], ['die Garantie, -n', '保修'], ['das Wechselgeld', '找零'], ['die Weltreise, -n', '环球旅行'], ['das Werkzeug, -e', '工具'], ['die Reparatur, -en', '维修'], ['der Wochentag, -e', '星期'], ['die Filiale, -n', '分行'], ['der Bankangestellte, -', '银行职员'], ['die Wohnfläche, -n', '居住面积'], ['der Quadratmeter, -', '平方米'], ['das Würstchen, -', '小香肠'], ['die Pommes frites pl', '炸薯条'], ['der Zahnarzt, ¨e', '牙医'], ['die Zahnbürste, -n', '牙刷'], ['die Zahncreme, -s / die Zahnpasta, -pasten', '牙膏'], ['das Zeltlager, -', '露营'], ['der Zirkus, -se', '马戏团'], ['der Zivilstand, ¨e（瑞）', '婚姻状况'], ['das Znüni, -s / das Zvieri, -s（瑞）', '上午/下午点心'], ['der Zünder, -', '打火机/引信'], ['das Zündholz, ¨er（瑞）', '火柴'], ['der Zuschlag, ¨e', '附加费'], ['der Zug, ¨e', '火车'], ['die Zustimmung, -en', '同意'], ['die Werbung', '广告'], ['der Tarif, -e', '票价'], ['die Bahn', '铁路'], ['der Bericht, -e', '报告'], ['die Einnahme, -n', '收入'], ['das Quartal, -e', '季度'], ['der Untertitel, -', '字幕'], ['der Film, -e', '电影'], ['die Uhrzeit, -en', '时间'], ['die Glocke, -n', '钟'], ['der Zufall, ¨e', '偶然'], ['der Leib, -er', '身体'], ['die Episode, -n', '插曲'], ['der Soldat, -en', '士兵'], ['das Wetter', '天气'], ['das Heer, -e', '军队'], ['die Schlacht, -en', '战斗'], ['die Region, -en', '地区'], ['der Tourismus', '旅游业'], ['der Ausdruck, ¨e', '表达/打印件'], ['die E-Mail, -s', '邮件']],
 'examples': [('Wo ist der nächste Bankomat?', '最近的自动取款机在哪？'), ('Ich habe eine Ermäßigung bekommen.', '我拿到了一张折扣券。'), ('Der Zug fährt von Perron 3 ab.', '火车从 3 号站台发车。'), ('Kann ich mit der ec-Karte zahlen?', '我能刷卡吗？')]},
{'num': 'M16-20', 'id': 'b1_andere', 'cat': 'vokabel', 'title': 'B1 其他类词汇补充', 'titleDe': 'Adjektive & Adverbien (B1)',
 'explain': 'B1 级别的形容词、副词和少量介词短语 81 条。注意固定搭配：auf stumm（调至静音）、zur Verfügung stellen（提供）、auf keinen Fall（决不）；äußerlich 是"外用的"（药物外敷），不能换成 außen（外面）；abhängig von（依赖于）介词固定，只能死记；unentschieden 指比赛已结束且比分为平局。\n\n🇬🇧 英语对照：英语 free / online 等词性灵活；德语 gratis、online 作形容词不变格，但作表语和定语位置规则一样。',
 'table': [['词汇', '中文'], ['stündlich', '每小时的'], ['fettarm', '低脂的'], ['befreit (von)', '免于……的'], ['blond', '金色的'], ['lila', '紫色的'], ['abwesend', '缺席的'], ['außen', '外面的'], ['äußerlich', '外用的（药物）'], ['aufwärts', '向上的'], ['zuständig', '负责的、主管的'], ['betrunken', '喝醉的'], ['geehrt', '尊敬的'], ['gratis', '免费的'], ['online', '在线的'], ['eckig', '方的'], ['rund', '圆的'], ['erforderlich', '必要的'], ['persönlich', '亲自的'], ['unentschieden', '（比分）平局的、未决定的'], ['farbig', '彩色的'], ['weiß', '白色的'], ['alkoholfrei', '不含酒精的'], ['rezeptfrei', '无需处方的'], ['fröhlich', '欢乐的'], ['gleichberechtigt', '平等的'], ['interkulturell', '跨文化的'], ['neblig', '有雾的'], ['vorsichtig', '小心的'], ['nochmals', '再次'], ['parallel', '平行的'], ['pauschal', '套餐形式的'], ['pensioniert', '退休的'], ['sichtbar', '明显的'], ['trotzdem', '尽管如此'], ['senkrecht', '垂直的'], ['soviel', '（soviel ich weiß 据我所知）'], ['auf keinen Fall', '在任何情况下都不'], ['problemlos', '毫无问题的'], ['solange', '只要、长达'], ['städtisch', '市政的'], ['stilistisch', '风格上的'], ['stumm', '静音的'], ['leise', '轻声的'], ['strafbar', '应受惩罚的'], ['sympathisch', '讨人喜欢的'], ['unheimlich', '吓人的、诡异的'], ['die Verabredung, -en', '约会'], ['vorläufig', '暂时的'], ['vorwärts', '向前的'], ['vorbei', '经过、过去'], ['voraussichtlich', '预计的'], ['vorgestern', '前天'], ['waagerecht', '水平的'], ['zugänglich', '可进入的'], ['unten', '在底部'], ['gelassen', '平静的'], ['sicherlich', '当然、无疑'], ['zur Verfügung', '提供（zur Verfügung stellen）'], ['erneuerbar', '可再生的'], ['jene', '那个（指示代词）'], ['positiv', '积极的'], ['negativ', '消极的'], ['unbestritten', '无可争议的'], ['europaweit', '欧洲范围内的'], ['total', '完全的'], ['sowohl...als auch', '既……又……'], ['höher', '更高的'], ['mit Gewalt', '用暴力'], ['logisch', '逻辑的'], ['teuer', '昂贵的'], ['gegenteilig', '相反的'], ['abschaffen', '废除'], ['das Fazit, -s', '结论'], ['virtuell', '虚拟的'], ['strikt', '严格的'], ['abhängig (von)', '上瘾的、依赖于……的'], ['zusätzlich', '额外的'], ['rechtlich', '法律上的'], ['verbindlich', '有约束力的'], ['konsularisch', '领事的'], ['sämtlich', '所有的'], ['(sich) aufhalten', '停留'], ['untersagen', '禁止'], ['einschließlich', '包括（介词）'], ['wie...auch', '和……一样'], ['aufstellen', '搭起'], ['aufbewahren', '保存'], ['erheben', '征收'], ['geistig', '精神的、智力的'], ['zynisch', '尖酸刻薄的'], ['verkehrt', '错误的'], ['gleichgültig', '不在乎的'], ['die Quelle, -n', '来源、渠道'], ['voraussagen', '预言']],
 'examples': [('Mein Handy ist auf stumm.', '我的手机调了静音。'), ('Ich bin trotzdem gekommen.', '我还是来了。'), ('Das Zimmer steht dir zur Verfügung.', '这个房间供你使用。'), ('Er ist nochmals gekommen.', '他又来了一次。')]},

]

def main():
    for p in GRAMMAR_POINTS:
        assert len(p['examples']) == 4, p['id']
    out = os.path.join(os.path.dirname(__file__), '..', 'kurs', 'b1', 'grammar_b1.json')
    with open(out, 'w', encoding='utf-8') as f:
        json.dump(GRAMMAR_POINTS, f, ensure_ascii=False, indent=1)
    print(f"wrote {len(GRAMMAR_POINTS)} cards -> {out}")

if __name__ == '__main__':
    main()
