# 德语词族（Wortfamilie）：同一词根的名词/动词/形容词
# 格式: 词干: [(单词, 词性, 中文), ...]
# 词性: v=动词 n=名词 a=形容词
FAMILIES = {
'fahr': [
    ('fahren', 'v', '开车；去', 'fuhr', 'gefahren'),
    ('abfahren', 'v', '出发；开走', 'fuhr ab', 'abgefahren'),
    ('erfahren', 'v', '经历；得知', 'erfuhr', 'erfahren'),
    ('die Fahrt', 'n', '旅程；车程', '', '', 'die Fahrten'),
    ('die Abfahrt', 'n', '出发；下坡', '', '', 'die Abfahrten'),
    ('die Erfahrung', 'n', '经验；经历', '', '', 'die Erfahrungen'),
    ('der Fahrer', 'n', '司机', '', '', 'die Fahrer'),
    ('das Fahrrad', 'n', '自行车', '', '', 'die Fahrräder'),
],
'sprech': [
    ('sprechen', 'v', '说；说话', 'sprach', 'gesprochen'),
    ('besprechen', 'v', '讨论', 'besprach', 'besprochen'),
    ('versprechen', 'v', '承诺', 'versprach', 'versprochen'),
    ('die Sprache', 'n', '语言', '', '', 'die Sprachen'),
    ('das Gespräch', 'n', '谈话；对话', '', '', 'die Gespräche'),
    ('das Versprechen', 'n', '承诺；诺言', '', '', 'die Versprechen'),
],
'schreib': [
    ('schreiben', 'v', '写', 'schrieb', 'geschrieben'),
    ('beschreiben', 'v', '描述', 'beschrieb', 'beschrieben'),
    ('unterschreiben', 'v', '签名', 'unterschrieb', 'unterschrieben'),
    ('die Schrift', 'n', '文字；字体', '', '', 'die Schriften'),
    ('der Schreiber', 'n', '写作者', '', '', 'die Schreiber'),
    ('schriftlich', 'a', '书面的', '', ''),
],
'steh': [
    ('stehen', 'v', '站；位于', 'stand', 'gestanden'),
    ('bestehen', 'v', '存在；通过（考试）', 'bestand', 'bestanden'),
    ('verstehen', 'v', '理解', 'verstand', 'verstanden'),
    ('der Stand', 'n', '摊位；状态', '', '', 'die Stände'),
    ('der Zustand', 'n', '状态；状况', '', '', 'die Zustände'),
    ('der Verstand', 'n', '理智；头脑', '', '', '—'),
    ('das Verständnis', 'n', '理解；谅解', '', '', 'die Verständnisse'),
],
'zieh': [
    ('ziehen', 'v', '拉；搬', 'zog', 'gezogen'),
    ('ausziehen', 'v', '搬出；脱衣', 'zog aus', 'ausgezogen'),
    ('einziehen', 'v', '搬入', 'zog ein', 'eingezogen'),
    ('umziehen', 'v', '搬家；换衣', 'zog um', 'umgezogen'),
    ('der Zug', 'n', '火车；列车', '', '', 'die Züge'),
    ('der Umzug', 'n', '搬家', '', '', 'die Umzüge'),
],
'stell': [
    ('stellen', 'v', '放；设置', 'stellte', 'gestellt'),
    ('bestellen', 'v', '订购', 'bestellte', 'bestellt'),
    ('vorstellen', 'v', '介绍；想象', 'stellte vor', 'vorgestellt'),
    ('die Stelle', 'n', '地方；职位', '', '', 'die Stellen'),
    ('die Vorstellung', 'n', '介绍；想象；演出', '', '', 'die Vorstellungen'),
    ('die Ausstellung', 'n', '展览', '', '', 'die Ausstellungen'),
],
'komm': [
    ('kommen', 'v', '来', 'kam', 'gekommen'),
    ('mitkommen', 'v', '一起来', 'kam mit', 'mitgekommen'),
    ('zurückkommen', 'v', '回来', 'kam zurück', 'zurückgekommen'),
    ('das Kommen', 'n', '到来', '', '', '—'),
    ('der Willkommen', 'n', '欢迎', '', '', '—'),
],
'nehm': [
    ('nehmen', 'v', '拿；取', 'nahm', 'genommen'),
    ('mitnehmen', 'v', '带走', 'nahm mit', 'mitgenommen'),
    ('aufnehmen', 'v', '接受；录制', 'nahm auf', 'aufgenommen'),
    ('die Aufnahme', 'n', '接收；录音', '', '', 'die Aufnahmen'),
],
'geb': [
    ('geben', 'v', '给', 'gab', 'gegeben'),
    ('aufgeben', 'v', '放弃', 'gab auf', 'aufgegeben'),
    ('eingeben', 'v', '输入', 'gab ein', 'eingegeben'),
    ('die Gabe', 'n', '天赋；赠品', '', '', 'die Gaben'),
    ('die Aufgabe', 'n', '任务；作业', '', '', 'die Aufgaben'),
    ('die Eingabe', 'n', '输入', '', '', 'die Eingaben'),
],
'seh': [
    ('sehen', 'v', '看；看见', 'sah', 'gesehen'),
    ('aussehen', 'v', '看起来', 'sah aus', 'ausgesehen'),
    ('fernsehen', 'v', '看电视', 'sah fern', 'ferngesehen'),
    ('die Sicht', 'n', '视野；看法', '', '', 'die Sichten'),
    ('die Aussicht', 'n', '展望；景色', '', '', 'die Aussichten'),
],
'arbeit': [
    ('arbeiten', 'v', '工作', 'arbeitete', 'gearbeitet'),
    ('mitarbeiten', 'v', '协作', 'arbeitete mit', 'mitgearbeitet'),
    ('die Arbeit', 'n', '工作；劳动', '', '', 'die Arbeiten'),
    ('der Arbeiter', 'n', '工人', '', '', 'die Arbeiter'),
    ('arbeitslos', 'a', '失业的', '', ''),
],
'wohn': [
    ('wohnen', 'v', '住；居住', 'wohnte', 'gewohnt'),
    ('die Wohnung', 'n', '公寓；住宅', '', '', 'die Wohnungen'),
    ('der Bewohner', 'n', '居民', '', '', 'die Bewohner'),
],
'rechn': [
    ('rechnen', 'v', '计算；算数', 'rechnete', 'gerechnet'),
    ('die Rechnung', 'n', '账单；计算', '', '', 'die Rechnungen'),
    ('der Rechner', 'n', '计算器', '', '', 'die Rechner'),
],
'üb': [
    ('üben', 'v', '练习', 'übte', 'geübt'),
    ('die Übung', 'n', '练习；习题', '', '', 'die Übungen'),
],
'spiel': [
    ('spielen', 'v', '玩；演奏', 'spielte', 'gespielt'),
    ('das Spiel', 'n', '游戏；比赛', '', '', 'die Spiele'),
    ('der Spieler', 'n', '玩家；选手', '', '', 'die Spieler'),
],
'lern': [
    ('lernen', 'v', '学习', 'lernte', 'gelernt'),
    ('das Lernen', 'n', '学习', '', '', '—'),
],
}
