# 66 个动词的三形式 + 中文
# 格式: 不定式: (过去式, 过去分词, 中文)
VERBS = {
'abhalten': ('hielt ab', 'abgehalten', '举行；阻止'),
'abwaschen': ('wusch ab', 'abgewaschen', '洗（餐具）'),
'anfangen': ('fing an', 'angefangen', '开始'),
'anschauen': ('schaute an', 'angeschaut', '观看'),
'anschließen': ('schloss an', 'angeschlossen', '连接；接通'),
'arbeiten': ('arbeitete', 'gearbeitet', '工作'),
'aufgeben': ('gab auf', 'aufgegeben', '放弃；交运（行李）'),
'aufnehmen': ('nahm auf', 'aufgenommen', '接受；录制；开始'),
'ausprobieren': ('probierte aus', 'ausprobiert', '试一试'),
'ausziehen': ('zog aus', 'ausgezogen', '搬出；脱（衣）'),
'beraten': ('beriet', 'beraten', '咨询；商议'),
'beschreiben': ('beschrieb', 'beschrieben', '描述'),
'besprechen': ('besprach', 'besprochen', '讨论；商量'),
'bestellen': ('bestellte', 'bestellt', '订购；预订'),
'bezahlen': ('bezahlte', 'bezahlt', '支付；付钱'),
'bringen': ('brachte', 'gebracht', '带来；拿来'),
'darstellen': ('stellte dar', 'dargestellt', '描绘；表现；构成'),
'eingeben': ('gab ein', 'eingegeben', '输入（数据）'),
'einstellen': ('stellte ein', 'eingestellt', '调整；雇佣；停止'),
'einziehen': ('zog ein', 'eingezogen', '搬入；吸入'),
'entspannen': ('entspannte', 'entspannt', '放松'),
'erklären': ('erklärte', 'erklärt', '解释；说明'),
'erziehen': ('erzog', 'erzogen', '教育；养育'),
'eröffnen': ('eröffnete', 'eröffnet', '开幕；开设'),
'fahren': ('fuhr', 'gefahren', '开车；去；行驶'),
'fangen': ('fing', 'gefangen', '抓住；捕捉'),
'geben': ('gab', 'gegeben', '给'),
'halten': ('hielt', 'gehalten', '拿着；保持；认为'),
'hinbringen': ('brachte hin', 'hingebracht', '送去；带去'),
'hinfahren': ('fuhr hin', 'hingefahren', '开车去；去'),
'hinhalten': ('hielt hin', 'hingehalten', '拖延；敷衍'),
'holen': ('holte', 'geholt', '取；接'),
'klären': ('klärte', 'geklärt', '澄清；弄清'),
'kommen': ('kam', 'gekommen', '来'),
'mitarbeiten': ('arbeitete mit', 'mitgearbeitet', '协作；合作'),
'mitkommen': ('kam mit', 'mitgekommen', '一起来；跟来'),
'mitnehmen': ('nahm mit', 'mitgenommen', '带走；顺便带'),
'nehmen': ('nahm', 'genommen', '拿；取；吃（药）'),
'probieren': ('probierte', 'probiert', '尝试；试吃'),
'reisen': ('reiste', 'gereist', '旅行'),
'schauen': ('schaute', 'geschaut', '看；瞧'),
'schieben': ('schob', 'geschoben', '推；滑'),
'schließen': ('schloss', 'geschlossen', '关；关闭'),
'schreiben': ('schrieb', 'geschrieben', '写'),
'setzen': ('setzte', 'gesetzt', '放；设置；坐下'),
'spannen': ('spannte', 'gespannt', '拉紧；绷紧；使紧张'),
'sprechen': ('sprach', 'gesprochen', '说；说话'),
'stehen': ('stand', 'gestanden', '站；位于；处于'),
'stellen': ('stellte', 'gestellt', '放；设置；提出'),
'umsetzen': ('setzte um', 'umgesetzt', '实施；执行；换座位'),
'umziehen': ('zog um', 'umgezogen', '搬家；换（衣服）'),
'unterhalten': ('unterhielt', 'unterhalten', '娱乐；交谈；维持'),
'unterschreiben': ('unterschrieb', 'unterschrieben', '签名；签署'),
'verbringen': ('verbrachte', 'verbracht', '度过（时间）'),
'verraten': ('verriet', 'verraten', '泄露；背叛；透露'),
'verreisen': ('verreiste', 'verreist', '出门旅行'),
'verstehen': ('verstand', 'verstanden', '理解；懂'),
'vorschieben': ('schob vor', 'vorgeschoben', '推到前面；找借口'),
'vorstellen': ('stellte vor', 'vorgestellt', '介绍；想象；提出'),
'waschen': ('wusch', 'gewaschen', '洗'),
'wegfahren': ('fuhr weg', 'weggefahren', '开车离开'),
'wiederholen': ('wiederholte', 'wiederholt', '重复'),
'zahlen': ('zahlte', 'gezahlt', '付钱；数数'),
'ziehen': ('zog', 'gezogen', '拉；拖；搬'),
'zurückholen': ('holte zurück', 'zurückgeholt', '取回；接回'),
'zurückkommen': ('kam zurück', 'zurückgekommen', '回来；返回'),
'zusammenarbeiten': ('arbeitete zusammen', 'zusammengearbeitet', '合作；协作'),
'öffnen': ('öffnete', 'geöffnet', '打开'),
'übersetzen': ('übersetzte', 'übersetzt', '翻译；摆渡'),
}
