# A2 课程语法（按站内实际模块顺序，18 个语法点）
# 数据源：站内课程目录+课件要点（已登录核验）；讲解与例句均为原创，不含视频内容
# 生成：python3 scripts/build_a2_grammar.py -> kurs/a2/grammar_a2.json
import json, os

GRAMMAR_POINTS = [
{'num': 'M09-02', 'id': 'genitiv', 'cat': 'ge', 'title': '第二格', 'titleDe': 'Genitiv',
 'explain': '第二格表所属/所有关系，提问用 wessen（谁的）。冠词：der→des、die→der、das→des、die（复数）→der。阳性、中性名词单数词干后加 -s，s/st/zt/sch/x/z/ß 结尾加 -es（des Hauses）；阴性、复数不加词尾。人称代词第二格（meiner、deiner…）只用于搭配支配第二格的动词或介词。"因为我"三种说法：wegen mir（较正式）、wegen meiner（较书面）、meinetwegen（口语）。口语常避开第二格，改用 von + 第三格（von meiner Frau）。\n\n🇬🇧 英语对照：英语用 s 或 of；德语第二格口语萎缩、书面语用，口语多用 von + 三格代替。',
 'table': [['', '阳性', '阴性', '中性', '复数'],
           ['一格', 'der Mann', 'die Frau', 'das Kind', 'die Kinder'],
           ['二格', 'des Mannes', 'der Frau', 'des Kindes', 'der Kinder']],
 'examples': [
     ('Das ist das Auto meines Vaters.', '这是我父亲的车。'),
     ('Wegen des Wetters bleiben wir zu Hause.', '因为天气我们待在家里。'),
     ('Die Meinung der Experten ist wichtig.', '专家们的意见很重要。'),
     ('Trotz des Regens gehen wir spazieren.', '尽管下雨我们还是去散步。'),
 ]},
{'num': 'M09-03', 'id': 'n_deklination', 'cat': 'mingci', 'title': '阳性弱变化', 'titleDe': 'N-Deklination',
 'explain': '少数阳性名词在二、三、四格（单复数皆如此）词干后加 -n 或 -en，判断靠拼写/词尾而非含义。三类：以 -e 结尾的阳性名词（der Junge）；大部分 -and/-ant/-ent/-ist 等结尾的外来词（der Student）；一小撮日耳曼词（Herr、Bauer、Nachbar、Mensch）。8 个特殊词第二格还要加 -s：Name、Buchstabe、Friede、Funke、Glaube、Gedanke、Same、Wille。das Herz 是唯一服从弱变化的中性词（des Herzens）。易错：名词化形容词（如 den Alten）不是弱变化；加完 -en 后绝不再加 s；无冠词时不加 -n/-en（der Herr 除外）。\n\n🇬🇧 英语对照：英语完全没有这种现象；只能按词尾类型记，是德语名词最"不讲理"的部分之一。',
 'table': [['一格', '二/三/四格'],
           ['der Junge', 'des/dem/den Jungen'],
           ['der Student', 'des/dem/den Studenten'],
           ['der Herr', 'des/dem/den Herrn'],
           ['der Name', 'des Namens（特殊+ s）']],
 'examples': [
     ('Ich sehe den Jungen.', '我看见那个男孩。'),
     ('Das ist der Name des Studenten.', '这是那个学生的名字。'),
     ('Er hilft dem Herrn.', '他帮助那位先生。'),
     ('Jeder Mensch hat Träume.', '每个人都有梦想。'),
 ]},
{'num': 'M09-04', 'id': 'reflexiv', 'cat': 'dongci', 'title': '反身动词', 'titleDe': 'Reflexive Verben',
 'explain': '反身代词：第一二人称与人称代词同形（mich/dich/uns/euch），三人称一律 sich（er/sie/es/wir? 不，wir 是 uns；ihr 是 euch；sie/Sie 是 sich）。真反身动词：sich 是动词必要组成部分，去掉就不完整（sich freuen、sich befinden、sich kümmern um），需逐个记。假反身动词：sich 本身承载意思（如 sich etwas überlegen 表"认真考虑"）。sich 表"互相"可换成 einander（较书面）。易错：Ich wasche mir die Hände（洗手），不能说 meine Hände；真反身动词助动词通常用 haben。\n\n🇬🇧 英语对照：英语 enjoy oneself / each other；德语真假反身要逐个记，假反身的 sich 有实在含义。',
 'table': [['人称', '三格', '四格'],
           ['ich', 'mir', 'mich'],
           ['du', 'dir', 'dich'],
           ['er/sie/es', 'sich', 'sich'],
           ['wir', 'uns', 'uns'],
           ['ihr', 'euch', 'euch'],
           ['sie/Sie', 'sich', 'sich']],
 'examples': [
     ('Ich freue mich auf dich.', '我很期待见到你。'),
     ('Sie interessiert sich für Musik.', '她对音乐感兴趣。'),
     ('Wir treffen uns morgen.', '我们明天见。'),
     ('Ich wasche mir die Hände.', '我洗手。'),
 ]},
{'num': 'M09-05', 'id': 'wenn_als', 'cat': 'congju', 'title': 'wenn / als / wann / ob 从句', 'titleDe': 'wenn, als, wann, ob',
 'explain': 'ob = 是否（间接疑问句）。als = 过去一次性事件（纵然一生只发生一次，如十岁那年）。wenn = 现在/将来/过去重复多次的事（过去重复常配 immer/jedes Mal 加强频率）。wann = 何时（疑问句用），wenn = 当……时。从句前置时从句整体占主句第一位，主句变位动词仍在第二位。表示时长/频率的时间状语可用第四格直接做，不需介词（jeden Tag 每天）。\n\n🇬🇧 英语对照：英语 when 兼任 als/wenn；德语按"过去一次性"vs"重复/现在将来"严格区分，这是中式思维重灾区。',
 'table': [['连词', '用法', '例子'],
           ['als', '过去一次性', 'Als ich zehn war, …'],
           ['wenn', '重复/现在/将来', 'Wenn es regnet, …'],
           ['wann', '何时（疑问）', 'Wann kommst du?'],
           ['ob', '是否', 'Ich weiß nicht, ob …']],
 'examples': [
     ('Als ich ein Kind war, wohnten wir in Berlin.', '我小时候我们住在柏林。'),
     ('Wenn ich Zeit habe, lese ich.', '我有空就读书。'),
     ('Weißt du, ob er kommt?', '你知道他来不来吗？'),
     ('Ruf mich an, wenn du fertig bist!', '你弄完给我打电话！'),
 ]},
{'num': 'M09-10', 'id': 'da_wo', 'cat': 'qita', 'title': '代副词', 'titleDe': 'Pronominaladverbien',
 'explain': 'da(r) + 介词（指示）、wo(r) + 介词（疑问），前提：介词后面是无生命名词（darauf、womit）。有人参与时用"人称代词 + 介词"（mit ihm），对人提问用 wer/wen/wem + 介词。常见副词化用法：damit（以便，连词）、darum/daher（因此）、dabei sein（加入；dabei sein + zu 不定式 = 正在做某事）、dabeihaben（带上，可分动词）。易错：别和表地点的 wo（哪里）混淆；副词不能跟主语抢第一位。\n\n🇬🇧 英语对照：英语 thereof/whereby 已死亡，德语代副词极其常用；可以理解为"介词的代词化"。',
 'table': [['介词', 'da-（指示）', 'wo-（疑问）'],
           ['mit', 'damit', 'womit'],
           ['für', 'dafür', 'wofür'],
           ['auf', 'darauf', 'worauf'],
           ['über', 'darüber', 'worüber']],
 'examples': [
     ('Womit fährst du? – Mit dem Bus.', '你坐什么去？——公交。'),
     ('Ich denke oft daran.', '我常想起它。'),
     ('Wofür interessierst du dich?', '你对什么感兴趣？'),
     ('Bist du dabei?', '你加入吗？'),
 ]},
{'num': 'M10-01', 'id': 'stehen_stellen', 'cat': 'dongci', 'title': '近义词辨析：位置动词', 'titleDe': 'stehen/stellen, sitzen/setzen …',
 'explain': '状态（不及物，表静止）vs 动作（及物，改变物体状态）：stehen/stellen（站立/放站）、sitzen/setzen（坐/放坐）、liegen/legen（躺/放躺）、hängen（悬挂 gehangen / 挂放 gehängt）、stecken（插入）。按物体姿势选词：liegen 躺、stehen 站立或有底座、sitzen 屈膝坐、hängen 悬挂、stecken 插入。特殊：Schuh/Topf/Pfanne 底面接触用 stehen；Laptop 开着用 stehen、合上用 liegen。"戴帽子"用地道表达：Ich setze mir einen Hut auf den Kopf（反身代词 + 定冠词）。\n\n🇬🇧 英语对照：英语 lie/lay、sit/set 也有对应区分；德语多一组 stehen/stellen，逻辑完全一样。',
 'table': [['状态（不及物）', '动作（及物）'],
           ['stehen（站着）', 'stellen（放站）'],
           ['sitzen（坐着）', 'setzen（放坐）'],
           ['liegen（躺着）', 'legen（放躺）'],
           ['hängen（悬挂, gehangen）', 'hängen（挂放, gehängt）']],
 'examples': [
     ('Das Buch liegt auf dem Tisch.', '书躺在桌上。'),
     ('Ich lege das Buch auf den Tisch.', '我把书放到桌上。'),
     ('Er sitzt auf dem Stuhl.', '他坐在椅子上。'),
     ('Setz dich bitte!', '请坐！'),
 ]},
{'num': 'M10-02', 'id': 'zu_infinitiv', 'cat': 'dongci', 'title': '带 zu 的不定式', 'titleDe': 'Infinitiv mit zu',
 'explain': '形式：zu + 动词原形，其支配的宾语/状语放 zu 前面（尾语序），整段放句末逗号后。作主语（Es ist schön, dich zu sehen.）、作宾语（versuchen/anfangen/vergessen/versprechen + zu）、作名词补语（die Lust, …zu…）、作形容词补语。um + zu（为了，要求主从句主语一致）、ohne + zu（没有…就…）。易错：wissen 后面不能接带 zu 不定式（死记）。\n\n🇬🇧 英语对照：对应英语 to do；德语要求尾语序，且 um…zu 要求主语一致是英语没有的限制。',
 'table': [['用法', '例子'],
           ['作主语', 'Es ist schön, dich zu sehen.'],
           ['作宾语', 'Ich versuche, früh zu kommen.'],
           ['um + zu（为了）', 'Ich lerne, um zu bestehen.'],
           ['ohne + zu', 'Er ging, ohne zu grüßen.']],
 'examples': [
     ('Es freut mich, dich zu sehen.', '见到你我很高兴。'),
     ('Ich habe vergessen, ihn anzurufen.', '我忘了给他打电话。'),
     ('Um pünktlich zu sein, stehe ich früh auf.', '为了准时，我早起。'),
     ('Er hofft, bald zu kommen.', '他希望快点来。'),
 ]},
{'num': 'M10-03', 'id': 'nach_zu', 'cat': 'ge', 'title': '表示"去"的介词', 'titleDe': 'Präpositionen der Richtung',
 'explain': 'nach + 无冠词名词：地名（城市、国家）、方位副词（nach Hause/rechts/links/oben/unten）。in + 可"进去"的地点（Kino、Mensa、Berge、Schweiz、USA、Iran、Ausland）；带冠词的国家（die USA、der Iran）用 in 不用 nach。zu：zum/zur + 具体的人或地点（nach Hause 除外）、交通工具。auf + 露天地点（Straße、Sportplatz、Land）；an + 某物边上（Fenster、Strand、Grenze、See）。易错：in = 进去 vs zu = 朝…走（不一定进）；单座 Berg 不用 in。\n\n🇬🇧 英语对照：英语 go to 一词打天下；德语按"地名/可进入/露天/边上"选介词，只能分类记。',
 'table': [['介词', '用于', '例子'],
           ['nach', '无冠词地名', 'nach Berlin / nach Hause'],
           ['in', '可进入的地点', 'ins Kino / in die Schweiz'],
           ['zu', '人/具体地点', 'zu meiner Freundin'],
           ['auf', '露天', 'auf den Sportplatz'],
           ['an', '边上', 'an den Strand']],
 'examples': [
     ('Ich fahre nach Berlin.', '我去柏林。'),
     ('Wir gehen ins Kino.', '我们去电影院。'),
     ('Kommst du zu mir?', '你来我这吗？'),
     ('Die Kinder spielen auf der Straße.', '孩子们在街上玩。'),
 ]},

{'num': 'M10-04', 'id': 'nebenssatz', 'cat': 'congju', 'title': '原因 / 结果 / 目的 / 让步', 'titleDe': 'Kausal-, Konsekutiv-, Final-, Konzessivsätze',
 'explain': '原因：并列连词 denn（不占位、不能放句首）/ nämlich（放变位动词后）；附属连词 weil / da；介词 wegen（书面支配二格，口语可三格）。结果：并列连词 daher；附属连词 sodass；副词 deshalb / deswegen / darum（占一位）。目的：附属连词 damit；um…zu…（要求主从句主语一致）。让步：附属连词 obwohl；介词 trotz（支配二格）；副词 trotzdem。易错：用了 weil 就不能再加 deshalb；口语里 trotzdem 不能代替 obwohl。\n\n🇬🇧 英语对照：英语 because / so / although；德语 denn（并列）vs weil（附属尾语序）的区分是重点。',
 'table': [['含义', '并列（主句语序）', '附属（尾语序）'],
           ['原因', 'denn', 'weil / da'],
           ['结果', 'daher', 'sodass'],
           ['目的', '—', 'damit / um…zu…'],
           ['让步', 'trotzdem（副词）', 'obwohl']],
 'examples': [
     ('Ich bleibe zu Hause, weil ich krank bin.', '因为我病了，我待在家里。'),
     ('Es regnet, daher bleiben wir hier.', '下雨，所以我们待在这。'),
     ('Ich lerne Deutsch, um in Deutschland zu studieren.', '我学德语是为了去德国读书。'),
     ('Obwohl es regnet, gehen wir spazieren.', '尽管下雨，我们还是去散步。'),
 ]},
{'num': 'M10-05', 'id': 'passiv', 'cat': 'dongci', 'title': '被动语态', 'titleDe': 'Passiv',
 'explain': 'Vorgangspassiv（werden + 过去分词，强调动作过程）vs Zustandspassiv（sein + 过去分词，强调动作完成后的状态）。Zustandspassiv 只有能产生明确结果的动词可用；它的现在时约等于 Vorgangspassiv 的完成时。规则：只有四格直接宾语能变成被动主语；三格/二格/介词宾语不行，此时常用无人称形式（Es wird getanzt. 有人在跳舞）。von = 对动作有绝对控制的人；durch = 物/媒介/方式；mit = 具体工具。易错：被动句中过去分词的助动词是 worden（其他情况是 geworden）；bedeuten、besitzen、enthalten、haben、kennen、wissen 等及物动词例外，不能变被动，用 man 作主语表达。\n\n🇬🇧 英语对照：英语 be done 一套打天下；德语分"过程被动"和"状态被动"，是英语没有的精细区分。',
 'table': [['类型', '结构', '例子'],
           ['过程被动', 'werden + 过去分词', 'Das Haus wird gebaut.'],
           ['状态被动', 'sein + 过去分词', 'Das Haus ist gebaut.'],
           ['施动者', 'von（人）/ durch（媒介）', 'von ihm / durch den Sturm']],
 'examples': [
     ('Das Auto wird repariert.', '车正在被修。（过程）'),
     ('Das Auto ist repariert.', '车修好了。（状态）'),
     ('Die Tür wurde von ihm geöffnet.', '门被他打开了。'),
     ('Es wird viel getanzt.', '大家跳了很多舞。（无人称）'),
 ]},
{'num': 'M10-06', 'id': 'relativsatz', 'cat': 'congju', 'title': '关系代词和关系从句', 'titleDe': 'Relativsätze',
 'explain': '关系代词的性数看先行词，格看它在从句中的成分；紧跟被修饰名词。二格：dessen（阳/中）、deren（阴/复）——dessem 是母语者常犯的错误。先行词是第一/二人称代词时，从句中重复人称代词且动词与其变位一致。was 引导关系从句的四种场景：修饰 etwas / nichts / alles、名词化中性形容词、指示代词 das、代指整句话。was 作介词宾语时须与介词合并成代副词（worauf）。wo 代替"介词 + 地点状语"时，先行词无冠词只能用 wo。\n\n🇬🇧 英语对照：英语 who/which/that；德语关系代词要变格，二格 dessen/deren 是英语没有的。',
 'table': [['先行词', '一格', '四格', '二格'],
           ['阳性', 'der', 'den', 'dessen'],
           ['阴性', 'die', 'die', 'deren'],
           ['中性', 'das', 'das', 'dessen'],
           ['复数', 'die', 'die', 'deren']],
 'examples': [
     ('Der Mann, der dort steht, ist mein Lehrer.', '站在那的男人是我老师。'),
     ('Das Buch, das ich lese, ist spannend.', '我正在读的书很刺激。'),
     ('Die Frau, deren Auto kaputt ist, wartet.', '车坏了的那位女士在等。'),
     ('Alles, was er sagt, stimmt.', '他说的都对。'),
 ]},
{'num': 'M10-07', 'id': 'konjunktiv2', 'cat': 'dongci', 'title': '第二虚拟式', 'titleDe': 'Konjunktiv II',
 'explain': '形成：规则动词二虚 = 一般过去时；不规则动词 = 过去时词干加变音 + 一三单加 -e 补齐。除 sein/haben/werden/情态动词外，其余动词都用 würden + 动词原形代替。用法：礼貌愿望/请求（Würden Sie bitte…）、与事实相悖的愿望（wenn…würde…）、假设。"Ich hätte es wissen müssen." = 本该知道（表与过去事实相反）。易错：würden 不能直接连带情态动词；主从句时态/虚拟形式保持一致。\n\n🇬🇧 英语对照：英语 If I were / would；德语 würde + 原形是万能钥匙，sein/haben/werden/情态动词才用真二虚。',
 'table': [['动词', '第二虚拟式'],
           ['sein', 'wäre'],
           ['haben', 'hätte'],
           ['werden', 'würde'],
           ['können', 'könnte'],
           ['müssen', 'müsste'],
           ['kommen', 'käme（或 würde kommen）']],
 'examples': [
     ('Wenn ich Zeit hätte, käme ich mit.', '我有空的话就跟你去。'),
     ('Würden Sie mir bitte helfen?', '能请您帮我一下吗？'),
     ('Ich wäre gern dabei.', '我很想参加。'),
     ('An deiner Stelle würde ich das nicht tun.', '换作我不会这么做。'),
 ]},
{'num': 'M11-01', 'id': 'wortstellung2', 'cat': 'jufa', 'title': '语序（中高级篇）', 'titleDe': 'Wortstellung (B)',
 'explain': '核心原则：先说不重要/旧信息，后说重要/新信息。中场成分层级链：代词宾语 → 状语和确指名词宾语 → 泛指/零冠词名词宾语 → 表示方向的状语 → 介词宾语。两个代词宾语时四格在三格前。同一级别的状语顺序：态度副词 → 时间 → 原因 → 地点 → 方式。从句前置占主句第一位时，主句动词仍在第二位。\n\n🇬🇧 英语对照：英语语序相对固定 SVO；德语中场是按"信息重要性"排序的，这是德语语感的核心。',
 'table': [['位置', '放什么', '例子'],
           ['中场前', '代词宾语', 'Ich gebe es dir.'],
           ['中场中', '状语 + 确指宾语', 'Ich gebe dir das Buch heute.'],
           ['中场后', '介词宾语', 'Ich denke an dich.']],
 'examples': [
     ('Ich habe es ihm gestern gegeben.', '我昨天把它给他了。'),
     ('Er hat mir das Buch aus Berlin mitgebracht.', '他从柏林给我带来了这本书。'),
     ('Weil er krank ist, bleibt er zu Hause.', '因为他病了，他待在家里。'),
     ('Gib es mir bitte!', '请把它给我！'),
 ]},
{'num': 'M11-02', 'id': 'dativ_verben', 'cat': 'dongci', 'title': '只支配第三格的动词', 'titleDe': 'Verben mit Dativ',
 'explain': '四类归纳：①表"发生"（geschehen、passieren、gelingen，助动词 sein；bevorstehen 临近用 haben）②zu-/nach-/bei-/ent- 前缀动词（zuhören、zusehen、zustimmen、entsprechen、widersprechen）③主语是物表感觉/评价（gefallen、fehlen、schmecken、wehtun、auffallen）④表人际（gratulieren、helfen、gehören、folgen、danken）。易错：glauben + 人 = 三格（Niemand wollte ihm glauben.），+ 物 = 四格，glauben an = 更深层的相信；erfolgen 不支配宾语。\n\n🇬🇧 英语对照：英语无此概念；只能按"动词词典"逐个记——A1 的 helfen/danken 只是冰山一角。',
 'table': [['类别', '动词', '例子'],
           ['发生', 'geschehen / gelingen', 'Es geschieht mir oft.'],
           ['前缀动词', 'zuhören / widersprechen', 'Ich höre dir zu.'],
           ['感觉评价', 'gefallen / wehtun', 'Das gefällt mir.'],
           ['人际', 'helfen / gratulieren', 'Ich helfe dir.']],
 'examples': [
     ('Das Konzert gefällt mir sehr.', '我很喜欢这场音乐会。'),
     ('Hör mir bitte zu!', '请听我说！'),
     ('Er gratuliert seiner Schwester.', '他祝贺他姐姐。'),
     ('Der Schlüssel gehört mir.', '这钥匙是我的。'),
 ]},
{'num': 'M11-03', 'id': 'artikel_pronomen', 'cat': 'mingci', 'title': '冠词作代词', 'titleDe': 'Artikel als Pronomen',
 'explain': '定冠词作代词相当于"这个/那个…"，变格与冠词一致，但复数三格是 denen（不是 den）、复数二格 deren/derer；可加重读音表强调。einer + von/nach 两类用法："他们中的一个"和"一个这样的人"。不定冠词作代词：①"一群中的一个"（英语 one of）②"某人"（较 jemand 不礼貌）③固定搭配 der eine…, der andere…（一个…另一个…/一些…另一些…）。易错：复数三格代词是 denen 而不是 den；andere- 是代词不是形容词名词化（etwas anderes 小写）。\n\n🇬🇧 英语对照：英语 one/ones；德语直接拿冠词当代词用，复数三格 denen 是特例。',
 'table': [['作代词', '一格', '三格'],
           ['der', 'der da', 'dem da'],
           ['die（复数）', 'die da', 'denen（特例！）'],
           ['einer', 'einer von uns', 'einem von uns']],
 'examples': [
     ('Der da drüben ist mein Bruder.', '那边那个是我哥哥。'),
     ('Denen kann man nicht trauen.', '那些人不可信。'),
     ('Einer von uns muss gehen.', '我们中得去一个。'),
     ('Der eine lacht, der andere weint.', '一个笑，一个哭。'),
 ]},
{'num': 'M11-04', 'id': 'tiere', 'cat': 'mingci', 'title': '动物', 'titleDe': 'Tiere',
 'explain': '以单词表为核心，每词标冠词和复数，冠词大多靠死记。性别分布：阳性居多（der Hund/Hase/Löwe/Affe/Elefant）；中性如 das Kaninchen/Huhn/Schaf/Pferd；阴性如 die Katze/Kuh/Maus/Spinne。不只动物名词本身是弱变化（der Hase→den Hasen、der Bär→den Bären、der Löwe→den Löwen）。易错/趣点：der Hase（野兔）vs das Kaninchen（家兔）；der Moskito（蚊子，阳性）vs die Mücke（蚊子，阴性）。\n\n🇬🇧 英语对照：英语 animal 词无性；德语动物名词阳性占大头，性多靠死记。',
 'table': [['动物', '冠词', '复数'],
           ['狗', 'der Hund', 'die Hunde'],
           ['猫', 'die Katze', 'die Katzen'],
           ['野兔', 'der Hase', 'die Hasen'],
           ['家兔', 'das Kaninchen', 'die Kaninchen'],
           ['马', 'das Pferd', 'die Pferde'],
           ['鸟', 'der Vogel', 'die Vögel']],
 'examples': [
     ('Der Hund bellt.', '狗在叫。'),
     ('Die Katze schläft auf dem Sofa.', '猫在沙发上睡觉。'),
     ('Ein Hase läuft über die Wiese.', '一只野兔跑过草地。'),
     ('Das Pferd ist schnell.', '马跑得快。'),
 ]},
{'num': 'M12-01', 'id': 'der_ein_woerter', 'cat': 'mingci', 'title': 'der-Wörter 和 ein-Wörter', 'titleDe': 'der-Wörter / ein-Wörter',
 'explain': 'ein-Wörter = 所有物主代词（mein-、dein-…）+ kein；der-Wörter = dies-、jed-、manch-、solch-、welch-、all-、jen-。作代词使用时，ein-/der-Wörter 的变格分别服从不定冠词/定冠词作代词的规则。all- 作代词：alles = 所有事情（中性不可数），alle = 所有人（复数可数）。manches = 一些事情（中性不可数），manche = 一些人。易错：der-Wörter 二格词尾与冠词作代词的二格不同。\n\n🇬🇧 英语对照：英语 this/every/such；德语把这类词系统化为 der-Wörter，变格走定冠词路线。',
 'table': [['类别', '成员', '变格路线'],
           ['ein-Wörter', 'mein-, dein-, kein-…', '走不定冠词路线'],
           ['der-Wörter', 'dies-, jed-, welch-, all-…', '走定冠词路线'],
           ['all-', 'alles（事情）/ alle（人）', '不可数 vs 可数']],
 'examples': [
     ('Jedes Kind bekommt ein Geschenk.', '每个孩子都得到一份礼物。'),
     ('Manche Leute mögen keinen Kaffee.', '有些人不喜欢咖啡。'),
     ('Alles ist fertig.', '一切都准备好了。'),
     ('Welches Buch liest du?', '你在读哪本书？'),
 ]},
{'num': 'M12-02', 'id': 'kriegen_passiv', 'cat': 'dongci', 'title': 'kriegen / bekommen 的被动', 'titleDe': 'bekommen-Passiv',
 'explain': '口语/非正式书面语中 bekommen/kriegen（罕见 erhalten）可引导被动，原第三格间接宾语变为第一格主语（Er bekommt einen Brief geschrieben. 他收到一封信/有人给他写了信）。对应英语 have/get sth done：请人做某事、自己不亲自做（Ich bekomme die Haare geschnitten. 我让人剪头发）。gehören 本身支配三格，也有被动含义：Der Wagen gehört repariert.（这车该修了）。易错：kriegen/bekommen 的被动用法很口语，正式书面语应避免；gratulieren、helfen 等三格动词是典型例子。\n\n🇬🇧 英语对照：对应英语 get sth done；德语用 bekommen/kriegen 实现，口语常用、考试少考。',
 'table': [['结构', '例子', '含义'],
           ['bekommen + 过去分词', 'Er bekommt das Auto repariert.', '他的车被修了'],
           ['kriegen + 过去分词', 'Er kriegt das Geld überwiesen.', '他收到汇款'],
           ['gehören + 过去分词', 'Der Wagen gehört repariert.', '这车该修了']],
 'examples': [
     ('Ich bekomme die Haare geschnitten.', '我让人剪头发。'),
     ('Er kriegt das Geld überwiesen.', '他收到汇款。'),
     ('Der Wagen gehört repariert.', '这车该修了。'),
     ('Sie bekommt ein Paket geschickt.', '她收到一个包裹。'),
 ]},
]

def main():
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'kurs', 'a2')
    os.makedirs(out_dir, exist_ok=True)
    data = []
    for p in GRAMMAR_POINTS:
        data.append({
            'num': p['num'], 'id': p['id'], 'cat': p['cat'],
            'title': p['title'], 'titleDe': p['titleDe'],
            'explain': p['explain'], 'table': p.get('table', []),
            'examples': [list(e) for e in p['examples']],
        })
    out = os.path.join(out_dir, 'grammar_a2.json')
    with open(out, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
    print(f'wrote {out} ({len(data)} points)')

if __name__ == '__main__':
    main()
