# C1 课程语法+词汇（按站内实际模块顺序，6 个卡片）
# 数据源：站内课程目录+课件要点（已登录核验）；讲解为原创重写（贴近原文要点），例句采用课程原文短句，不含视频内容
# 生成：python3 scripts/build_c1_grammar.py -> kurs/c1/grammar_c1.json
import json, os

GRAMMAR_POINTS = [{'num': 'M21-01',
  'id': 'dativ_verben2',
  'cat': 'yufa',
  'title': '支配第三格的动词（二）',
  'titleDe': 'Verben mit Dativ (2)',
  'explain': '支配第三格的动词（二）。① 本课是 A2 阶段三格动词的延续，收录此前未讲的三格动词，属于查漏补缺性质。② 核心是带可分前缀的三格动词家族：bei-（beistehen '
             '帮助、beiwohnen 出席）、entgegen-（entgegengehen 走向、entgegenwirken 对抗）、nach-（nachgeben '
             '让步、nachkommen 履行、nachlaufen 追随、nachstellen 追求、nachstreben 效仿）、wider-（widerstehen '
             '抵抗）。③ 易错点：beistehen（三格"帮助"）不要写成 bestehen（"由…组成/通过"，用法完全不同）；sich widersetzen '
             '是三格反身动词（Ich habe mich dem Plan widersetzt），不要漏掉反身代词；widerstehen（不及物，三格）与 '
             'widerlegen（四格"反驳"）是两词。④ 记忆技巧：前缀 nach-/entgegen-/wider- '
             '带有"朝向/逆向"的方向感，这类动词多支配三格；geschehen（发生）是典型无人称三格动词（was in jenem Jahr geschehen war）。⑤ '
             'entsagen（三格"放弃"）后常接抽象名词三格复数（den Freuden des Lebens），写作中可替换口语化的 aufgeben。⑥ '
             '语序注意：这些动词在从句中居句尾（was in jenem Jahr geschehen war）。\n'
             '\n'
             '🇬🇧 英语对照：英语 attend/resist 无介词；德语 beiwohnen/widerstehen + 三格，前缀家族整批背。',
  'table': [['动词', '含义', '例子'],
            ['beistehen', '援助', 'Er steht mir bei.'],
            ['nachgeben', '让步', 'Er gibt dem Druck nach.'],
            ['nachkommen', '履行/跟上', 'Sie kommt ihrer Pflicht nach.'],
            ['widerstehen', '抵挡', 'Er widersteht der Versuchung.'],
            ['sich widersetzen', '反抗', 'Sie widersetzt sich dem Plan.']],
  'examples': [['Sie müssen der Gerichtsverhandlung beiwohnen.', '你们必须出席庭审。（beiwohnen+三格）'],
               ['Du musst den Freuden des Lebens nicht entsagen.', '你不必放弃人生的乐趣。（entsagen+三格）'],
               ['Offenkundig hat sie der Versuchung widerstanden.', '显然她抵挡住了诱惑。（widerstehen+三格）'],
               ['Alle Studenten hier strebten ihrem Lehrer nach.', '这里所有学生都效仿他们的老师。']]},
 {'num': 'M22-01',
  'id': 'adj_praep',
  'cat': 'vokabel',
  'title': '形容词和介词的搭配总结',
  'titleDe': 'Adjektiv + Präposition',
  'explain': '形容词和介词的搭配总结。① 形容词固定搭配介词是 C1 考试高频考点，不能按中文"对…"直译成一个介词，必须逐个记忆。② von（+三格）表来源/原因：abhängig '
             'von、begeistert von、enttäuscht von、überzeugt von；注意 von dem 缩合为 vom（begeistert vom '
             'Gesang）。③ auf（+四格）表情绪指向：stolz auf、neugierig auf、eifersüchtig auf、neidisch '
             'auf；对象是被指向的人或事。④ an（+三格）表关联：interessiert an、erkrankt an、reich an、schuld an、beteiligt '
             'an；注意 an dem 缩合为 am。⑤ mit（+三格）表伴随/一致：zufrieden mit、einverstanden mit、versöhnt mit。⑥ '
             '易错点：überzeugt von 不要说成 überzeugt über；interessiert an 不要混成 interessiert '
             'für；ärgerlich 既可接 auf 也可接 über，含义侧重不同。⑦ '
             '记忆技巧：按介词（von/auf/an/mit）归类成表记忆，而不是按形容词字母顺序背；多为 sein + 形容词 + 介词的表语结构。\n'
             '\n'
             '🇬🇧 英语对照：英语 proud of/interested in；德语 stolz auf/interessiert an，介词逐个死记，按介词归类。',
  'table': [['搭配', '中文'],
            ['stolz / böse / wütend + auf', '为…骄傲 / 生…的气'],
            ['glücklich / traurig + über', '对…高兴 / 难过'],
            ['interessiert + an', '对…感兴趣'],
            ['zufrieden / fertig + mit', '对…满意 / 完成'],
            ['fähig / bereit + zu', '有能力… / 准备好…'],
            ['neugierig + auf', '对…好奇'],
            ['begeistert / enttäuscht + von', '为…着迷 / 失望']],
  'examples': [['Das ist von den Umständen abhängig.', '这取决于情况。'],
               ['Ich bin davon überzeugt, dass er der Täter ist.', '我确信他就是凶手。（überzeugt von）'],
               ['Er ist sehr stolz auf seine Tochter.', '他为女儿感到骄傲。（stolz auf）'],
               ['Ich bin mit seiner Antwort nicht zufrieden.', '我对他的回答不满意。（zufrieden mit）']]},
 {'num': 'M21-17',
  'id': 'wetter_sprache',
  'cat': 'vokabel',
  'title': '天气与语言',
  'titleDe': 'Das Wetter und die Sprachen',
  'explain': '主题词汇：天气与语言（Das Wetter und die Sprachen）。① 本课实际包含两大主题六个词汇段：天气（天气预报用语、天气与健康）+ '
             '语言（语言变化、语言学习、非语言交际）。② 天气预报表达高度固定：温度用 liegen bei/steigen auf/sinken auf，高低压用 das '
             'Hoch/das Tief，降水按强度分为 '
             'Schauer（阵雨）/Regen（雨）/Schneefall（降雪）/Gewitter（雷暴）/Unwetter（恶劣天气）。③ 固定搭配记忆：der Nebel '
             'löst sich auf（雾散）、in Strömen regnen（倾盆大雨）、mit Unwetter ist zu rechnen（预计有恶劣天气）。④ '
             '"天气与健康"段引入 Wetterfühligkeit（天气敏感）等 C1 话题词，适合口语和写作中谈论健康与环境话题。⑤ "语言"段核心词 '
             'Anglisierung（英语化）、Verkehrssprache（通用语）、Sprachbarrieren（语言障碍），可用于讨论语言政策、英语影响类议论文。⑥ '
             '非语言交际三词辨析：Körpersprache（身体语言，总称）/ Mimik（面部表情）/ Gestik（手势），写作描述人物时常用。⑦ 易错：die '
             'Wettervorhersage 是阴性；der Schauer（阵雨）不要与作"恐怖"解的 Schauer 混淆；Tiefsttemperatur 注意复数形式 '
             'Tiefsttemperaturen。⑧ 记忆技巧：按"预报—现象—健康"和"语言—学习—交际"两条线分组记；动词多与名词固定搭配出现，背搭配不背孤词。\n'
             '\n'
             '🇬🇧 英语对照：英语 weather forecast；德语 die Wettervorhersage，预报用语高度固定，整句背。',
  'table': [['主题', '德语', '中文'],
            ['天气预报用语', 'die Höchst-/Tiefsttemperatur', '最高/最低气温'],
            ['天气预报用语', 'steigen / sinken', '上升/下降'],
            ['天气预报用语', 'das Hoch / das Tief', '高压/低压'],
            ['天气预报用语', 'die Aufheiterung', '放晴'],
            ['天气预报用语', 'bewölkt', '多云'],
            ['天气预报用语', 'der Schauer', '阵雨'],
            ['天气预报用语', 'der Niederschlag', '降水'],
            ['天气预报用语', 'niederschlagsfrei', '无降水'],
            ['天气预报用语', 'der Schnee', '雪'],
            ['天气预报用语', 'der Schneefall', '降雪'],
            ['天气预报用语', 'der Nebel', '雾'],
            ['天气预报用语', 'das Nebelfeld', '雾区'],
            ['天气预报用语', 'der Wind', '风'],
            ['天气预报用语', 'die Sturmböe', '强阵风'],
            ['天气预报用语', 'das Unwetter', '恶劣天气'],
            ['天气预报用语', 'das Gewitter', '雷暴'],
            ['天气预报用语', 'der Regen', '雨'],
            ['天气预报用语', 'in Strömen regnen', '倾盆大雨'],
            ['天气预报用语', 'der Donner', '雷声'],
            ['天气预报用语', 'donnern', '打雷'],
            ['天气预报用语', 'der Blitz', '闪电'],
            ['天气预报用语', 'der Blitzeinschlag', '雷击'],
            ['天气预报用语', 'blitzen', '闪电划过'],
            ['天气预报', 'die Wettervorhersage', '天气预报'],
            ['天气预报', 'die Wetteraussicht', '天气展望'],
            ['天气预报', 'das Wetterphänomen', '天气现象'],
            ['天气预报', 'der Wetterverlauf', '天气过程'],
            ['天气预报', 'die Bauernregel', '农谚'],
            ['天气预报', 'die Überlieferung', '流传'],
            ['天气预报', 'das Stationsnetz', '观测站网'],
            ['天气预报', 'die Wetterbeobachtung', '气象观测'],
            ['天气预报', 'vereinheitlichen', '统一'],
            ['天气预报', 'analysieren', '分析'],
            ['天气预报', 'der Wetterdienst', '气象服务'],
            ['天气预报', 'die Treffsicherheit', '准确度'],
            ['天气预报', 'zuverlässig', '可靠的'],
            ['天气与健康', 'die Wetterfühligkeit', '天气敏感'],
            ['天气与健康', 'wetterfühlig', '对天气敏感的'],
            ['天气与健康', 'das Wohlbefinden', '健康幸福感'],
            ['天气与健康', 'beeinflussen', '影响'],
            ['天气与健康', 'das Krankheitssymptom', '疾病症状'],
            ['天气与健康', 'einer Tätigkeit nachgehen', '从事某项活动'],
            ['天气与健康', 'klagen', '抱怨'],
            ['天气与健康', 'der Schmerz', '疼痛'],
            ['天气与健康', 'die Beschwerde', '不适'],
            ['天气与健康', 'hervorrufen', '引起'],
            ['天气与健康', 'das Leiden', '痛苦'],
            ['天气与健康', 'die Wetterlage', '天气形势'],
            ['天气与健康', 'die Hitze', '炎热'],
            ['天气与健康', 'die UV-Strahlung', '紫外线辐射'],
            ['天气与健康', 'das Hautkrebsrisiko', '皮肤癌风险'],
            ['天气与健康', 'die Warnung', '警告'],
            ['天气与健康', 'der Meteorologe', '气象学家'],
            ['天气与健康', 'subjektiv', '主观的'],
            ['天气与健康', 'die Einschätzung', '评估'],
            ['语言英语化', 'sich vollziehen', '发生'],
            ['语言英语化', 'die Ausdrucksweise', '表达方式'],
            ['语言英语化', 'das Forschungsergebnis', '研究成果'],
            ['语言英语化', 'veröffentlichen', '发表'],
            ['语言英语化', 'die Welthilfssprache', '世界辅助语言'],
            ['语言英语化', 'heranwachsen', '发展成为'],
            ['语言英语化', 'die Sprachbarriere', '语言障碍'],
            ['语言英语化', 'aus dem Weg räumen', '消除'],
            ['语言英语化', 'die Verkehrssprache', '通用语'],
            ['语言英语化', 'der Widerstand', '抵制'],
            ['语言英语化', 'die Landessprache', '本国语言'],
            ['语言英语化', 'das Verständigungsmittel', '交际工具'],
            ['语言英语化', 'sich entfremden', '疏远'],
            ['学语言', 'erlernen', '学会'],
            ['学语言', 'verlernen', '遗忘'],
            ['学语言', 'nachschlagen', '查阅'],
            ['学语言', 'übersetzen', '翻译'],
            ['学语言', 'umschreiben', '释义'],
            ['学语言', 'der Kontext', '语境'],
            ['学语言', 'festigen', '巩固'],
            ['学语言', 'der Lernstoff', '学习材料'],
            ['学语言', 'erfassen', '掌握'],
            ['学语言', 'das Gehirn', '大脑'],
            ['学语言', 'stimulieren', '刺激'],
            ['学语言', 'der Lerntyp', '学习类型'],
            ['学语言', 'der Biorhythmus', '生物节律'],
            ['学语言', 'die Gelegenheit', '机会'],
            ['学语言', 'nutzen', '利用'],
            ['非语言交际', 'die Körpersprache', '肢体语言'],
            ['非语言交际', 'die Mimik', '面部表情'],
            ['非语言交际', 'der Gesichtsausdruck', '面部表情'],
            ['非语言交际', 'die Gestik', '手势'],
            ['非语言交际', 'die Körperhaltung', '姿态'],
            ['非语言交际', 'die Körperbewegung', '身体动作'],
            ['非语言交际', 'unbewusst', '无意识地'],
            ['非语言交际', 'die Botschaft', '信息'],
            ['非语言交际', 'verraten', '透露'],
            ['非语言交际', 'seelisch', '心理的'],
            ['非语言交际', 'die Aufmerksamkeit', '注意'],
            ['非语言交际', 'signalisieren', '发出信号'],
            ['非语言交际', 'kontrollieren', '控制'],
            ['非语言交际', 'der Gefühlszustand', '情绪状态'],
            ['非语言交际', 'zum Ausdruck bringen', '表达']],
  'examples': [['Die Höchsttemperaturen liegen bei 30 Grad.', '最高温度 30 度。'],
               ['Es gibt einige Schauer.', '有一些阵雨。'],
               ['Der Nebel löst sich auf.', '雾散了。'],
               ['sich mit der Bedeutung der Körpersprache beschäftigen', '研究肢体语言的意义。']]},
 {'num': 'M22-18',
  'id': 'glueck_gefuehle',
  'cat': 'vokabel',
  'title': '幸福与其他情感',
  'titleDe': 'Glück und andere Gefühle',
  'explain': '主题词汇：幸福与其他情感（Glück und andere Gefühle）。① 本课围绕"幸福"与"情感"分 4 '
             '段：幸福与不幸、压力、笑与幽默、愚人节玩笑，情绪话题词汇密集。② 幸福研究类多为 Glück- '
             '复合名词：Glücksfähigkeit（幸福能力）、Glücksniveau（幸福水平）、Glücksempfinden、Zufriedenheitsgefühl，适合 '
             'C1 写作论述"幸福"话题，可成组记忆。③ 压力段是职场话题核心表达：unter Stress leiden（承受压力）、die Psyche wird '
             'belastet/entlastet、die Gratifikationskrise（付出—回报危机），以及 Anspruch und Wirklichkeit '
             'klaffen auseinander（期望与现实脱节）。④ 幽默段口语表达丰富：sich totlachen（笑死）、Witze reißen（讲笑话）、mit '
             'etwas ist nicht zu spaßen（某事开不得玩笑）；近义词 Spaßvogel/Witzbold/Scherzkeks/Ulknudel '
             '都是"爱开玩笑的人"。⑤ 愚人节段是文化词汇：Aprilscherz、jemanden in den April schicken（和某人开愚人节玩笑）、hinters '
             'Licht führen（欺骗），了解德国 4 月 1 日习俗。⑥ 易错：Glück 一词多义（幸福/运气），die Glücksfähigkeit '
             '指"获得幸福的能力"；schadenfroh（幸灾乐祸的）是形容词；der Stress 为阳性。⑦ 记忆技巧：Glück- '
             '复合词家族一起记；压力段按"压力源—身心反应—应对"链条记（Anforderungen steigen → Psyche wird belastet → Balance '
             'finden）。\n'
             '\n'
             '🇬🇧 英语对照：英语 happiness；德语 das Glück（幸福/运气），Glück- 复合词家族成组背。',
  'table': [['主题', '德语', '中文'],
            ['幸福与不幸', 'sich Gedanken machen', '思考'],
            ['幸福与不幸', 'empirisch', '经验的'],
            ['幸福与不幸', 'die Untersuchung', '研究'],
            ['幸福与不幸', 'die Frohnatur', '乐天派'],
            ['幸福与不幸', 'die Stimmung', '情绪'],
            ['幸福与不幸', 'die Glücksfähigkeit', '感受幸福的能力'],
            ['幸福与不幸', 'angeboren', '天生的'],
            ['幸福与不幸', 'das Glücksniveau', '幸福水平'],
            ['幸福与不幸', 'die Zufriedenheit', '满意'],
            ['幸福与不幸', 'der Wohlstand', '富足'],
            ['幸福与不幸', 'Jeder ist seines Glückes Schmied', '每个人都是自己幸福的创造者（谚语）'],
            ['幸福与不幸', 'der Lebensumstand', '生活状况'],
            ['幸福与不幸', 'abhängen (von)', '取决于'],
            ['幸福与不幸', 'sich gewöhnen (an)', '习惯'],
            ['幸福与不幸', 'der Pechvogel', '倒霉鬼'],
            ['幸福与不幸', 'unglücklich', '不幸的'],
            ['幸福与不幸', 'die Emotion', '情绪'],
            ['幸福与不幸', 'in den Griff bekommen', '控制'],
            ['幸福与不幸', 'die Angst', '害怕'],
            ['幸福与不幸', 'die Enttäuschung', '失望'],
            ['幸福与不幸', 'erleben', '经历'],
            ['幸福与不幸', 'die Vergangenheit', '过去'],
            ['压力', 'stressig', '有压力的'],
            ['压力', 'leiden (unter)', '遭受'],
            ['压力', 'der Überlebensreflex', '生存反射'],
            ['压力', 'die Hilflosigkeit', '无助'],
            ['压力', 'belasten / entlasten', '负担/减负'],
            ['压力', 'die Anforderung', '要求'],
            ['压力', 'die Karriere', '事业'],
            ['压力', 'das Erfolgserlebnis', '成功体验'],
            ['压力', 'der Anspruch', '期望'],
            ['压力', 'die Wirklichkeit', '现实'],
            ['压力', 'sich identifizieren (mit)', '认同'],
            ['压力', 'die Belohnungschance', '回报机会'],
            ['压力', 'die Gratifikationskrise', '奖酬危机'],
            ['压力', 'die Wertschätzung', '尊重'],
            ['压力', 'die Anerkennung', '表彰'],
            ['压力', 'die Motivation', '动力'],
            ['压力', 'die Balance', '平衡'],
            ['压力', 'die Priorität', '优先事项'],
            ['压力', 'die Stärke', '优势'],
            ['笑与幽默', 'lachen', '笑'],
            ['笑与幽默', 'lustig / amüsant', '有趣的'],
            ['笑与幽默', 'sich krummlachen', '笑弯腰'],
            ['笑与幽默', 'sich totlachen', '笑死了'],
            ['笑与幽默', 'sich ausschütten (vor Lachen)', '爆笑'],
            ['笑与幽默', 'der Humor', '幽默'],
            ['笑与幽默', 'der Witz', '笑话'],
            ['笑与幽默', 'Witze erzählen / reißen', '讲笑话'],
            ['笑与幽默', 'mit etwas ist nicht zu spaßen', '某事开不得玩笑'],
            ['笑与幽默', 'die Gesundheit', '健康'],
            ['笑与幽默', 'die soziale Beziehung', '社会关系'],
            ['愚人节玩笑', 'in den April schicken', '开愚人节玩笑'],
            ['愚人节玩笑', 'auf den Arm nehmen', '捉弄'],
            ['愚人节玩笑', 'hinters Licht führen', '欺骗'],
            ['愚人节玩笑', 'hereinlegen', '欺骗'],
            ['愚人节玩笑', 'der Scherz', '玩笑'],
            ['愚人节玩笑', 'der Streich', '恶作剧'],
            ['愚人节玩笑', 'veralbern / verspotten / auslachen', '愚弄/嘲笑'],
            ['愚人节玩笑', 'schadenfroh', '幸灾乐祸'],
            ['愚人节玩笑', 'der Brauch', '习俗']],
  'examples': [['Die Glücksfähigkeit ist zum Teil angeboren.', '幸福能力在一定程度上是天生的。'],
               ['unter Stress leiden', '承受压力。'],
               ['sich totlachen', '笑死。'],
               ['Aprilscherze sind seit dem 16. Jahrhundert verbürgt.', '愚人节恶作剧从 16 世纪起就有记载。']]},
 {'num': 'M23-19',
  'id': 'erfolg_niederlage',
  'cat': 'vokabel',
  'title': '成功与失败',
  'titleDe': 'Erfolge und Niederlagen',
  'explain': '主题词汇：成功与失败（Erfolge und Niederlagen）。① 本课 4 '
             '段：体育中的成功、职业成功、公司介绍、失败的艺术，"成功与失败"正反两面都覆盖，适合议论文正反论证。② 体育成功表达：den Titel '
             'holen/erringen（夺得头衔）、den ersten Platz belegen（获得第一名）；兴奋剂话题链 '
             'Doping—Dopingkontrolle—disqualifiziert（取消资格）。③ 职业成功关键词：Erfolg im Beruf、die '
             'Sozialkompetenz（社交能力）、die Teamfähigkeit（团队能力）、Chancen suchen und '
             'ergreifen（寻找并抓住机会），求职与面试话题高频词。④ "失败的艺术"是本课特色段：Misserfolge erleiden（遭受失败）、ein Traum '
             'zerplatzt（梦想破灭）、das Projekt in den Sand setzen（把项目搞砸），学习积极、得体地谈论失败的表达。⑤ 固定搭配：die '
             'Verantwortung (anderen) in die Schuhe schieben（推卸责任给他人）、den Sport an den Nagel '
             'hängen（告别体坛，字面"把运动挂在钉子上"）。⑥ 易错：der Erfolg（成功）vs das '
             'Ergebnis（结果）；scheitern（失败）是不及物动词（das Projekt ist gescheitert）；die '
             'Niederlage（战败/失败）vs der Misserfolg（不成功）。⑦ 记忆技巧：按"成功三段 + 失败一段"结构记；失败段重点记动词搭配 '
             'erleiden/versagen/misslingen/missglücken 的区别。\n'
             '\n'
             '🇬🇧 英语对照：英语 success/failure；德语 der Erfolg/die Niederlage，失败段学"得体地谈失败"。',
  'table': [['主题', '德语', '中文'],
            ['体育成功', 'teilnehmen (an)', '参加'],
            ['体育成功', 'gewinnen', '赢得'],
            ['体育成功', 'der Meister / die Meisterin', '冠军'],
            ['体育成功', 'der Titel', '头衔'],
            ['体育成功', 'der Profi', '职业（选手）'],
            ['体育成功', 'der Amateur', '业余（选手）'],
            ['体育成功', 'die Silbermedaille', '银牌'],
            ['体育成功', 'der Erfolgsdruck', '成功压力'],
            ['体育成功', 'olympisch', '奥林匹克的'],
            ['体育成功', 'das Dabeisein', '参与'],
            ['体育成功', 'die Leistungsfähigkeit', '运动能力'],
            ['体育成功', 'steigern', '提高'],
            ['体育成功', 'das Aufputschmittel', '兴奋剂'],
            ['体育成功', 'die Nebenwirkung', '副作用'],
            ['体育成功', 'die Dopingkontrolle', '兴奋剂检测'],
            ['体育成功', 'disqualifizieren', '取消资格'],
            ['体育成功', 'an den Nagel hängen', '放弃（习语）'],
            ['体育成功', 'die Karriere beenden', '结束职业生涯'],
            ['职业成功', 'Karriere machen', '创事业'],
            ['职业成功', 'die Abschlussnote', '毕业成绩'],
            ['职业成功', 'aussagekräftig', '有说服力的'],
            ['职业成功', 'die Sozialkompetenz', '社交能力'],
            ['职业成功', 'die Teamfähigkeit', '团队能力'],
            ['职业成功', 'besitzen', '具备'],
            ['职业成功', 'gefragt', '受欢迎的'],
            ['职业成功', 'durchschauen', '看透'],
            ['职业成功', 'der Stellenantritt', '入职'],
            ['职业成功', 'die Zielvereinbarung', '目标协议'],
            ['职业成功', 'sich zurückhalten', '克制'],
            ['职业成功', 'der Besserwisser', '万事通'],
            ['职业成功', 'lästern', '说坏话'],
            ['职业成功', 'der Arbeitgeber', '雇主'],
            ['职业成功', 'die Chance ergreifen', '抓住机会'],
            ['职业成功', 'das Hindernis', '障碍'],
            ['职业成功', 'überwinden', '克服'],
            ['职业成功', 'das Risiko eingehen', '承担风险'],
            ['职业成功', 'sich orientieren', '定位'],
            ['公司介绍', 'weltweit führend', '世界领先'],
            ['公司介绍', 'das Unternehmen', '公司'],
            ['公司介绍', 'das Produkt', '产品'],
            ['公司介绍', 'entwickeln', '开发'],
            ['公司介绍', 'herstellen', '生产'],
            ['公司介绍', 'maßgeschneidert', '定制的'],
            ['公司介绍', 'die Dienstleistung', '服务'],
            ['公司介绍', 'die Lösung', '解决方案'],
            ['公司介绍', 'anbieten', '提供'],
            ['公司介绍', 'innovativ', '创新的'],
            ['公司介绍', 'die Technik', '技术'],
            ['公司介绍', 'das Know-how', '专业知识'],
            ['公司介绍', 'der Mitarbeiter', '员工'],
            ['公司介绍', 'der Wettbewerbsvorteil', '竞争优势'],
            ['公司介绍', 'die Verantwortung übernehmen', '承担责任'],
            ['公司介绍', 'der Aktionär', '股东'],
            ['失败的艺术', 'der Misserfolg', '失败'],
            ['失败的艺术', 'scheitern', '失败'],
            ['失败的艺术', 'versagen', '失败'],
            ['失败的艺术', 'der Versager', '失败者'],
            ['失败的艺术', 'in den Sand setzen', '搞砸'],
            ['失败的艺术', 'der Traum zerplatzt', '梦想破灭'],
            ['失败的艺术', 'aus Misserfolgen lernen', '从失败中学习'],
            ['失败的艺术', 'die Niederlage', '失败'],
            ['失败的艺术', 'mit Niederlagen umgehen', '应对失败'],
            ['失败的艺术', 'der Umgang', '应对']],
  'examples': [['den Titel holen / erringen', '夺得冠军头衔。'],
               ['Dopingkontrollen durchführen', '进行兴奋剂检查。'],
               ['Chancen suchen und ergreifen', '寻找并抓住机会。'],
               ['ein Traum zerplatzt', '梦想破灭。']]},
 {'num': 'M24-27',
  'id': 'fortschritt_umwelt',
  'cat': 'vokabel',
  'title': '进步与环境',
  'titleDe': 'Fortschritt und Umwelt',
  'explain': '主题词汇：进步与环境（Fortschritt und Umwelt）。① 本课 6 '
             '段：进步、新媒体、语言变化、环境、水资源，主题是"进步"与"环境"的辩证关系，议论文素材丰富。② 进步段讨论科技利弊：Lebenserwartung '
             'steigt（寿命延长）vs im Stau stehen（堵车）、Annehmlichkeiten（便利），适合"科技进步利弊"类写作正反论述。③ '
             '新媒体段聚焦隐私：die Privatsphäre gegen Bequemlichkeit eintauschen（为了便利交换隐私）、digitale Spuren '
             'hinterlassen（留下数字足迹）、der Datenschutz，是 C1 写作互联网话题的高频词。④ '
             '语言变化段：chatten/bloggen/mailen/googeln 等英语借词动词化，auf die Großschreibung '
             'verzichten（放弃大写）反映网络语言特点。⑤ 环境段核心词链：Klimawandel/globale Erwärmung（气候变化）— '
             'Treibhausgase werden ausgestoßen（温室气体排放）— '
             'Pro-Kopf-Emissionen（人均排放）；水资源段：Wasserknappheit、Dürre、Flüsse versickern（河流干涸）。⑥ '
             '易错：der Klimawandel（阳性）、die Dürre（阴性）、das Treibhausgas（中性复合词）；der Stau（堵车）不要与 der '
             'Staub（灰尘）混淆。⑦ 记忆技巧：按"进步—代价"链条记（Stau、Privatsphäre 换取 '
             'Lebenserwartung、Annehmlichkeiten）；环境段按"原因—现象—对策"记（Emissionen—Erwärmung—Aufklärungsarbeit）。\n'
             '\n'
             '🇬🇧 英语对照：英语 climate change；德语 der Klimawandel，"进步—代价"链条背议论文素材。',
  'table': [['主题', '德语', '中文'],
            ['进步', 'meistern', '克服'],
            ['进步', 'die Geschwindigkeit', '速度'],
            ['进步', 'jährlich', '每年'],
            ['进步', 'der Stau', '拥堵'],
            ['进步', 'die Parkplatzsuche', '找车位'],
            ['进步', 'die Lebenserwartung', '预期寿命'],
            ['进步', 'die Lebensqualität', '生活质量'],
            ['进步', 'abhängen (von)', '取决于'],
            ['进步', 'sogenannt', '所谓的'],
            ['新媒体', 'abrufen', '获取'],
            ['新媒体', 'die Suchmaschine', '搜索引擎'],
            ['新媒体', 'digital', '数字的'],
            ['新媒体', 'die Spur hinterlassen', '留下痕迹'],
            ['新媒体', 'die Privatsphäre', '隐私'],
            ['新媒体', 'der Datenschutz', '数据保护'],
            ['新媒体', 'das Urheberrecht', '版权'],
            ['新媒体', 'die Suchanfrage', '搜索请求'],
            ['新媒体', 'durchsuchen', '搜遍'],
            ['新媒体', 'der Datenverkehr', '数据流量'],
            ['新媒体', 'analysieren', '分析'],
            ['新媒体', 'digitalisieren', '数字化'],
            ['新媒体', 'die Anzeige platzieren', '投放广告'],
            ['新媒体', 'zur Verfügung stellen', '提供'],
            ['新媒体', 'warnen (vor)', '警告'],
            ['新媒体', 'das Risiko bergen', '带来风险'],
            ['新媒体', 'unaufhaltsam', '不可阻挡的'],
            ['新媒体', 'der Aufstieg', '上升'],
            ['语言变化', 'chatten / bloggen / mailen / googeln', '聊天/写博客/发邮件/谷歌'],
            ['语言变化', 'der Verfall', '衰落'],
            ['语言变化', 'der Tippfehler', '打字错误'],
            ['语言变化', 'sich häufen', '增加'],
            ['语言变化', 'die Großschreibung', '大写'],
            ['语言变化', 'verzichten (auf)', '放弃'],
            ['语言变化', 'das Emoticon', '表情符号'],
            ['语言变化', 'ausdrücken', '表达'],
            ['语言变化', 'die Rechtschreibung', '拼写'],
            ['语言变化', 'der Satzbau', '句法'],
            ['语言变化', 'der Wortschatz', '词汇'],
            ['环境与气候', 'die globale Erwärmung', '全球变暖'],
            ['环境与气候', 'der Klimawandel', '气候变化'],
            ['环境与气候', 'die Gefahr', '危险'],
            ['环境与气候', 'das Bewusstsein', '意识'],
            ['环境与气候', 'das Treibhausgas', '温室气体'],
            ['环境与气候', 'ausstoßen', '排放'],
            ['环境与气候', 'die Pro-Kopf-Emission', '人均排放'],
            ['环境与气候', 'der Biosprit', '生物燃料'],
            ['环境与气候', 'kostspielig', '昂贵的'],
            ['环境与气候', 'der Treibhauseffekt', '温室效应'],
            ['环境与气候', 'verschlimmern', '恶化'],
            ['环境与气候', 'die Wassernachfrage', '用水需求'],
            ['环境与气候', 'sich verdoppeln', '加倍'],
            ['环境与气候', 'die Abholzung', '砍伐'],
            ['环境与气候', 'in die Flucht treiben', '驱赶'],
            ['环境与气候', 'der Lebensmittelpreis', '食品价格'],
            ['环境与气候', 'explodieren', '暴涨'],
            ['环境与气候', 'aufmerksam machen auf', '提醒注意'],
            ['水', 'prekär', '岌岌可危'],
            ['水', 'mangeln (an)', '缺乏'],
            ['水', 'die Wasserknappheit', '缺水'],
            ['水', 'knapp', '稀缺的'],
            ['水', 'das Trinkwasser', '饮用水'],
            ['水', 'der Wasserverbrauch', '用水量'],
            ['水', 'ansteigen', '上升'],
            ['水', 'das Abwasser', '废水'],
            ['水', 'das Leck', '漏洞'],
            ['水', 'ungenutzt', '未被利用的'],
            ['水', 'die Dürre', '干旱'],
            ['水', 'leiden (unter)', '遭受'],
            ['水', 'die Landwirtschaft', '农业']],
  'examples': [['Die Lebenserwartung steigt.', '预期寿命在上升。'],
               ['Der Klimawandel schreitet voran.', '气候变化正在加剧。'],
               ['Treibhausgase werden ausgestoßen.', '温室气体被排放。'],
               ['jährlich viele Stunden im Stau verbringen', '每年花很多小时堵在路上。']]}]


def main():
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'kurs', 'c1')
    os.makedirs(out_dir, exist_ok=True)
    data = []
    for p in GRAMMAR_POINTS:
        data.append({
            'num': p['num'], 'id': p['id'], 'cat': p['cat'],
            'title': p['title'], 'titleDe': p['titleDe'],
            'explain': p['explain'], 'table': p.get('table', []),
            'examples': [list(e) for e in p['examples']],
        })
    out = os.path.join(out_dir, 'grammar_c1.json')
    with open(out, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
    print(f'wrote {out} ({len(data)} points)')

if __name__ == '__main__':
    main()
