# 德语语法学习页内容（A1-B2，每个语法点配例句）
GRAMMAR_POINTS = [
# ============ A1 ============
{'level': 'A1', 'id': 'verb_konjugation', 'title': '动词变位', 'titleDe': 'Verbkonjugation',
 'explain': '德语动词要根据人称变位。规则动词去 -en 加词尾；不规则动词元音会变化（如 e→i, e→ie, a→ä）。',
 'table': [['人称', 'machen（规则）', 'sprechen（e→i）', 'sehen（e→ie）', 'fahren（a→ä）'],
           ['ich', 'mache', 'spreche', 'sehe', 'fahre'],
           ['du', 'machst', 'sprichst', 'siehst', 'fährst'],
           ['er/sie/es', 'macht', 'spricht', 'sieht', 'fährt'],
           ['wir', 'machen', 'sprechen', 'sehen', 'fahren'],
           ['ihr', 'macht', 'sprecht', 'seht', 'fahrt'],
           ['sie/Sie', 'machen', 'sprechen', 'sehen', 'fahren']],
 'examples': [
     ('Ich mache meine Hausaufgaben.', '我在做作业。'),
     ('Du sprichst gut Deutsch.', '你德语说得很好。'),
     ('Er sieht einen Film.', '他在看电影。'),
     ('Sie fährt nach Berlin.', '她开车去柏林。'),
 ]},
{'level': 'A1', 'id': 'artikel', 'title': '冠词：der / die / das', 'titleDe': 'Artikel',
 'explain': '德语名词有三种性：阳性 der、阴性 die、中性 das。复数统一用 die。性没有绝对规则，要和单词一起背。',
 'table': [['', '阳性', '阴性', '中性'],
           ['定冠词', 'der Mann', 'die Frau', 'das Kind'],
           ['不定冠词', 'ein Mann', 'eine Frau', 'ein Kind'],
           ['复数', 'die Männer', 'die Frauen', 'die Kinder']],
 'examples': [
     ('Der Mann trinkt Kaffee.', '那个男人在喝咖啡。'),
     ('Die Frau liest ein Buch.', '那个女人在读书。'),
     ('Das Kind spielt im Garten.', '孩子在花园里玩。'),
     ('Die Kinder sind müde.', '孩子们累了。'),
 ]},
{'level': 'A1', 'id': 'akkusativ', 'title': '第四格 Akkusativ', 'titleDe': 'Akkusativ',
 'explain': '直接宾语用第四格。只有阳性单数冠词变化：der→den, ein→einen。动词后跟"谁/什么"就是四格。',
 'table': [['格', '阳性', '阴性', '中性', '复数'],
           ['一格', 'der', 'die', 'das', 'die'],
           ['四格', 'den', 'die', 'das', 'die']],
 'examples': [
     ('Ich sehe den Mann.', '我看见那个男人。'),
     ('Sie kauft einen Apfel.', '她买一个苹果。'),
     ('Wir lieben das Wetter.', '我们喜欢这天气。'),
     ('Er besucht die Freunde.', '他拜访朋友们。'),
 ]},
{'level': 'A1', 'id': 'negation', 'title': '否定：nicht / kein', 'titleDe': 'Negation',
 'explain': 'kein 否定名词（=没有），nicht 否定动词/形容词/整个句子。kein 要变格，和 ein 一样。',
 'table': [['', 'kein（名词）', 'nicht（其他）'],
           ['例', 'kein Geld（没有钱）', 'nicht gut（不好）']],
 'examples': [
     ('Ich habe kein Auto.', '我没有车。'),
     ('Das ist keine Frage.', '这不是问题。'),
     ('Ich komme nicht.', '我不来。'),
     ('Der Film ist nicht interessant.', '这电影没意思。'),
 ]},
{'level': 'A1', 'id': 'fragen', 'title': '疑问句', 'titleDe': 'Fragen',
 'explain': '是非疑问句动词放句首；特殊疑问句疑问词放句首、动词第二位。',
 'table': [['类型', '结构', '例子']],
 'examples': [
     ('Kommst du mit?', '你一起来吗？'),
     ('Wo wohnst du?', '你住在哪？'),
     ('Was machst du?', '你在做什么？'),
     ('Wie heißt du?', '你叫什么名字？'),
 ]},
{'level': 'A1', 'id': 'modalverben', 'title': '情态动词', 'titleDe': 'Modalverben',
 'explain': 'können（能）、müssen（必须）、wollen（想要）、dürfen（可以）、sollen（应该）、mögen（喜欢）。情态动词变位不规则，句中主要动词用原形放句末。',
 'table': [['', 'können', 'müssen', 'wollen'],
           ['ich', 'kann', 'muss', 'will'],
           ['du', 'kannst', 'musst', 'willst'],
           ['er', 'kann', 'muss', 'will']],
 'examples': [
     ('Ich kann Deutsch sprechen.', '我会说德语。'),
     ('Du musst mir helfen.', '你必须帮我。'),
     ('Wir wollen nach Hause gehen.', '我们想回家。'),
     ('Darf ich hier rauchen?', '我可以在这抽烟吗？'),
 ]},
{'level': 'A1', 'id': 'trennbar', 'title': '可分动词', 'titleDe': 'Trennbare Verben',
 'explain': '前缀可分：陈述句中前缀分开、放句末；从句和不定式中不分开。',
 'table': [['', '陈述句', '从句'],
           ['ankommen', 'Ich komme an.', '…, weil ich ankomme.']],
 'examples': [
     ('Der Zug kommt um 8 Uhr an.', '火车8点到达。'),
     ('Mach bitte das Licht an!', '请开灯！'),
     ('Ruf mich später an.', '晚点给我打电话。'),
     ('Sie steht früh auf.', '她起得很早。'),
 ]},
{'level': 'A1', 'id': 'perfekt', 'title': '现在完成时 Perfekt', 'titleDe': 'Perfekt',
 'explain': '口语过去时：haben/sein + 过去分词。表位移的动词用 sein，其他多用 haben。',
 'table': [['', 'haben', 'sein'],
           ['结构', 'ich habe gemacht', 'ich bin gegangen']],
 'examples': [
     ('Ich habe gestern viel gearbeitet.', '我昨天工作了很多。'),
     ('Sie ist nach Berlin gefahren.', '她开车去了柏林。'),
     ('Wir haben einen Film gesehen.', '我们看了一部电影。'),
     ('Bist du schon aufgestanden?', '你起床了吗？'),
 ]},
# ============ A2 ============
{'level': 'A2', 'id': 'dativ', 'title': '第三格 Dativ', 'titleDe': 'Dativ',
 'explain': '间接宾语用第三格。冠词变化：der→dem, die→der, das→dem, die(复数)→den + n。',
 'table': [['格', '阳性', '阴性', '中性', '复数'],
           ['一格', 'der', 'die', 'das', 'die'],
           ['三格', 'dem', 'der', 'dem', 'den + n']],
 'examples': [
     ('Ich helfe dem Mann.', '我帮助那个男人。'),
     ('Sie gibt der Frau ein Buch.', '她给那个女人一本书。'),
     ('Das gehört mir.', '那属于我。'),
     ('Er antwortet den Kindern.', '他回答孩子们。'),
 ]},
{'level': 'A2', 'id': 'wechsel', 'title': '双向介词', 'titleDe': 'Wechselpräpositionen',
 'explain': 'an, auf, hinter, in, neben, über, unter, vor, zwischen：表示静态位置跟三格，表示方向移动跟四格。',
 'table': [['介词', '三格（位置）', '四格（方向）'],
           ['in', 'in der Stadt（在城里）', 'in die Stadt（进城）'],
           ['auf', 'auf dem Tisch（在桌上）', 'auf den Tisch（放到桌上）']],
 'examples': [
     ('Das Buch liegt auf dem Tisch.', '书在桌上。（位置）'),
     ('Ich lege das Buch auf den Tisch.', '我把书放到桌上。（方向）'),
     ('Sie ist in der Schule.', '她在学校。（位置）'),
     ('Er geht in die Schule.', '他去上学。（方向）'),
 ]},
{'level': 'A2', 'id': 'praeteritum', 'title': '过去时 Präteritum', 'titleDe': 'Präteritum',
 'explain': '书面过去时。规则动词：词干+te；不规则动词要背（如 gehen→ging）。口语多用 Perfekt，书面多用 Präteritum。',
 'table': [['', 'machen（规则）', 'gehen（不规则）', 'haben', 'sein'],
           ['ich', 'machte', 'ging', 'hatte', 'war'],
           ['er', 'machte', 'ging', 'hatte', 'war']],
 'examples': [
     ('Er ging gestern ins Kino.', '他昨天去看了电影。'),
     ('Sie hatte keine Zeit.', '她没有时间。'),
     ('Wir waren sehr müde.', '我们很累。'),
     ('Ich machte meine Hausaufgaben.', '我做了作业。'),
 ]},
{'level': 'A2', 'id': 'nebensatz', 'title': '从句与连词', 'titleDe': 'Nebensätze',
 'explain': 'weil（因为）、dass（…）、wenn（如果/当…时）、als（当…时，过去一次性）：从句中动词放句末。',
 'table': [['连词', '含义', '动词位置'],
           ['weil', '因为', '句末'],
           ['dass', '…（宾语从句）', '句末'],
           ['wenn', '如果；每当', '句末']],
 'examples': [
     ('Ich bleibe zu Hause, weil ich krank bin.', '我待在家里，因为我病了。'),
     ('Er sagt, dass er keine Zeit hat.', '他说他没时间。'),
     ('Wenn es regnet, bleiben wir zu Hause.', '如果下雨，我们就待在家里。'),
     ('Als ich ein Kind war, spielte ich Fußball.', '当我还是孩子时，我踢足球。'),
 ]},
{'level': 'A2', 'id': 'komparativ', 'title': '比较级与最高级', 'titleDe': 'Komparativ / Superlativ',
 'explain': '比较级：形容词+er + als；最高级：am + 形容词+sten。部分不规则：gut→besser→am besten, viel→mehr→am meisten。',
 'table': [['原级', '比较级', '最高级'],
           ['schnell', 'schneller', 'am schnellsten'],
           ['gut', 'besser', 'am besten']],
 'examples': [
     ('Er ist größer als ich.', '他比我高。'),
     ('Dieses Buch ist besser als das.', '这本书比那本好。'),
     ('Sie läuft am schnellsten.', '她跑得最快。'),
     ('Heute ist es kälter als gestern.', '今天比昨天冷。'),
 ]},
{'level': 'A2', 'id': 'reflexiv', 'title': '反身动词', 'titleDe': 'Reflexive Verben',
 'explain': 'sich waschen（洗）、sich freuen（高兴）、sich erinnern（记得）：反身代词和主语人称一致。',
 'table': [['人称', 'sich freuen'],
           ['ich', 'mich'],
           ['du', 'dich'],
           ['er', 'sich']],
 'examples': [
     ('Ich freue mich auf dich.', '我期待见到你。'),
     ('Er wäscht sich die Hände.', '他洗手。'),
     ('Wir erinnern uns an ihn.', '我们记得他。'),
     ('Beeil dich!', '快点！'),
 ]},
# ============ B1 ============
{'level': 'B1', 'id': 'genitiv', 'title': '第二格 Genitiv', 'titleDe': 'Genitiv',
 'explain': '表所属。阳性/中性：der→des + 词尾-(e)s；阴性/复数：die→der。口语常用 von + 三格代替。',
 'table': [['格', '阳性', '阴性', '中性'],
           ['一格', 'der', 'die', 'das'],
           ['二格', 'des + (e)s', 'der', 'des + (e)s']],
 'examples': [
     ('Das ist das Auto des Lehrers.', '这是老师的车。'),
     ('Die Farbe der Wand ist weiß.', '墙的颜色是白的。'),
     ('Wegen des Wetters bleiben wir zu Hause.', '因为天气，我们待在家里。'),
     ('Trotz der Kälte geht er spazieren.', '尽管寒冷，他还是去散步。'),
 ]},
{'level': 'B1', 'id': 'konjunktiv2', 'title': '第二虚拟式', 'titleDe': 'Konjunktiv II',
 'explain': '表假设、愿望、委婉。würde + 不定式（最常用）；haben→hätte, sein→wäre。',
 'table': [['', 'würde 形式', '特殊形式'],
           ['ich', 'würde gehen', 'hätte / wäre']],
 'examples': [
     ('Ich würde gern nach Japan reisen.', '我想去日本旅行。（愿望）'),
     ('Wenn ich Geld hätte, würde ich ein Auto kaufen.', '如果我有钱，我就买辆车。（假设）'),
     ('Könnten Sie mir helfen?', '您能帮我吗？（委婉）'),
     ('An deiner Stelle würde ich das nicht tun.', '要是我是你，我不会这么做。'),
 ]},
{'level': 'B1', 'id': 'relativsatz', 'title': '关系从句', 'titleDe': 'Relativsätze',
 'explain': 'der/die/das 作关系代词，引导定语从句，动词放句末。关系代词的格由从句中的功能决定。',
 'table': [['先行词', '关系代词（主格）'],
           ['der Mann', 'der'],
           ['die Frau', 'die'],
           ['das Kind', 'das']],
 'examples': [
     ('Der Mann, der dort steht, ist mein Lehrer.', '站在那的男人是我老师。'),
     ('Das Buch, das ich lese, ist spannend.', '我正在读的书很精彩。'),
     ('Die Frau, mit der ich gesprochen habe, ist nett.', '和我说话的女人很友好。'),
     ('Kinder, die viel lesen, lernen schnell.', '多读书的孩子学得快。'),
 ]},
{'level': 'B1', 'id': 'infinitiv_zu', 'title': '不定式 zu', 'titleDe': 'Infinitiv mit zu',
 'explain': 'versuchen zu（尝试）、beginnen zu（开始）、vergessen zu（忘记）：zu + 动词原形放句末。',
 'table': [['动词', '结构'],
           ['versuchen', 'versuchen, … zu machen']],
 'examples': [
     ('Ich versuche, Deutsch zu lernen.', '我尝试学德语。'),
     ('Er hat vergessen, mich anzurufen.', '他忘了给我打电话。'),
     ('Es ist schwer, das zu verstehen.', '这很难理解。'),
     ('Sie beginnt, das Buch zu lesen.', '她开始读书。'),
 ]},
{'level': 'B1', 'id': 'passiv', 'title': '被动态', 'titleDe': 'Passiv',
 'explain': 'werden + 过去分词。施动者用 von + 三格。',
 'table': [['时态', '结构'],
           ['现在时', 'wird gemacht'],
           ['过去时', 'wurde gemacht'],
           ['完成时', 'ist gemacht worden']],
 'examples': [
     ('Das Haus wird gebaut.', '房子正在被建造。'),
     ('Der Brief wurde gestern geschrieben.', '信是昨天写的。'),
     ('Die Fenster sind geputzt worden.', '窗户已经被擦了。'),
     ('Mir wurde geholfen.', '我得到了帮助。'),
 ]},
# ============ B2 ============
{'level': 'B2', 'id': 'konjunktiv1', 'title': '第一虚拟式（转述）', 'titleDe': 'Konjunktiv I',
 'explain': '间接引语用。er sagt, er sei krank（他说他病了）。sein 的虚拟一式：ich sei, du seiest, er sei。',
 'table': [['', 'sein', 'haben'],
           ['er', 'sei', 'habe']],
 'examples': [
     ('Er sagt, er sei krank.', '他说他病了。'),
     ('Sie meint, sie habe keine Zeit.', '她说她没时间。'),
     ('Der Sprecher erklärt, die Lage habe sich verbessert.', '发言人解释说情况已改善。'),
 ]},
{'level': 'B2', 'id': 'partizip_attr', 'title': '分词作定语', 'titleDe': 'Partizip als Attribut',
 'explain': '现在分词/过去分词可作定语，相当于缩略的关系从句，要加形容词词尾。',
 'table': [['', '例'],
           ['Partizip I', 'der lachende Mann（笑着的男人）'],
           ['Partizip II', 'das geöffnete Fenster（开着的窗）']],
 'examples': [
     ('Der weinende Junge braucht Hilfe.', '哭泣的男孩需要帮助。'),
     ('Die gestern angekommene Post liegt hier.', '昨天到的邮件在这里。'),
     ('Ein gut bezahlter Job ist schwer zu finden.', '高薪工作难找。'),
 ]},
{'level': 'B2', 'id': 'n_deklination', 'title': 'N-词尾变化', 'titleDe': 'N-Deklination',
 'explain': '部分阳性名词（多指人/动物）单数二三四格加 -n/-en：der Student→den Studenten。',
 'table': [['一格', '二/三/四格'],
           ['der Student', 'des/dem/den Studenten'],
           ['der Kollege', 'des/dem/den Kollegen']],
 'examples': [
     ('Ich sehe den Studenten.', '我看见那个学生。'),
     ('Das Buch des Kollegen ist hier.', '同事的书在这。'),
     ('Er hilft dem Jungen.', '他帮助那个男孩。'),
 ]},
{'level': 'B2', 'id': 'nominalisierung', 'title': '名词化', 'titleDe': 'Nominalisierung',
 'explain': '动词/形容词大写变名词：das Lesen（阅读）、das Gute（好的东西）。',
 'table': [['原词', '名词化'],
           ['lesen', 'das Lesen'],
           ['gut', 'das Gute']],
 'examples': [
     ('Das Lesen fällt mir schwer.', '阅读对我来说很难。'),
     ('Beim Kochen höre ich Musik.', '做饭时我听音乐。'),
     ('Das Wichtigste ist die Gesundheit.', '最重要的是健康。'),
 ]},
]
