# A1 课程整理（按站内实际模块顺序：32 个语法点 + 9 个词汇点）
# 数据源：站内课程目录+课件要点（已登录核验）；讲解与例句均为原创，不含视频内容
# 生成：python3 scripts/build_kurs_grammar.py -> a1-kurs/grammar_kurs.json
import json, os

GRAMMAR_POINTS = [
{'num': 'M01-01', 'id': 'zimu', 'cat': 'yuyin', 'title': '德语字母表', 'titleDe': 'Alphabet',
 'explain': '德语共 30 个字母：26 个拉丁字母 + ä ö ü ß。每个字母都有标准读音（如 R 读"ɛr"、Z 读"tsɛt"、ß 读"ɛs-tsɛt"）。德语没有声调，读字母时用几声都可以，不用纠结。小舌音 R 是公认难点，没有速成法，只能长期多练。\n\n🇬🇧 英语对照：英语也是 26 个字母但读音不同（如 Z 读 zi:）；德语多了 4 个特殊字母，ß 只在小写出现。',
 'table': [['字母', '读音', '备注'],
           ['Ä ä / Ö ö / Ü ü', 'ɛː / øː / yː', '变元音，a o u 的"变形"'],
           ['ß', 'ɛs-tsɛt', '只小写 = ss，如 Straße'],
           ['R r', 'ɛr', '小舌音，公认难点'],
           ['Y y', 'ypsilon', '多见于外来词']],
 'examples': [
     ('Das ABC ist nicht schwer.', '字母表不难。'),
     ('Wie schreibt man Straße?', 'Straße 怎么拼写？'),
     ('Das ß gibt es nur klein.', 'ß 只有小写形式。'),
     ('Übe das R jeden Tag!', '每天都练小舌音 R！'),
 ]},
{'num': 'M01-02~04', 'id': 'fayin', 'cat': 'yuyin', 'title': '发音规则', 'titleDe': 'Ausspracheregeln',
 'explain': '长短音判断：元音后 1 个辅音、双写元音（aa）或"元音+h"→长音；元音后 2 个以上辅音→短音。例外死记：an/am/ab/hat/das/man 是短音，nach/hoch 却是长音。ch 的规则记"a o u 后读 [x]（Bach），其余读 [ç]（ich）"，外来词读 [k]，词尾 -ig 读 [iç]。词尾浊辅音清化：b/d/g 在词尾读 [p]/[t]/[k]（lieb 读 li:p）。r：词首发 [r]，元音后或词尾发 [ɐ]。组合：sch=[ʃ]，词首 sp=[ʃp]、st=[ʃt]（只在词首！），z=[ts]，ng 的 g 不发音。双元音：ei=[ai]、au=[ao]、eu/äu=[ɔy]。\n\n🇬🇧 英语对照：英语发音例外更多，德语规则性强得多；但德语有英语没有的音：ch（ich/Bach 对立）、小舌音 r、词尾清化。',
 'table': [['规则', '例子'],
           ['长音：1辅音/aa/元音+h', 'Tag（长a）、Saal、gehen'],
           ['短音：2+辅音', 'Tanne、Kette'],
           ['ch：aou后[x]其余[ç]', 'Bach[x] / ich[ç]'],
           ['词尾清化 bdg→ptk', 'lieb→[li:p]、Tag→[ta:k]'],
           ['词首sp/st→ʃp/ʃt', 'Sport、Stadt'],
           ['双元音', 'mein[ai]、Haus[ao]、heute[ɔy]']],
 'examples': [
     ('Ich spreche Deutsch.', '我说德语。'),
     ('Die Schule beginnt um acht.', '学校八点开学。'),
     ('Mein Vater wohnt in Berlin.', '我父亲住在柏林。'),
     ('Heute ist das Wetter schön.', '今天天气很好。'),
 ]},
{'num': 'M01-05', 'id': 'artikel_nomen', 'cat': 'mingci', 'title': '冠词、名词的性与单复数', 'titleDe': 'Artikel & Nomen',
 'explain': '三性：der（阳）/die（阴）/das（中），复数冠词统一 die；不定冠词 ein/eine 没有复数。猜性技巧：90% 以 -e 结尾的是阴性，90% 以 Ge- 开头的是中性，67% 单音节是阳性，-chen 结尾一定是中性。但复数变化规则性很低（+e、变音+e、+n、+er、变音+er、外来词+s），必须和单数一起死记。名词首字母永远大写（德语只有句首和名词大写）。\n\n🇬🇧 英语对照：英语只有 the/a/an 不分性；德语冠词随性数格变化，且复数形式不规则——这是德语词汇记忆量大的主因。',
 'table': [['', '阳性', '阴性', '中性', '复数'],
           ['定冠词', 'der Mann', 'die Frau', 'das Kind', 'die Kinder'],
           ['不定冠词', 'ein Mann', 'eine Frau', 'ein Kind', '—（没有）']],
 'examples': [
     ('Der Mann trinkt Kaffee.', '那个男人在喝咖啡。'),
     ('Die Frau liest ein Buch.', '那个女人在读书。'),
     ('Das Kind spielt im Garten.', '孩子在花园里玩。'),
     ('Die Kinder sind müde.', '孩子们累了。'),
 ]},
{'num': 'M01-06', 'id': 'konjugation', 'cat': 'dongci', 'title': '人称代词和动词变位', 'titleDe': 'Personalpronomen & Konjugation',
 'explain': '8 个人称：ich、du、er/sie/es、wir、ihr、sie、Sie。注意 sie 一词四义（她/他们/她们/它们），Sie 是尊称；er/sie/es 跟随语法性别而非自然性别。规则变位：词干 + 词尾（ich -e、du -st、er/sie/es/ihr -t、wir/sie/Sie 用原形）。特殊词干：t/d 结尾先加 -e（arbeiten→du arbeitest）；s/ß/x/z 结尾 du 只加 -t（heißt）；-ern/-eln 去掉 n 取词干。不规则变位只发生在 du 和 er/sie/es：a→ä（fährt）、e→i（spricht/liest）、nehmen→nimmt；sein/haben 全不规则死记。\n\n🇬🇧 英语对照：英语只有三单加 -s，德语 6 个人称 5 套词尾；但思路一样：高频词不规则（be-was/were 对应 sein-war）。',
 'table': [['人称', '词尾', 'machen', '备注'],
           ['ich', '-e', 'mache', ''],
           ['du', '-st', 'machst', 's/ß/x/z结尾只加-t'],
           ['er/sie/es', '-t', 'macht', '不规则只变这里'],
           ['wir', '-en', 'machen', ''],
           ['ihr', '-t', 'macht', 'du的复数是ihr'],
           ['sie/Sie', '-en', 'machen', '']],
 'examples': [
     ('Ich lerne Deutsch.', '我在学德语。'),
     ('Du sprichst gut Deutsch.', '你德语说得很好。'),
     ('Er sieht einen Film.', '他在看电影。'),
     ('Arbeiten Sie hier?', '您在这里工作吗？'),
 ]},
{'num': 'M01-07', 'id': 'satzbau', 'cat': 'jufa', 'title': '德语句式结构', 'titleDe': 'Satzbau',
 'explain': '陈述句中变位动词永远在第二位（是第二个"成分"不是第二个词）。宾语、状语可以提前表强调，提前后主语紧跟动词（Heute gehe ich…）。一般疑问句把动词提前到句首；特殊疑问句 = 疑问词 + 一般疑问句（was/wie/wer/wo/woher/wohin）。der/die/das 还可作代词表"这个/那个"；主系表结构中的 das 可代替任何性数的词。注意：动词第二位在从句中不适用。\n\n🇬🇧 英语对照：英语疑问句也是"疑问词+助动词+主语"；德语铁律是主句动词第二位，状语前置时主语后移是德语特有的。',
 'table': [['类型', '结构', '例子'],
           ['陈述句', '主语 + 动词2位', 'Ich lerne Deutsch.'],
           ['状语前置', '时间 + 动词2位 + 主语', 'Heute lerne ich Deutsch.'],
           ['一般问句', '动词1位 + 主语', 'Lernst du Deutsch?'],
           ['特殊问句', '疑问词 + 动词2位 + 主语', 'Woher kommst du?']],
 'examples': [
     ('Ich wohne in Shanghai.', '我住在上海。'),
     ('Heute bleibe ich zu Hause.', '今天我待在家里。'),
     ('Kommst du mit?', '你一起来吗？'),
     ('Wohin fährst du?', '你要去哪里？'),
 ]},
{'num': 'M01-12', 'id': 'possessiv', 'cat': 'mingci', 'title': '物主代词', 'titleDe': 'Possessivpronomen',
 'explain': '对应关系：ich→mein、du→dein、Sie→Ihr、er/es→sein、sie（她/它们）→ihr、wir→unser、ihr（你们）→euer。作定语时词尾和不定冠词完全一样：阳/中性单数无词尾，阴性单数和复数加 -e（mein Vater / meine Mutter / mein Kind / meine Eltern）。注意区分三个 ihr：Ihr（您，大写）、ihr（她/它们）、ihr（你们），靠上下文和大小写区分；euer 加词尾时别漏 e（eure Freunde）。\n\n🇬🇧 英语对照：英语 my/your 永远不变，德语物主代词要随后面名词的性数格加词尾，和 ein 的变法一致。',
 'table': [['', '阳性', '阴性', '中性', '复数'],
           ['mein', 'mein Vater', 'meine Mutter', 'mein Kind', 'meine Eltern'],
           ['euer', 'euer Vater', 'eure Mutter', 'euer Kind', 'eure Eltern']],
 'examples': [
     ('Das ist mein Bruder.', '这是我哥哥。'),
     ('Ihre Tasche ist rot.', '她的包是红色的。'),
     ('Unser Lehrer ist nett.', '我们的老师人很好。'),
     ('Sind das eure Kinder?', '那些是你们的孩子吗？'),
 ]},
{'num': 'M02-01', 'id': 'trennbar', 'cat': 'dongci', 'title': '可分动词', 'titleDe': 'Trennbare Verben',
 'explain': '框架结构：变位部分居第二位，可分前缀蹦到句末（Ich komme um 8 Uhr an.）。前缀三分法：绝对不可分 be-/emp-/ent-/er-/ge-/miss-/ver-/zer-；绝对可分 ab-/an-/auf-/aus-/ein-/mit-/nach-/vor- 等；两用 durch-/über-/um-/unter-/voll-/wieder- 按意义区分（umfahren"撞倒"vs"绕行"）。重音可辅助判断：可分前缀重读第一音节，不可分重读第二音节。有情态动词时合体为原形放句末（mitspielen）。\n\n🇬🇧 英语对照：英语动词短语 pick up / turn off 也有分离（pick it up）；德语是前缀分离，位置固定在句末。',
 'table': [['前缀类型', '例子', '重音'],
           ['不可分', 'be-/ver-/er-…', '第二音节'],
           ['可分', 'an-/auf-/aus-…', '第一音节'],
           ['两用', 'umfahren 撞倒/绕行', '按意义']],
 'examples': [
     ('Der Zug kommt um 8 Uhr an.', '火车8点到达。'),
     ('Mach bitte das Licht an!', '请开灯！'),
     ('Ruf mich später an.', '晚点给我打电话。'),
     ('Sie steht früh auf.', '她起得很早。'),
 ]},
{'num': 'M02-02', 'id': 'modal', 'cat': 'dongci', 'title': '情态动词', 'titleDe': 'Modalverben',
 'explain': '六个：können（能）、müssen（必须）、sollen（应该）、wollen（想要）、mögen（喜欢）、dürfen（可以，被允许）。框架结构：情态动词变位居第二位 + 实义动词原形居句尾。一三人称单数同形（ich kann/er kann）。关键区分：nicht müssen = 不必（≠英语 mustn\'t），nicht dürfen = 禁止；sollen 表义务责任，müssen 表必要性；möchte- 更委婉（点餐用 Ich möchte…）。mögen 作情态多用于否定，"喜欢做某事"用 gern + 动词。框架内成分越靠后越被强调。\n\n🇬🇧 英语对照：和 can/must/shall/will/may 一一对应；但注意 nicht müssen ≠ mustn\'t，这是中式思维重灾区。',
 'table': [['', 'können', 'müssen', 'wollen'],
           ['ich/er', 'kann', 'muss', 'will'],
           ['du', 'kannst', 'musst', 'willst'],
           ['否定含义', '—', 'nicht müssen=不必', '—']],
 'examples': [
     ('Ich kann gut schwimmen.', '我很会游泳。'),
     ('Du musst mir helfen.', '你必须帮我。'),
     ('Ich möchte einen Kaffee.', '我想要一杯咖啡。（委婉）'),
     ('Hier darf man nicht rauchen.', '这里禁止吸烟。'),
 ]},

{'num': 'M02-03', 'id': 'negation', 'cat': 'jufa', 'title': '否定句', 'titleDe': 'Negation',
 'explain': 'kein 否定"不确指"名词的存在（= 没有），词形和不定冠词一样变；nicht 否定确指名词、动词、形容词。nicht 的位置决定否定范围：越靠后越倾向否定全句。无情态动词时 nicht 居句末，有情态动词时在动词原形前（Ich kann nicht kommen.）；否定可分动词时 nicht 在句尾前缀之前（Mach das Licht nicht an!）。注意不能拆开介词和宾语。\n\n🇬🇧 英语对照：英语 no/not 分工类似（no + 名词，not + 动词）；德语 kein 要变格、nicht 位置定否定范围，是英语没有的。',
 'table': [['', 'kein（不确指名词）', 'nicht（其他）'],
           ['例子', 'kein Geld（没有钱）', 'nicht gut（不好）'],
           ['变格', '随 ein 变', '不变'],
           ['位置', '名词前', '常居句末/动词原形前']],
 'examples': [
     ('Ich habe kein Auto.', '我没有车。'),
     ('Das ist keine gute Idee.', '这不是个好主意。'),
     ('Ich komme heute nicht.', '我今天不来。'),
     ('Mach das Licht nicht an!', '别开灯！'),
 ]},
{'num': 'M02-04', 'id': 'imperativ', 'cat': 'dongci', 'title': '命令式', 'titleDe': 'Imperativ',
 'explain': 'du 的命令式：去掉词尾 -st（komm! mach!）；词干以 t/d 结尾必须加 -e（arbeiten→arbeite!）。不规则动词：加变音的恢复规则形式（schlafen→schlaf!），换字母的保留（sprechen→sprich!、essen→iss!、lesen→lies!，不能加 -e），wissen→wisse 特例。ihr 的命令式同现在时（kommt!，主语可省略）；Sie/wir 的命令式保留主语紧跟动词（Kommen Sie! Gehen wir!）。sein/haben：sei/seid/seien、hab(e)/habt/haben。du 的命令式必须省略主语，对 Sie 说话加 bitte 表礼貌。\n\n🇬🇧 英语对照：英语命令式也是动词原形（Come!）；德语分 du/ihr/Sie 三套，元音变化的保留是难点。',
 'table': [['对象', '形式', '例子'],
           ['du', '去 -st（t/d结尾加-e）', 'Komm her! / Arbeite!'],
           ['ihr', '同现在时', 'Kommt her!'],
           ['Sie', 'Sie + 原形', 'Kommen Sie bitte her!'],
           ['不规则', '保留换字母', 'Sprich! / Iss! / Lies!']],
 'examples': [
     ('Komm bitte her!', '请过来！'),
     ('Sprich langsamer!', '说慢一点！'),
     ('Macht die Tür zu!', '把门关上！（对你们说）'),
     ('Seien Sie bitte pünktlich!', '请准时！（尊称）'),
 ]},
{'num': 'M03-01', 'id': 'akkusativ', 'cat': 'gejie', 'title': '第四格', 'titleDe': 'Akkusativ',
 'explain': '第四格 = 直接宾语，回答"谁/什么"（wen/was）。冠词、物主代词、kein、人称代词都要变格，但只有阳性单数发生变化：der→den、ein→einen、mein→meinen、kein→keinen。人称代词：mich/dich/ihn/sie/es/uns/euch/sie/Sie。注意：sein/werden/bleiben 后面是表语，用第一格（Er ist Lehrer.）；主语和表语人称不一致时动词跟随非第三人称单数的那个（Das bin ich. 是我）。\n\n🇬🇧 英语对照：英语宾格只有代词变化（he→him）；德语是冠词变化，且只变阳性单数——记住这一条就够了。',
 'table': [['格', '阳性', '阴性', '中性', '复数'],
           ['一格', 'der', 'die', 'das', 'die'],
           ['四格', 'den', 'die', 'das', 'die'],
           ['人称代词', 'ihn', 'sie', 'es', 'sie']],
 'examples': [
     ('Ich sehe den Mann.', '我看见那个男人。'),
     ('Sie kauft einen Apfel.', '她买一个苹果。'),
     ('Das bin ich.', '是我。'),
     ('Er wird Lehrer.', '他要当老师。（表语一格）'),
 ]},
{'num': 'M03-02', 'id': 'dativ', 'cat': 'gejie', 'title': '第三格', 'titleDe': 'Dativ',
 'explain': '第三格 = 间接宾语，回答"给谁/为谁"（wem）。双宾语动词（如 geben 等）：人用三格、物用四格（Ich gebe dem Mann einen Apfel.）。口诀：阳性/中性单数 + -(e)m、阴性单数 + -(e)r、复数 + -(e)n；复数三格名词本身还要加 -n（den Lehrern，本身以 n/s 结尾的除外）。人称代词：mir/dir/ihm/ihr/ihm/uns/euch/ihnen/Ihnen（er 和 es 都是 ihm；"她"=ihr、"他们"=ihnen）。固定支配三格的动词：helfen、danken、gratulieren、gehören。\n\n🇬🇧 英语对照：英语 I give him a book 里 him 兼任二三格；德语把直接/间接宾语用四格/三格严格区分。',
 'table': [['格', '阳性', '阴性', '中性', '复数'],
           ['一格', 'der', 'die', 'das', 'die'],
           ['三格', 'dem', 'der', 'dem', 'den + n'],
           ['人称代词', 'ihm', 'ihr', 'ihm', 'ihnen']],
 'examples': [
     ('Ich helfe dem Mann.', '我帮助那个男人。'),
     ('Ich gebe dir ein Buch.', '我给你一本书。'),
     ('Das gehört mir.', '这属于我。'),
     ('Er dankt seinen Eltern.', '他感谢他的父母。'),
 ]},
{'num': 'M03-03', 'id': 'praep_dativ', 'cat': 'gejie', 'title': '只支配第三格的介词', 'titleDe': 'Präpositionen mit Dativ',
 'explain': '10 个：ab、aus、außer、bei、mit、nach、seit、von、zu、gegenüber。记忆口诀"aus außer 买米拿菜放醋"（aus/außer/bei/mit/nach/seit/von/zu）。要点：seit 只跟过去的时间点（seit einem Jahr）；von 永远支配三格；gegenüber 的宾语可前置，代词宾语必须后置（mir gegenüber）；缩合 zum=zu dem、zur=zu der。判断格位看实际被哪个介词/动词支配，整个成分一起变格。\n\n🇬🇧 英语对照：英语介词不支配格；德语这些介词后面永远跟三格，按固定搭配记。',
 'table': [['介词', '含义', '例子'],
           ['aus / von', '从…里 / 来自', 'aus China / von mir'],
           ['bei / mit', '在…处 / 和…', 'bei Eltern / mit Bus'],
           ['nach / seit', '往…/自从', 'nach Hause / seit 2020'],
           ['zu', '向…', 'zum Arzt（zu+dem）'],
           ['gegenüber', '在…对面', 'mir gegenüber']],
 'examples': [
     ('Ich komme aus Shanghai.', '我来自上海。'),
     ('Er wohnt bei seinen Eltern.', '他和父母住在一起。'),
     ('Ich fahre mit dem Fahrrad zur Arbeit.', '我骑车上班。'),
     ('Seit einem Jahr lerne ich Deutsch.', '我学德语一年了。'),
 ]},
{'num': 'M03-04', 'id': 'praep_akk', 'cat': 'gejie', 'title': '只支配第四格的介词', 'titleDe': 'Präpositionen mit Akkusativ',
 'explain': '5 个：durch、ohne、gegen、um、für（记"dog uf"）。注意介词的"格"≠动词的直接/间接宾语概念，是两套系统。加不加冠词看确指/泛指；bis 也只支配四格。um 既表"围绕"又表钟点（um 8 Uhr）。\n\n🇬🇧 英语对照：同样按固定搭配记；注意 für（为了）是最高频的四格介词。',
 'table': [['介词', '含义', '例子'],
           ['durch', '穿过', 'durch den Park'],
           ['ohne', '没有', 'ohne dich'],
           ['gegen', '反对/撞上', 'gegen den Baum'],
           ['um', '围绕/在…点', 'um 8 Uhr'],
           ['für', '为了', 'für dich']],
 'examples': [
     ('Das Geschenk ist für dich.', '这礼物是给你的。'),
     ('Er geht durch den Park.', '他穿过公园。'),
     ('Ohne Kaffee kann ich nicht arbeiten.', '没有咖啡我没法工作。'),
     ('Der Unterricht beginnt um 9 Uhr.', '课九点开始。'),
 ]},
{'num': 'M03-06', 'id': 'uhrzeit', 'cat': 'jufa', 'title': '询问和播报时间', 'titleDe': 'Uhrzeit',
 'explain': '问法：Wie viel Uhr ist es? / Wie spät ist es? 正式场合用 24 小时制，Uhr 必须保留；口语用 12 小时制：过 = nach、差 = vor、Viertel（一刻钟）、halb vier = 三点半（"四点的一半"！）。nach/vor 后省略 Uhr。某事发生在几点用 um（Um wie viel Uhr…? 里介词跟疑问词一起放句首，因为疑问词是介词宾语）。Punkt/genau（整点）、ungefähr（大概）、fast（快到）。\n\n🇬🇧 英语对照：英语 half past three 是"三点过半"，德语 halb vier 是"离四点差一半"——方向反的，最容易错。',
 'table': [['时间', '说法'],
           ['8:00', 'acht Uhr'],
           ['8:15', 'viertel nach acht'],
           ['8:30', 'halb neun'],
           ['8:45', 'viertel vor neun']],
 'examples': [
     ('Wie spät ist es?', '现在几点了？'),
     ('Es ist halb neun.', '现在八点半。'),
     ('Der Film beginnt um viertel nach acht.', '电影八点一刻开始。'),
     ('Wir treffen uns um halb zehn.', '我们九点半见。'),
 ]},
{'num': 'M04-01', 'id': 'mengen', 'cat': 'mingci', 'title': '量词', 'titleDe': 'Mengenangaben',
 'explain': '结构：数词 + 量词 + 名词（ein Stück Kuchen、一块蛋糕）。数量 >1 时只有阴性量词变复数，量词后的可数名词一律变复数（zwei Tassen Kaffee）。有量词时只有量词变格，动词跟量词走（Zwei Tassen Kaffee reichen aus. 两杯咖啡够了）。口语中饮料前量词可省略（einen Kaffee），数词 + mal 可代替（zweimal Kaffee）。注意 Flasche 是细颈瓶、Glas 是玻璃杯、Tasse 是茶杯。\n\n🇬🇧 英语对照：英语 a glass of water 有 of，德语直接并列；英语 two glasses 用复数，德语量词（阳/中性）不变。',
 'table': [['量词', '例子'],
           ['ein Glas', 'ein Glas Wasser（一杯水）'],
           ['eine Tasse', 'eine Tasse Tee（一杯茶）'],
           ['ein Stück', 'ein Stück Kuchen（一块蛋糕）'],
           ['eine Flasche', 'eine Flasche Wein（一瓶酒）']],
 'examples': [
     ('Ich trinke ein Glas Wasser.', '我喝一杯水。'),
     ('Zwei Tassen Kaffee, bitte!', '请来两杯咖啡！'),
     ('Zwei Tassen Kaffee reichen aus.', '两杯咖啡够了。'),
     ('Er isst ein Stück Kuchen.', '他吃一块蛋糕。'),
 ]},

{'num': 'M04-03', 'id': 'wechsel', 'cat': 'gejie', 'title': '“静三动四”原则', 'titleDe': 'Wechselpräpositionen',
 'explain': '9 个双向介词：an、auf、hinter、in、neben、über、unter、vor、zwischen。静止 = 三格（"静三"），相对运动 = 四格（"动四"）。"动"必须是相对的：im Fitnessstudio（在健身房里，三格）vs ins Fitnessstudio（进健身房，四格）。提问：三格用 wo、四格用 wohin。该原则不适用于只支配一个格的介词。注意直接/间接宾语概念不适用于介词：Das Buch liegt auf dem Stuhl 里 Buch 是第一格（主语）！Ich schreibe auf dem Buch 死记（三格）。\n\n🇬🇧 英语对照：英语用不同介词区分（in vs into），德语用同一个介词、靠格来区分——这是德语格系统最漂亮的地方。',
 'table': [['介词', '静三（wo）', '动四（wohin）'],
           ['in', 'Ich bin in der Schule.', 'Ich gehe in die Schule.'],
           ['auf', 'Das Buch liegt auf dem Tisch.', 'Ich lege das Buch auf den Tisch.'],
           ['an', 'Das Bild hängt an der Wand.', 'Er hängt das Bild an die Wand.']],
 'examples': [
     ('Die Katze sitzt auf dem Stuhl.', '猫坐在椅子上。'),
     ('Die Katze springt auf den Stuhl.', '猫跳上椅子。'),
     ('Wo ist mein Handy?', '我手机在哪？（wo→三格）'),
     ('Wohin fliegst du?', '你要飞去哪？（wohin→四格）'),
 ]},
{'num': 'M04-04', 'id': 'adjektiv', 'cat': 'xingrong', 'title': '形容词词尾变化', 'titleDe': 'Adjektivdeklination',
 'explain': '定冠词后：以 -en 为主；单数一、四格 der/die/das 后用 -e（der gute Mann、den guten…不对，是 der gute / den guten：记住一格 -e，其余 -en）。三格和复数一律 -en。ein/eine 后：补上定冠词的词尾（ein guter Mann = der 缺的那笔）。零冠词：直接用定冠词词尾（Guten Tag!）。物主代词/kein 视作 ein/eine。介词宾语只看介词，不管前面。易错：复数冠词后形容词永远 -en（die kleinen Kinder）。\n\n🇬🇧 英语对照：英语形容词永远不变（a good man / the good man），德语形容词词尾是 A1 最大的记忆负担，靠高频句型磨熟。',
 'table': [['', '阳性', '阴性', '中性', '复数'],
           ['定冠词后', 'der gute', 'die gute', 'das gute', 'die guten'],
           ['不定冠词后', 'ein guter', 'eine gute', 'ein gutes', '—'],
           ['零冠词', 'guter', 'gute', 'gutes', 'gute']],
 'examples': [
     ('Der neue Film ist spannend.', '这部新电影很刺激。'),
     ('Ich kaufe einen roten Apfel.', '我买一个红苹果。'),
     ('Sie hat eine schöne Stimme.', '她有动听的嗓音。'),
     ('Mit kaltem Wasser waschen.', '用冷水洗。'),
 ]},
{'num': 'M04-06', 'id': 'perfekt', 'cat': 'dongci', 'title': '现在完成时', 'titleDe': 'Perfekt',
 'explain': '框架结构：助动词变位居第二位 + 过去分词居句尾。规则过去分词：ge + 词干 + t（gemacht），特殊词干先加 -e（gearbeitet）；-ieren 结尾不加 ge（studiert）。不规则三类：ge + 变音词干 + en（gesprochen）、ge + 词干 + en（gegangen）、ge + 变音词干 + t（gebracht）。助动词：多数用 haben；sein 用于不及物 + 位置变化/状态变化，以及 sein/bleiben/werden 本身。前缀：不可分前缀不加 ge（verstanden），可分前缀 = 前缀 + 完整过去分词（angekommen）。口语中完成时基本取代过去时。易错：beginnen→begonnen 是两条规则叠加。\n\n🇬🇧 英语对照：结构对应英语现在完成时 have done；但德语口语里它承担了英语过去时 did 的工作。',
 'table': [['', 'haben', 'sein'],
           ['结构', 'ich habe gemacht', 'ich bin gegangen'],
           ['用于', '大多数动词', '位移 + 状态变化 + sein/bleiben/werden']],
 'examples': [
     ('Ich habe gestern viel gearbeitet.', '我昨天工作了很多。'),
     ('Sie ist nach Berlin gefahren.', '她开车去了柏林。'),
     ('Wir haben einen Film gesehen.', '我们看了一部电影。'),
     ('Er hat mich gut verstanden.', '他很理解我。（不可分不加ge）'),
 ]},
{'num': 'M04-07', 'id': 'praet_hs', 'cat': 'dongci', 'title': 'sein 和 haben 的过去时', 'titleDe': 'Präteritum von sein/haben',
 'explain': '口语中过去时基本被完成时代替，但 sein/haben/情态动词除外——口语里也常用过去时（Ich war müde. 比 Ich bin müde gewesen 自然得多）。haben：hatte/hattest/hatte/hatten/hattet/hatten；sein：war/warst/war/waren/wart/waren。南部德国、瑞士、奥地利几乎只用完成时。\n\n🇬🇧 英语对照：对应英语 had / was，和英语一样是最高频的不规则过去式，先背这两个。',
 'table': [['', 'haben', 'sein'],
           ['ich', 'hatte', 'war'],
           ['du', 'hattest', 'warst'],
           ['er/sie/es', 'hatte', 'war'],
           ['wir/sie', 'hatten', 'waren']],
 'examples': [
     ('Ich hatte keine Zeit.', '我没有时间。'),
     ('Er war gestern krank.', '他昨天病了。'),
     ('Wir waren im Kino.', '我们在电影院。'),
     ('Hattest du Spaß?', '你玩得开心吗？'),
 ]},
{'num': 'M05-01', 'id': 'adj_nom', 'cat': 'xingrong', 'title': '形容词的名词化', 'titleDe': 'Nominalisierte Adjektive',
 'explain': '形容词首字母大写、去掉后接名词即名词化（angestellt→der Angestellte 雇员）；词尾变化完全按形容词词尾规则（零冠词取定冠词词尾）。阳/阴性名词化通常指人（der/die Alte 老人），中性指物（das Interessante 令人感兴趣的事、das Gesagte 说过的话）。特例：Deutscher（德国人）是形容词名词化（Ich bin Deutscher），其他国籍如 Chinese/Chinesin、Amerikaner 是普通名词、不按形容词变格。说语言：用"说 + Deutsch"（Ich spreche gut Deutsch）或"用 + das Deutsche"（vom Chinesischen ins Deutsche，固定搭配）。不是所有形容词都能名词化，约定俗成要背。\n\n🇬🇧 英语对照：英语 the rich / the poor 也有形容词作名词，但不变格；德语名词化后完整走一遍性数格。',
 'table': [['', '单数', '复数'],
           ['表人（阳）', 'der Deutsche', 'die Deutschen'],
           ['表人（阴）', 'die Alte', 'die Alten'],
           ['表物（中）', 'das Beste', '—']],
 'examples': [
     ('Ein Deutscher wohnt nebenan.', '一个德国人住在隔壁。'),
     ('Hast du etwas Neues gehört?', '你听到什么新鲜事了吗？'),
     ('Das Beste kommt noch.', '最好的还在后头。'),
     ('Ich spreche gut Deutsch.', '我说德语说得很好。'),
 ]},
{'num': 'M05-02', 'id': 'adj_sonder', 'cat': 'xingrong', 'title': '形容词词尾的特殊变化', 'titleDe': 'Besondere Adjektive',
 'explain': '-el 结尾：去 e 再加词尾（dunkel→dunklen、sensibel→sensibles、übel→üble）。-auer/-euer 结尾：去 e 再加词尾（teuer→teuren、sauer→saures）。hoch→hoh 再加词尾（einen hohen Berg）。永远不加词尾的：rosa/lila/prima/extra/mega（a 结尾）、beige/orange/türkis（颜色外来词）、super/klasse。\n\n🇬🇧 英语对照：类似英语的不规则（good→better），都是高频词的特殊形式，单独记。',
 'table': [['形容词', '变化', '例子'],
           ['dunkel', '→ dunkl-', 'ein dunkles Zimmer'],
           ['teuer', '→ teur-', 'eine teure Uhr'],
           ['hoch', '→ hoh-', 'ein hoher Berg'],
           ['rosa / lila', '不变', 'eine rosa Blume']],
 'examples': [
     ('Der Berg ist sehr hoch.', '这山很高。'),
     ('Ein hohes Haus steht dort.', '那里有一栋高楼。'),
     ('Das Zimmer ist dunkel.', '房间很暗。'),
     ('Sie trägt eine rosa Blume im Haar.', '她头发上戴着一朵粉色的花。'),
 ]},
{'num': 'M05-03', 'id': 'viel_wenig', 'cat': 'xingrong', 'title': 'viel(e) 和 wenig(e) 的用法', 'titleDe': 'viel / wenig',
 'explain': 'viel/wenig 修饰不可数名词（= much / a little），viele/wenige 修饰复数可数名词（= many / a few）；wie viel / wie viele 对应 how much / how many。修饰不可数名词的 viel/wenig：前面有冠词时按普通形容词加词尾（das viele Geld），无冠词时不加词尾（viel Milch）。修饰可数名词的 viele/wenige：无论有无冠词一律按形容词加词尾（vielen hundert Jahren）。书面语 ein wenig = ein bisschen；viel/wenig 前不可能出现不定冠词 ein。\n\n🇬🇧 英语对照：英语 much/many 按可数不可数区分，德语按"修饰可数还是不可数"决定用哪套，再看有无冠词决定加不加词尾。',
 'table': [['', '不可数（viel/wenig）', '可数复数（viele/wenige）'],
           ['无冠词', 'viel Milch（不加）', 'viele Leute（加）'],
           ['有冠词', 'das viele Geld（加）', 'die vielen Leute（加）']],
 'examples': [
     ('Ich habe viel Arbeit.', '我有很多工作。'),
     ('Er hat wenig Geld.', '他没什么钱。'),
     ('Viele Leute warten draußen.', '很多人在外面等。'),
     ('Wie viel kostet das?', '这个多少钱？'),
 ]},
{'num': 'M05-04', 'id': 'datum', 'cat': 'mingci', 'title': '日期、月份、年份和序数词', 'titleDe': 'Datum & Ordinalzahlen',
 'explain': '星期、月份都是阳性（12 个月份拼写近英语，别混淆）。序数词：1–19 加 -te（erste/zweite/dritte 特例），20 以上加 -ste；wievielte- 提问"第几"，按形容词加词尾。年份读法：2000 年及以后 zweitausend+（2026 = zweitausendsechsundzwanzig），1000–1999 用 hundert（1995 = neunzehnhundertfünfundneunzig）。"在几月几号"用 an（am 23. Oktober）；省略月份时序数词名词化大写（am Dreiundzwanzigsten）；日期顺序日-月-年，用点分隔。不带介词的时间状语用第四格（den 5. Juni）。\n\n🇬🇧 英语对照：英语 October 23rd / on Monday；德语日期用序数词 + 三格（am dreiundzwanzigsten Oktober），和英语 on the 23rd of October 思路接近。',
 'table': [['表达', '德语'],
           ['在某天', 'am 4. Oktober'],
           ['在星期几', 'am Montag'],
           ['在某年', 'im Jahr 2026'],
           ['序数词', 'der erste, der zweite, der dritte'],
           ['无介词时间状语', 'den 5. Juni（四格）']],
 'examples': [
     ('Heute ist der vierte Oktober.', '今天是十月四号。'),
     ('Wir treffen uns am Montag.', '我们周一见。'),
     ('Mein Geburtstag ist am zwölften Mai.', '我生日是五月十二号。'),
     ('Er wurde am ersten Januar geboren.', '他出生在一月一日。'),
 ]},

{'num': 'M05-05', 'id': 'jahrhundert', 'cat': 'mingci', 'title': '世纪与年代', 'titleDe': 'Jahrhundert',
 'explain': '世纪 = das Jahrhundert，配序数词（aus dem 20. Jahrhundert，读 zwanzigsten）。基数词加 -er 名词化：der Zehner（10 元面值/10 路车/十位）、die Zwanziger（20 年代，复数）、die Zwanzigerin（20 多岁的女人）。"XX 年代"：in den Zwanzigern / in den 20er-Jahren，前面可加世纪（in den 1920ern）。注意不是所有基数词加 -er 都能表货币，约定俗成。\n\n🇬🇧 英语对照：英语 the 20th century / the 90s；德语 Jahrhundert 中性、年代加 -er，基数词大写变名词。',
 'table': [['表达', '德语'],
           ['世纪', 'aus dem 21. Jahrhundert'],
           ['年代', 'in den 80er Jahren'],
           ['数字名词', 'der Zehner（十位/十元）'],
           ['二十多岁', 'die Zwanzigerin']],
 'examples': [
     ('Das war im 20. Jahrhundert.', '那是二十世纪的事。'),
     ('Die Musik der 80er ist toll.', '八十年代的音乐很棒。'),
     ('In den 1920ern war Berlin wild.', '1920 年代的柏林很狂野。'),
     ('Sie ist in den Zwanzigern.', '她二十多岁。'),
 ]},
{'num': 'M06-01', 'id': 'komparativ', 'cat': 'xingrong', 'title': '比较级和最高级：规则变化', 'titleDe': 'Komparativ & Superlativ',
 'explain': '德语不分单/多音节：比较级一律 +er，最高级一律 +st。作表语的比较级：+er（ist interessanter）；作定语：+er 后再按形容词词尾变（ein schöneres Haus）。作表语的最高级：am + -sten（am schönsten，与主语性别无关，固定形式）；南德口语可用 das schönste。作定语的最高级：定冠词 + 原级 + st + 词尾（das schönste Haus、den billigsten Tisch）。副词比较级/最高级构成同表语形容词（schneller、am schnellsten）。表语只跟 sein/bleiben/werden 系动词。\n\n🇬🇧 英语对照：和英语 faster / the fastest 几乎一一对应；am + -sten 是固定形式，不跟主语变。',
 'table': [['', '原级', '比较级', '最高级（表语）'],
           ['规则', 'schnell', 'schneller', 'am schnellsten'],
           ['变元音', 'groß', 'größer', 'am größten'],
           ['定语', '—', 'ein schöneres Haus', 'das schönste Haus']],
 'examples': [
     ('Mein Auto ist schneller als deins.', '我的车比你的快。'),
     ('Sie ist größer als ihr Bruder.', '她比她哥哥高。'),
     ('Das ist der schönste Tag!', '这是最美好的一天！'),
     ('Er läuft am schnellsten.', '他跑得最快。'),
 ]},
{'num': 'M06-02', 'id': 'komparativ_halb', 'cat': 'xingrong', 'title': '比较级和最高级：半规则变化', 'titleDe': 'Halbregelmäßige Steigerung',
 'explain': '-el/-auer/-euer 类同样去 e 再加比较级词尾（dunkel→dunkler、teuer→teurer）。-en/-er 结尾：作定语去 e（den trockneren Wein），作表语/副词保留 e（ist trockener）。最高级：-t/-haft/-s/-sk/-ß/-x/-z 结尾先加 -e 再加 -st（am interessantesten、am süßesten）；-d/-sch 结尾的单音节或部分双音节也先加 -e（am rundesten），多音节直接加 -st（am bedeutendsten）。部分单音节加 Umlaut（共 21 个）：alt→älter、jung→jünger、kurz→kürzer、kalt、klug、stark；部分可加可不加（gesund、glatt、nass）；英文借词双写辅音（fit→fitter）。定语用法：先完成特殊变化，再按性数格加词尾（das interessanteste Buch）。\n\n🇬🇧 英语对照：英语也有"半规则"（narrow→narrower 可加可不加 more）；德语的规则更细，但高频词就那 21 个变元音的。',
 'table': [['类型', '原级', '比较级/最高级'],
           ['去e', 'dunkel / teuer', 'dunkler / teurer'],
           ['最高级加e', 'interessant', 'am interessantesten'],
           ['变元音', 'alt / jung / kurz', 'älter / jünger / kürzer'],
           ['借词双写', 'fit', 'fitter']],
 'examples': [
     ('Der dunklere Wein schmeckt besser.', '颜色更深的酒更好喝。'),
     ('Das ist das interessanteste Buch.', '这是最有意思的书。'),
     ('Er ist älter als ich.', '他比我大。'),
     ('Sie wird immer schöner.', '她越来越漂亮。'),
 ]},
{'num': 'M06-03', 'id': 'komparativ_unreg', 'cat': 'xingrong', 'title': '比较级和最高级：不规则变化', 'titleDe': 'Unregelmäßige Steigerung',
 'explain': '不规则表死记：gut→besser→am besten；gern→lieber→am liebsten；hoch→höher→am höchsten；viel→mehr→am meisten；wenig→weniger→am wenigsten；nah→näher→am nächsten；groß→größer→am größten；bald→eher→am ehesten。nächste 已独立为"下一个"，作四格时间状语时不加定冠词（nächste Woche、nächstes Jahr）。mehr/weniger 永远只能作副词，不加词尾（Ich habe weniger Geld als du.）；meisten/wenigsten 在定冠词后作形容词时要加词尾（Die meisten Leute）。定语用 das größte Haus，不用 am。\n\n🇬🇧 英语对照：和英语 good→better→best、much→more→most 一样，都是最高频词的不规则变化。',
 'table': [['原级', '比较级', '最高级'],
           ['gut', 'besser', 'am besten'],
           ['viel', 'mehr', 'am meisten'],
           ['gern', 'lieber', 'am liebsten'],
           ['hoch', 'höher', 'am höchsten']],
 'examples': [
     ('Das Wetter wird immer besser.', '天气越来越好。'),
     ('Ich trinke lieber Tee als Kaffee.', '比起咖啡我更爱喝茶。'),
     ('Er hat die meisten Punkte.', '他得分最高。'),
     ('Nächste Woche fliege ich weg.', '下周我飞走。（四格不加冠词）'),
 ]},
{'num': 'M06-04', 'id': 'komparativ_use', 'cat': 'xingrong', 'title': '比较级和最高级：用法总结', 'titleDe': 'Gebrauch der Steigerung',
 'explain': 'A>B：比较连词 als（≠介词，后面名词格位与被比较对象一致：Ich liebe dich mehr als sie. 有歧义，格位定意思）；noch/viel/etwas/ein bisschen + 比较级表程度；um/四格名词表差异（um 50%、einen Monat jünger 小一个月）；immer + 比较级 = 越来越；aller- + 最高级强调独一无二（der allerschnellste Wagen）；序数词去 e + 最高级（zweitbeste 第二好、drittgrößte）。A=B：so…wie…（so schnell wie möglich 尽量快）、ebenso/genauso 强调完全一致。A<B：weniger + 原级 / am wenigsten（原级按需加词尾：das am wenigsten teure Auto）；"最不"常用反义词最高级代替（billigste 最便宜 = 最不贵）。\n\n🇬🇧 英语对照：als = than（但 als 是连词，格位跟比较对象一致）；so…wie = as…as；immer + 比较级 = more and more。',
 'table': [['含义', '结构', '例子'],
           ['A>B', 'als + 比较级', 'größer als du'],
           ['差异', 'um/四格 + 比较级', 'um 50% teurer'],
           ['越来越', 'immer + 比较级', 'immer besser'],
           ['A=B', 'so…wie…', 'so groß wie du'],
           ['A<B', 'weniger + 原级', 'weniger teuer']],
 'examples': [
     ('Er ist einen Monat jünger als ich.', '他比我小一个月。'),
     ('Das Wetter wird immer besser.', '天气越来越好。'),
     ('So schnell wie möglich!', '越快越好！'),
     ('Das ist das zweitbeste Ergebnis.', '这是第二好的成绩。'),
 ]},
{'num': 'M07-01', 'id': 'dass_satz', 'cat': 'jufa', 'title': 'dass 引导的名词性从句', 'titleDe': 'dass-Satz',
 'explain': '尾语序：变位动词永远居从句最后一位，非变位动词（过去分词、动词原形）倒数第二位；可分动词在从句中不再分开（einkauft、mitkommt）。书面语中 dass 和逗号不可省略；口语中主句动词为 finden/hoffen/denken/glauben（感觉/希望/认为/相信）时 dass 可省略，其他动词后一般不省略。dass 还可引导主语从句/同位语从句（Schön, dass ihr da seid!；Er ist der Meinung, dass… 后者是第二格固定搭配），这些 dass 都不能省略。主从句时态不必一致，尊重事实；从句整体占首位时主句倒装（变位动词第二位）。\n\n🇬🇧 英语对照：和英语 that 从句意思一样，但英语语序不变（I think that you are right），德语动词必须放从句末尾。',
 'table': [['', '主句', '从句'],
           ['基本', 'Ich weiß,', 'dass er heute kommt.'],
           ['带情态', 'Ich glaube,', 'dass sie Deutsch lernen will.'],
           ['可分动词', 'Ich sehe,', 'dass er einkauft.（不分开）']],
 'examples': [
     ('Ich denke, dass du recht hast.', '我觉得你是对的。'),
     ('Er sagt, dass er keine Zeit hat.', '他说他没时间。'),
     ('Ich hoffe, dass das Wetter gut bleibt.', '我希望天气保持晴朗。'),
     ('Schön, dass ihr da seid!', '你们能来真好！'),
 ]},
{'num': 'M07-09', 'id': 'futur', 'cat': 'dongci', 'title': '将来时', 'titleDe': 'Futur I',
 'explain': '将来时 = werden 变位 + 动词原形居句尾（框架结构）；从句中 werden 按尾语序放最后（…, die ich hier essen werde）。将来时带有承诺/希望/预言的感情色彩（政客、推销、算命常用）。日常生活中德国人一般用现在时代替将来时（Ich studiere nächstes Jahr in den USA.），除非明确表达承诺/期待。别和英语 will 画等号滥用。\n\n🇬🇧 英语对照：对应英语 will + 动词，但德语口语更爱用现在时表将来（类似英语 I am calling you tomorrow 用进行时表将来）。',
 'table': [['', '结构', '例子'],
           ['将来时', 'werden + 原形', 'Ich werde dir helfen.'],
           ['从句', '尾语序', '…, die ich essen werde.'],
           ['口语常用', '现在时 + 时间', 'Morgen helfe ich dir.']],
 'examples': [
     ('Ich werde dich morgen anrufen.', '我明天给你打电话。'),
     ('Es wird morgen regnen.', '明天会下雨。'),
     ('Morgen besuche ich meine Oma.', '明天我去看奶奶。（口语更常用）'),
     ('Wirst du mir helfen?', '你会帮我吗？'),
 ]},
{'num': 'M08-01', 'id': 'praeteritum', 'cat': 'dongci', 'title': '一般过去时', 'titleDe': 'Präteritum',
 'explain': '一般过去时主要用于书面语；口语用现在完成时，但 sein/haben/情态动词/es gibt 在口语中也常用过去时。规则动词：词干 + te + 人称词尾（fragte、arbeitete），特殊词干规则与现在时相同。haben→hatte、sein→war；情态动词：musste/konnte/sollte/durfte/wollte/mochte。不规则动词按元音变换死记：e→a→e（geben→gab→gegeben）、i→a→u（finden→fand→gefunden）、ei→ie（schreiben→schrieb）、o→a（kommen→kam）、ie→o（fliegen→flog）。过去时词尾 -te/-test/-tet/-ten 中的 e 读 [ə]。\n\n🇬🇧 英语对照：对应英语过去时 did/went，但德语口语里完成时抢了它的活，分工比英语更彻底。',
 'table': [['', '规则', '不规则'],
           ['结构', '词干 + te', '元音变化'],
           ['ich', 'machte', 'ging / gab'],
           ['du', 'machtest', 'gingst / gabst'],
           ['er', 'machte', 'ging / gab']],
 'examples': [
     ('Er ging nach Hause.', '他回家了。（书面/叙述）'),
     ('Sie kam zu spät.', '她迟到了。'),
     ('Ich konnte nicht schlafen.', '我睡不着。（情态动词口语也用过去时）'),
     ('Es gab ein Problem.', '出了个问题。'),
 ]},
{'num': 'M01-09', 'id': 'jishu', 'cat': 'vokabel', 'title': '基数词', 'titleDe': 'Kardinalzahlen',
 'explain': '1–12 硬背；13–19 = 个位 + zehn（sechzehn 去 s，siebzehn 去 en）；整十 = 数字 + zig（dreißig 写 ß）；21–99 = 个位 + und + 十位（einundzwanzig）；100 = (ein)hundert，1000 = (ein)tausend。eins 后接词时去掉 s（ein Apfel）。读音：vierzehn 的 vier 是短音（例外）；und 的 d 吞音；sechs/sechzehn 的 ch 读 [ks]；zehn 读 [tseːn] 不读 [tsiːn]。\n\n🇬🇧 英语对照：英语 13–19 也是"个位+teen"，21–99 也是"十位-个位"（twenty-one）；德语把个位放前面（einundzwanzig），顺序反的。',
 'table': [['数字', '德语'],
           ['0–12', 'null, eins, zwei, drei, vier, fünf, sechs, sieben, acht, neun, zehn, elf, zwölf'],
           ['13–19', 'dreizehn, vierzehn, fünfzehn, sechzehn, siebzehn, achtzehn, neunzehn'],
           ['整十', 'zwanzig, dreißig, vierzig, fünfzig, sechzig, siebzig, achtzig, neunzig'],
           ['21', 'einundzwanzig（个位+und+十位）'],
           ['100 / 1000', '(ein)hundert / (ein)tausend']],
 'examples': [
     ('Wie alt bist du? – Ich bin zwanzig.', '你多大了？——我二十岁。'),
     ('Das Buch kostet zwölf Euro.', '这本书十二欧。'),
     ('Ein Apfel und eine Birne, bitte.', '请来一个苹果、一个梨。'),
     ('Hundert minus zwanzig ist achtzig.', '100 减 20 等于 80。'),
 ]},
{'num': 'M01-10', 'id': 'guoming', 'cat': 'vokabel', 'title': '国名、语言和国籍', 'titleDe': 'Länder, Sprachen & Nationalitäten',
 'explain': '国民词两类：中/英/法/俄/土/瑞典等男国民以 -e 结尾（der Chinese），复数 +n；其余男国民以 -er 结尾、单复同形（der Amerikaner）。女性一律加 -in，复数 +nen（die Chinesin/die Chinesinnen）——所有女性国民复数都是 +nen。语言词尾几乎都是 -isch（印度 Hindi 例外），形容词也都是 -isch。特殊国名：die USA、die Niederlande 是复数；die Türkei、die Schweiz 阴性；der Iran 阳性；其余中性。der/die 国名冠词不可省；中性国名通常不带冠词（有形容词修饰时可加 das：das schöne China）。读音：元音前 s 读 [z]（Syrien）；Chinesin 的 i 是短音。\n\n🇬🇧 英语对照：英语 China→Chinese 男女同形；德语男女国民词分开，且女性复数一律 -nen，规则得多。',
 'table': [['国家', '语言', '男国民', '女国民', '形容词'],
           ['中国', 'Chinesisch', 'der Chinese', 'die Chinesin', 'chinesisch'],
           ['美国', 'Englisch', 'der Amerikaner', 'die Amerikanerin', 'amerikanisch'],
           ['德国', 'Deutsch', 'der Deutsche', 'die Deutsche', 'deutsch'],
           ['法国', 'Französisch', 'der Franzose', 'die Französin', 'französisch'],
           ['日本', 'Japanisch', 'der Japaner', 'die Japanerin', 'japanisch']],
 'examples': [
     ('Ich komme aus China.', '我来自中国。'),
     ('Er ist Amerikaner, sie ist Amerikanerin.', '他是美国人，她是美国人（女）。'),
     ('Sprichst du Deutsch?', '你会说德语吗？'),
     ('Die Schweiz ist sehr schön.', '瑞士很美。'),
 ]},
{'num': 'M01-11', 'id': 'xueye', 'cat': 'vokabel', 'title': '学业和职业', 'titleDe': 'Studium & Beruf',
 'explain': 'lernen（学习，泛指）vs studieren（上大学）。学校：die Schule（中小学）/ der Schüler（中小学生）/ die Universität / der Student（大学生）。女性职业词以 -in 结尾、复数 +nen；男性以 -er 结尾单复同形；以 t 结尾的男性复数 +en；Koch→Köche、Arzt→Ärzte 加变元音。以 -tik 结尾的名词是阴性（die Informatik）。Kommissar 指刑侦警探，Polizist 是警察统称。\n\n🇬🇧 英语对照：英语 teacher/student 不分男女；德语职业词分阴阳性，女性统一 -in，和法语 -euse 思路类似。',
 'table': [['职业', '阳性', '阴性'],
           ['老师', 'der Lehrer', 'die Lehrerin'],
           ['医生', 'der Arzt', 'die Ärztin'],
           ['大学生', 'der Student', 'die Studentin'],
           ['工程师', 'der Ingenieur', 'die Ingenieurin'],
           ['厨师', 'der Koch', 'die Köchin'],
           ['学科', 'die Architektur（建筑）', 'die Informatik（计算机）'],
           ['学科', 'die Medizin（医学）', 'Jura（法律，无冠词）']],
 'examples': [
     ('Ich studiere Medizin in Berlin.', '我在柏林学医。'),
     ('Meine Mutter ist Lehrerin.', '我妈妈是老师。'),
     ('Er arbeitet als Ingenieur.', '他当工程师。'),
     ('Was bist du von Beruf?', '你是做什么工作的？'),
 ]},
{'num': 'M06-05', 'id': 'yanse', 'cat': 'vokabel', 'title': '颜色的表达', 'titleDe': 'Farben',
 'explain': '形容词首字母大写即变为中性名词（das Rot 红色）。hell-/dunkel- 前缀表浅深（hellblau 浅蓝）。本土颜色词作定语要加词尾（ein schwarzes Auto）；外来颜色词作定语不加词尾（ein rosa Auto）——"ein rosanes Auto"这种写法连本族人都常犯错。提问：Welche Farbe hat…?（…是什么颜色？）\n\n🇬🇧 英语对照：英语 pink/blue 作定语永远不变；德语本土颜色词要加词尾，外来词不加——这是个"土著 vs 外来"的双轨制。',
 'table': [['颜色', '形容词', '名词'],
           ['红', 'rot', 'das Rot'],
           ['蓝', 'blau', 'das Blau'],
           ['绿', 'grün', 'das Grün'],
           ['黄', 'gelb', 'das Gelb'],
           ['黑', 'schwarz', 'das Schwarz'],
           ['白', 'weiß', 'das Weiß'],
           ['粉（外来，不变）', 'rosa', 'das Rosa'],
           ['紫（外来，不变）', 'lila', 'das Lila']],
 'examples': [
     ('Welche Farbe hat dein Auto? – Es ist rot.', '你车什么颜色？——红色的。'),
     ('Sie trägt ein blaues Kleid.', '她穿着一条蓝裙子。'),
     ('Das Rosa steht dir gut.', '粉色很适合你。'),
     ('Ich mag dunkelblau.', '我喜欢深蓝色。'),
 ]},
{'num': 'M06-06', 'id': 'siji', 'cat': 'vokabel', 'title': '一年四季', 'titleDe': 'Jahreszeiten',
 'explain': '春 der Frühling、夏 der Sommer、秋 der Herbst、冬 der Winter——四个全是阳性。季节前用 im（im Frühling 在春天）。天气动词：regnen（下雨）、schneien（下雪），主语用 es：Es regnet. / Es schneit.。\n\n🇬🇧 英语对照：英语 in spring / in summer；德语 im = in dem（三格），季节是阳性所以用 dem。',
 'table': [['季节', '词汇'],
           ['春 der Frühling', 'der Regen（雨）、Es regnet.、der Wind（风）、die Wolke（云）'],
           ['夏 der Sommer', 'Die Sonne scheint.、die Hitze（酷热）、das Gewitter（雷暴）'],
           ['秋 der Herbst', 'der Sturm（暴风雨）、der Nebel（雾）'],
           ['冬 der Winter', 'der Schnee（雪）、Es schneit.、das Eis（冰）、die Kälte（寒冷）']],
 'examples': [
     ('Im Frühling blühen die Blumen.', '春天花开。'),
     ('Im Sommer ist es sehr heiß.', '夏天很热。'),
     ('Im Herbst fällt das Laub.', '秋天落叶。'),
     ('Im Winter schneit es oft.', '冬天经常下雪。'),
 ]},
{'num': 'M06-09', 'id': 'wupin', 'cat': 'vokabel', 'title': '个人物品', 'titleDe': 'Persönliche Gegenstände',
 'explain': '三类：箱包、衣物、随身物品。Rucksack 是双肩包，Mappe 是夹在腋下的小包/文件夹。女套装区分：Kostüm（裙式套装）、Hosenanzug（裤式套装）、Badeanzug（连体泳衣）vs Bikini（分体）。\n\n🇬🇧 英语对照：英语 backpack/handbag；德语箱包词多且细（Koffer 箱子 vs Tasche 包），买错词会闹笑话。',
 'table': [['类别', '词汇'],
           ['箱包', 'der Koffer（箱子）、der Rucksack（双肩包）、die Handtasche（手提包）'],
           ['衣物', 'das Hemd（衬衫）、die Hose（裤子）、das Kleid（连衣裙）、der Mantel（大衣）、der Pullover（毛衣）、die Socke（袜子）'],
           ['随身', 'das Geld（钱）、der Pass（护照）、das Handy（手机）、der Regenschirm（雨伞）、die Sonnenbrille（墨镜）、der Führerschein（驾照）']],
 'examples': [
     ('Wo ist mein Pass?', '我的护照在哪？'),
     ('Nimm einen Regenschirm mit!', '带把伞！'),
     ('Die Hose ist zu lang.', '这裤子太长了。'),
     ('Hast du dein Handy dabei?', '你带手机了吗？'),
 ]},
{'num': 'M07-07', 'id': 'jianzhu', 'cat': 'vokabel', 'title': '建筑、居家与方位', 'titleDe': 'Gebäude, Wohnen & Richtung',
 'explain': '方位：in der Stadt（城里）vs auf dem Land（乡下，介词不同！）、am Stadtrand（城郊）；东西南北 der Osten/Westen/Süden/Norden；links 左转、rechts 右转、geradeaus 直走。楼层：das Erdgeschoss 是底楼（德语从 0 开始，erste Stock = 我们的二楼！）。电梯 der Aufzug/Fahrstuhl。Keller 多指昏暗的地窖式地下室，Untergeschoss 可指商场地下一层。室内地面 der Boden vs 室外 die Erde。问洗手间：餐厅用 Toilette，别用 Bad/Badezimmer（必须带洗澡设施）；Klo 是口语，正式场合不用。Balkon 小阳台 vs Terrasse 大平台/露台。\n\n🇬🇧 英语对照：英语 first floor 在英美还不一样（英=我们的二楼，美=一楼）；德语 Erdgeschoss + erste Stock 跟英式一致，租房看房时别走错层。',
 'table': [['类别', '词汇'],
           ['方位', 'in der Stadt（城里）、auf dem Land（乡下）、links/rechts/geradeaus'],
           ['建筑', 'das Haus（房子）、die Wohnung（公寓）、das Hochhaus（高楼）、die Villa（别墅）'],
           ['楼层', 'das Erdgeschoss（底楼）、der erste Stock、der Aufzug（电梯）、die Treppe（楼梯）'],
           ['房间', 'das Wohnzimmer（客厅）、das Schlafzimmer（卧室）、die Küche（厨房）、der Balkon（阳台）'],
           ['周边', 'der Bahnhof（火车站）、die Apotheke（药店）、das Rathaus（市政厅）']],
 'examples': [
     ('Ich wohne auf dem Land.', '我住在乡下。'),
     ('Gehen Sie geradeaus, dann links.', '直走，然后左转。'),
     ('Wir wohnen im dritten Stock.', '我们住在三楼（德语 3 层）。'),
     ('Wo ist die Toilette, bitte?', '请问洗手间在哪？'),
 ]},
{'num': 'M07-08', 'id': 'zhufang', 'cat': 'vokabel', 'title': '住房申请', 'titleDe': 'Wohnungsbewerbung',
 'explain': '模拟租房申请表（中介 Immobilienmaklerbüro）。个人信息：Name（姓）、Vorname（名）、Geburtsdatum（出生日期）、Geschlecht（性别）、Geburtsort（出生地）、Nationalität（国籍）、Arbeitgeber（雇主）、Monatliches Einkommen（月收入）。住房要求：Anzahl der Zimmer（房间数）、Größe in Quadratmeter（平米）、Maximale Miete inkl. NK（最高租金含杂费）、Etage（楼层）、Lage（位置）、Ausstattung（配置）。Makler 可以是个人或机构，Agentur 只能指机构。金额写法 2900,– Euro（逗号是小数点，短横表示整）。\n\n🇬🇧 英语对照：英语租房也填 application form；德语 NK = Nebenkosten（杂费），看房时租金分 Kaltmiete（冷租）和 Warmmiete（暖租含杂费），问价要问 inkl. NK。',
 'table': [['字段', '德语', '中文'],
           ['姓名', 'der Name / der Vorname', '姓 / 名'],
           ['出生日期', 'das Geburtsdatum', ''],
           ['国籍', 'die Nationalität', ''],
           ['雇主', 'der Arbeitgeber', ''],
           ['月收入', 'das monatliche Einkommen', ''],
           ['房间数', 'die Anzahl der Zimmer', ''],
           ['面积', 'die Größe in Quadratmeter', '平米'],
           ['租金', 'die Miete inkl. NK', '含杂费']],
 'examples': [
     ('Wie hoch ist die Miete inkl. NK?', '含杂费租金多少？'),
     ('Die Wohnung hat drei Zimmer.', '这公寓有三个房间。'),
     ('Was ist Ihr monatliches Einkommen?', '您的月收入是多少？'),
     ('Die Wohnung liegt im zweiten Stock.', '公寓在二楼。'),
 ]},
{'num': 'M08-02', 'id': 'shenti', 'cat': 'vokabel', 'title': '身体部位', 'titleDe': 'Körperteile',
 'explain': '23 个词，复数要一起背。注意变音复数：Hand→Hände、Zahn→Zähne、Fuß→Füße、Kopf→Köpfe、Mund→Münder、Arm→Arme（不加变音也对，常用 Arme）、Finger 单复同形。说"哪疼"：Dativ + wehtun（Mein Kopf tut weh. 我头疼）。\n\n🇬🇧 英语对照：英语 tooth→teeth、foot→feet 也是变元音复数；德语变音复数（ä/ö/ü）是对应现象，成体系得多。',
 'table': [['部位', '单数', '复数'],
           ['头', 'der Kopf', 'die Köpfe'],
           ['眼', 'das Auge', 'die Augen'],
           ['鼻', 'die Nase', 'die Nasen'],
           ['嘴', 'der Mund', 'die Münder'],
           ['牙', 'der Zahn', 'die Zähne'],
           ['手', 'die Hand', 'die Hände'],
           ['手指', 'der Finger', 'die Finger'],
           ['胳膊', 'der Arm', 'die Arme'],
           ['腿', 'das Bein', 'die Beine'],
           ['脚', 'der Fuß', 'die Füße'],
           ['膝', 'das Knie', 'die Knie'],
           ['背', 'der Rücken', 'die Rücken'],
           ['肚', 'der Bauch', 'die Bäuche'],
           ['耳', 'das Ohr', 'die Ohren']],
 'examples': [
     ('Mein Kopf tut weh.', '我头疼。'),
     ('Er hat blaue Augen.', '他有蓝眼睛。'),
     ('Wasch dir die Hände!', '洗手！'),
     ('Mein Fuß tut weh.', '我脚疼。'),
 ]},
]


def main():
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'a1-kurs')
    os.makedirs(out_dir, exist_ok=True)
    data = []
    for p in GRAMMAR_POINTS:
        data.append({
            'num': p['num'], 'id': p['id'], 'cat': p['cat'],
            'title': p['title'], 'titleDe': p['titleDe'],
            'explain': p['explain'], 'table': p.get('table', []),
            'examples': [list(e) for e in p['examples']],
        })
    out = os.path.join(out_dir, 'grammar_kurs.json')
    with open(out, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
    print(f'wrote {out} ({len(data)} points)')

if __name__ == '__main__':
    main()
